### ISSUE TITLE
Local dashboard shouldn't be showing system files

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10071]
Response to GUI shouldn't include  `.<name>` files/directories.

**Comment by 4e6** [comment]
I will update the `--filesystem-list` command to filter hidden files. @somebody1234 do we need to make any changes in the dashboard?

**Comment by 4e6** [comment]
Ok, I will probably need to update the middleware as well
https://github.com/enso-org/enso/blob/084be279c57c7216bd16db3c95a5085e3ea5723f/app/ide-desktop/lib/project-manager-shim/src/projectManagerShimMiddleware.ts#L216-L219

**Comment by somebody1234** [comment]
yeah. if the format doesn't change then dashboard shouldn't need to change. *however*, i was kinda assuming we'd be using windows' mechanism for hidden files on windows, otherwise the filtering by name would be able to be done on the frontend side.


alternatively, the API could return `hidden` as an attribute instead - so the user could have the option to show hidden files temporarily - but that might be overthinking it.
