### ISSUE TITLE
cannot login on mac app

### ISSUE THREAD

**Issue by techieshark** [enso-org/enso#10223]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I open Enso the first time it prompted me to login. I am not sure if that worked as I now see this:

<img width="1042" alt="image" src="https://github.com/enso-org/enso/assets/1072292/9ca9448f-e55a-4a1f-b266-b5b27d240365">

### Expected behaviour

I am able to use Enso

### How we can reproduce it?

1. download Enso mac (apple silicon) from website or latest as of 9 June 2024.
2. open it
3. observe error

### Enso Version

enso-mac-arm64-2024.1.1-nightly.2024.6.9

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

MacOS Sonoma 14.5

**Comment by jdunkerley** [comment]
Hi @techieshark,

Apologies as part of moving our domain from `enso.org` to `ensoanalytics.com` we accidently broke this.
If you download the newest release it should work again: https://github.com/enso-org/enso/releases/download/2024.1.1/enso-win-x64-2024.1.1.exe

We will set up a workaround as well so that the old version works as well as soon as possible.

**Comment by techieshark** [comment]
Thanks. Can confirm that old version still broken but new version does work.

**Comment by farmaazon** [comment]
Fixed by #10221
