### ISSUE TITLE
Tabbing across widgets not working for newly added components

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10311]
- Add a Date.new component using the CB
- Click into the year widget
- Enter 2024
- Press tab

Expected behaviour:
Focus moves to the year widget

Actual behaviour:
Component is deselected

Interestingly if I click back into the same year widget on my already created component and change the year to 2023 and press tab it now works as expected.

**Comment by Frizi** [comment]
From my observation, this happens because once the year is entered, a placeholder widget is replaced with a non-placeholder version, so in effect it appears to stop being the currently active element.

In fact, the whole node view is replaced with a brand new one, because its top-level Ast element changes.
