### ISSUE TITLE
Ability to get a list of target conversion

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10545]
In order to enable widgets on the `Any.to` method it would be useful to be able to get a list of the current in scope conversions for a specified object.

**Comment by JaroslavTulach** [comment]
Possibly this is a duplicate of
- #7320

btw. it even has almost the same title! This has already been implemented by @4e6 as
- #7857

The only thing needed, is to use the provided information in the IDE. There even is [an exact description](https://github.com/enso-org/enso/pull/7857#issuecomment-1728991142) of what the IDE could do to enrich the component browser for any _value at hand_. If the method is named `.to` then the IDE should do following to compute the _"static"_ drop down:
- search for all methods named `from`
- where `that` argument represents _value at hand_
- include all those types in the drop down

**Comment by Frizi** [comment]
This could potentially be implemented as a dynamic dropdown widget for `Any.to` method argument. Though I think making a special case for this one and handling it fully on the client side may be justified, since it can be a potentially very large list and we already have all the data, as @JaroslavTulach pointed out.

**Comment by JaroslavTulach** [comment]
> dynamic dropdown widget for `Any.to` method argument

Such an implementation _cannot work reliably_. At most it can offer `from` conversions that are _already imported_. However there can be more suitable `from` conversions in the libraries. The IDE should offer all of them (and add imports appropriately) .

Btw. _I know that currently we import everything from our libraries, so the difference is currently small, but the difference is there and the gap will grow in the future._

Because the engine runtime cannot provide all `from` methods (at most only those already imported), the decision has been made (in #7320), it is the **Suggestion DB** that has to provide such a "global" information for every library.

> handling it fully on the client side may be justified

There is no access to suggestion DB in the engine runtime. As such **dynamic dropdown** approach cannot work - code computing dynamic widgets cannot use suggestion DB. As such the client side approach isn't _"maybe justified"_, but (almost) _necessary_ (unless the decision made in #7320 is questioned, reverted and somebody designs an API to expose suggestion DB to widgets computing code).

**Comment by JaroslavTulach** [comment]
- Mentioned in [June 2025 Reality Check](https://github.com/orgs/enso-org/discussions/11366#discussioncomment-13441368)
