### ISSUE TITLE
Move Component browser help

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10592]
https://github.com/enso-org/enso/issues/10582 Adds a new context help panel to the right side panel.

- In this story we want to remove the component browser help panel and use the new side panel instead.
- If panel is closed or on doc tab, it should open and switch to help tab
- On closing CB side panel should be restored to its previous state

**Comment by Frizi** [comment]
- Save "component browser help visibility" as a separate state
  - By default, it is visible
  - When you close side panel while CB is visible, set the state to "hide"
  - When you navigate to "help" tab in the panel while CB is visible, set the state to "show"
  - When you open the side panel while CB is visible, automatically navigate to "help" tab
  - Read the state when CB is opened. If it is "visible", open panel and the help tab, otherwise don't modify panel state.
 - Interacting with side panel should not close the CB.
