### ISSUE TITLE
Deleting connected nodes is broken

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11062]
Still seems to be related to order of selection

Version 2024.4.1-rc5
Build cb7e2d6973343aff354fa0caf43a11a9993d1665
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.4.1-rc5 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

[Multidelete.zip](https://github.com/user-attachments/files/16981542/Multidelete.zip)

https://github.com/user-attachments/assets/f3c1988d-b18a-40db-8d5f-b3f68a9dc44e

**Comment by farmaazon** [comment]
This is not about removing _all_ nodes (as I initially thought). The problem is with removing nodes connected to each other.

When you select number and `up_to` nodes from top to bottom (so the number node is selected first), and press `delete`, the second node stays in the scene regardless if there are any other nodes in the graph.

**Comment by farmaazon** [comment]
Investigated so far: the problem is in the GraphEditor, and sometimes happens, when one node is edited _and_ removed at the same time (which is the case here, as removing the first node edits the second).

We first run `updateNodes` function, which properly removes it and stops the watchEffect updating the node:

![image](https://github.com/user-attachments/assets/feb1273b-3b32-4875-afaa-f5d1799cb31d)

but the effect is still run later: we update the node code, "recreating" the node in the graph this way:

![image](https://github.com/user-attachments/assets/d7e0732f-1e86-46f3-b3fd-cd7740ecfa3f)

As a result, one node is still visible, while not even being in code editor.
