### ISSUE TITLE
Language server issue when project name is different in project.yaml from catalogue's name

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/enso#1110]
### General Summary
If project name is different in project.yaml from catalogue's name, Enso studio cannot run the code

### Steps to Reproduce

1. change project catalog's name without modifying project.yaml file
2. run Enso Studio

### Expected Result

Project.yaml is updated by language server

### Actual Result

Application can't find project_name.Main, loads file but cannot execute it.

**Comment by mwu-tow** [comment]
It is the same issue I once discussed with @4e6 on Discord. The project manager reports wrong project names (uses directory names rather the names from yaml). This must be addressed, as IDE has no other means of knowing the project name. (unless we are expected to parse package.yaml on our own?)

**Comment by 4e6** [comment]
The issue is that the project manager is not designed to deal with the manual filesystem changes.

Project manager maintains a project index `$HOME/enso/.enso/project-index.json` and uses it to manage the projects.

```json
{
  "projects" : {
    "e0559c54-801e-45e2-aca0-143d5dfc4d15" : {
      "id" : "e0559c54-801e-45e2-aca0-143d5dfc4d15",
      "name" : "Unnamed",
      "kind" : "UserProject",
      "created" : "2020-08-20T03:38:25.119942Z",
      "lastOpened" : "2020-08-31T07:08:28.802145Z",
      "path" : "/home/dbushev/enso/projects/Unnamed"
    }
}
```

So, all the file system changes that were not made with JSON-RPC API make the index inconsistent and lead to undefined behavior.

**Comment by mwu-tow** [comment]
@sylwiabr @4e6 
Ugh… so if user ever touches the name in `package.yaml` then the project becomes broken forever (well, until user manually cleans `~/.enso`) with no clear diagnostics? To me it still sounds like a bug. Unless there is huge red frame in our doc saying that user must not edit the file. 

Please consider:
* having some kind of hash/timestamp-triggered invalidation of the project index;
* performing sanity checks when opening the project.

Or, if we really want to go with the "user must not edit without JSON-RPC" then move the `package.yaml` to `.enso` subfolder, so it it considered "hidden" rather than part of public API.

**Comment by 4e6** [comment]
I assume that the current approach was designed to work in the cloud environment, where the user doesn't have direct access to the file system.

We can make the Project Manager more local-user friendly if we redesign it slightly:
- instead of maintaining the global index, Project Manager stores its metadata (created and last opened time) per project in the project's `.enso` directory
- when looking for projects, Project Manager scans the `~/enso/projects/` for subdirectories containing `package.yaml`
