### ISSUE TITLE
Project manager should update the asset if they have the same name

### ISSUE THREAD

**Issue by MrFlashAccount** [enso-org/enso#11166]
Steps to reproduce:

1. Open the dashboard, switch to local mode.
2. Upload a project with already existing name
3. On a duplicate dialog, select the "Update" button
4. Newly uploaded project should replace the old one

More context: https://github.com/enso-org/enso/pull/11111#pullrequestreview-2327506225

**Comment by 4e6** [comment]
Checking the current state of `develop` on Linux

> 1. Open the dashboard, switch to local mode.
> 2. Upload a project with already existing name
> 3. On a duplicate dialog, select the "Update" button
> 4. Newly uploaded project should replace the old one

When importing the project with the same name:
:heavy_check_mark:  the `Rename` button works correctly
:negative_squared_cross_mark: the `Update` button creates a duplicate project with the same name instead of replacing the project.

looking at the logic, I suppose that it was not designed to replace the existing project, but to create a duplicate one: https://github.com/enso-org/enso/blob/f37e50e87b24a62851858900889f3d8dca613a9b/app/ide-desktop/client/src/projectManagement.ts#L146-L154

it even deals with the directory name clashes: https://github.com/enso-org/enso/blob/f37e50e87b24a62851858900889f3d8dca613a9b/app/ide-desktop/client/src/projectManagement.ts#L335-L342

**Comment by 4e6** [comment]
Also, a comment about the renaming logic of `generateDirectoryName` function

> If given a name like `Name_1` it will become `Name_2` if there is already a directory named  `Name_1`
 
I used to name the projects according to the issue. For example, to test this issue I created a project `Issue_11166`, and the first time I tested, I did not expect and completely missed the new `Issue_11167` and `Issue_11168` directories that were created when I  imported the project twice.

Perhaps this naming logic is acceptable if we don't expect our users to use numbers to distinguish their projects.

**Comment by somebody1234** [comment]
well, it is a good point to raise, as you might run into this issue for dates as well

**Comment by 4e6** [comment]
AFAIK the Cloud adds `(1)` when duplicating the project. Although I'm not sure how different filesystems would handle the brackets

**Comment by somebody1234** [comment]
yeah. we use brackets for names in metadata, not sure what we should do for directory names. i think the intention of using plain old `_` was to avoid risking breakage, *although* we know for sure that windows and linux (and almost certainly macos) handle it fine. so perhaps we *should* change to (n)
