### ISSUE TITLE
Can't open projects on mac

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11210]
![image](https://github.com/user-attachments/assets/c9b077a2-e6ed-419c-866a-46ff40a67fb6)

Version 2024.5.1-nightly.2024.9.30
Build 28a470d705283706941c2269b979d5bce295f2d3
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.5.1-nightly.2024.9.30 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

**Comment by Akirathan** [comment]
`com.sun.jna` is supposed to be an automatic module that is fetched via sbt as `net.java.dev.jna:jna:5.14.0`. The artifact is named as `jna-5.14.jar` and put into the `built-distribution/.../component` directory. With @AdRiley we managed to pinpoint the issue to the fact that on Linux the derived automatic name for `jna-5.14.jar` is `com.sun.jna`, whereas for MacOS it is just `jna`. To see the derived automatic name, run:
```sh
jar --describe-module jna-5.14.jar
```

I will create a PR that will wrap `com.sun.jna` inside our own artifact, so that we have a full control over the module naming.

**Comment by JaroslavTulach** [comment]
>  on Linux the derived automatic name for `jna-5.14.jar` is `com.sun.jna`, whereas for MacOS it is just `jna`. To see the derived automatic name, run:
> 
> ```shell
> jar --describe-module jna-5.14.jar
> ```

Please report this issue (with a PR?) upstream to the JNA project. Let them specify the name in manifest to avoid such a dichotomy.

Should the source of the problem be in the JDK itself, consider reporting bug for openjdk with description and steps to reproduce. Let's report a service request to escalate the problem to Oracle support team.
