### ISSUE TITLE
Node added inside collapsed node is never executed.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#11251]
### Discord username

farmaazon

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I tried to check one of my parsed columns inside collapsed function, but it's gray forever. That is, until the project is reopened.

![Zrzut ekranu z 2024-10-04 09-34-59](https://github.com/user-attachments/assets/71bb2553-01b3-4280-b85a-3f616e004b5a)

### Expected behaviour

All nodes are executed, as I'm interested in their visualizations.

### How we can reproduce it?

Perhaps any side-branch of collapsed funtion has this issue?

If not, I attach the project here. I will also attach data file once I remove personal data.

### Enso Version

2024.5.1-nightly.2024.10.4

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Garuda

**Comment by 4e6** [comment]
After bisecting found out that the issue first appeared in #10785.
Then after the caches were enabled it was only reproducible with clean project caches. And #11032 made it visible even when the project caches were present.

Now I can assume that the issue is not showing up in the test scenario because the self argument does not have a UUID and therefore is not cached.

**Comment by 4e6** [comment]
The cache invalidation logic in the `EnsureCompiledJob` is fine. I tracked down the issue to the `DataflowAnalysis`. 

Given an example program

```py
main =
    Main.foo 42

foo x =
    a = 42
    x + 1
```

To fix the issue we need to invalidate the `Main` self-argument of the `Main.foo` call when the `foo` body changes. But the issue is that 
1. Function arguments (i.e. `x`) do not depend on the expressions in the function body using them. This means that whatever changes we make to the body, they don't invalidate the arguments.
2. The body may contain unused expressions i.e. `a = 42` (that should still potentially invalidate self-argument but we cannot track them with the DataflowAnalysis)
