### ISSUE TITLE
Make the Add Component control part of the output port

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11508]
![image](https://github.com/user-attachments/assets/9ec1085a-dd12-4733-a5e9-872df3993498)

I think the circle should be smaller than this. Maybe the same size as the one on the vector widget?

Problem:
We have 2 different UX paradigms for adding a new component. If a user discovers one they may miss the second.
Solution:
We should make the add component button part of the output port.

Question should it position itself where the new component will be added? So if there is already a component in the default position it will move to where the empty space is?

**Comment by farmaazon** [comment]
Refinement notes:
* We don't think moving button to the actual place of a new node is a good idea, because it need to be within the mouse active area of output port (and the user will have this button handy). But still it should be in the place of _default_ (unobscured) port placement.
* The implementation should consider multiple ports - each port will have its dedicated + button.
