### ISSUE TITLE
Opening workflow created in 2024.5.1-rc2 in 2024.4.2 breaks layout

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11742]
All of my layout gets broken when I open a 2024.5.1-rc2 workflow in 2024.4.2

**Comment by farmaazon** [comment]
We extended the metadata kept in the file.

If the older version cannot handle it, we cannot do much except making 2024.4.3.

**Comment by AdRiley** [comment]
That doesn't help users who already have the old version installed though.

What can we do to prevent this happening again in the future?

**Comment by farmaazon** [comment]
Notes from standup discussion:
* The proper fix would be to add metadata versions, and handle them properly (or warn user that the format is too new and any edit would break it).

**Comment by JaroslavTulach** [comment]
> If the older version cannot handle it, we cannot do much except making 2024.4.3.

There is a **solution for not confusing/crashing** the parser:
- **necessary**: turn stored **metadata into a comment** so that **older version ignores the comment** and does not try to parse it as metadata as that would fail
- **future proof** - add version to the metadata and if it is newer than expected (produced by some future IDE) then don't read it at all - tracked as #11479

However this is not going to give the old IDE ability to _"understand the layout"_ created by new IDE. Even
- #11479 

is not going to help with that. If the versioning is implemented, then the old version will (properly) refuse new versions of metadata to be even read in.
