### ISSUE TITLE
Clarify relationship between Enso, Luna and the various builds available

### ISSUE THREAD

**Issue by FeldrinH** [enso-org/enso#1270]
From the fact that enso.org currently links to luna-lang.org and the projects share a logo and old issues here reference Luna, I would assume the project has simply been renamed from Luna to Enso.
However, the [Getting Enso](https://github.com/enso-org/enso/blob/main/docs/getting-enso.md) page in this repo states that there are only nightly releases whereas the luna-lang.org page clearly has beta releases available and the technologies which Enso and Luna run on seem to be very different, which seems to indicate that Enso is a full rewrite of Luna or something along those lines.

For people just looking into Enso with no prior knowledge, such as myself, I think it would be important to add some sort of overview somewhere either in this repo or the luna-lang.org website clarifying what the relationship between Enso and Luna is and how the available Luna beta releases and Enso CI builds differ/are related.

**Comment by joenash** [comment]
Hey @FeldrinH, thanks for this! 

Totally agree: a lot happened at once, with us both transitioning to a new brand, and a new codebase. We first wrote about that in our devblog, which you can read [here](https://medium.com/@enso_org/enso-dev-blog-19th-june-2020-335e528d50b).

However as you’ve noted, with the old website still lurking around, and Enso still being pre-release, it’s a little slippery. We can’t expect everyone to find that blog post from June, or to find their way into the repos to observe that the Luna repository is archived.

We’re working on a new website at the moment. I think a lot of the problems you mention will be solved once that old luna-lang.org site is gone, because there simply won’t be any mention of the old beta releases, or luna. In the mean time, I’ll see what I can do to put some clearer signposting on the current site.

**Comment by FeldrinH** [comment]
Thank you for the quick response!

Regarding the devblog I noticed that the blog link on luna-lang.org goes to https://medium.com/@luna_language, where there are no posts.

<blockquote><img src="https://miro.medium.com/max/2400/1*VUHbEVx1nGAdHKbLQTk9jg.png" width="48" align="right"><div>Medium</div><div><strong><a href="https://medium.com/@luna_language">Luna language (now Enso) – Medium</a></strong></div><div>Read writing from Luna language (now Enso) on Medium. Looking for Luna, the visual programming language for data processing? Luna is now Enso. https://medium.com/@enso_org.</div></blockquote>

**Comment by joenash** [comment]
@FeldrinH Yep that is a known issue - the website (and all public facing things, really) have been neglected whilst the team is head down on the Enso rewrite. Before the end of the year, hopefully those things will have caught up with the current state of play :)

**Comment by joenash** [comment]
@FeldrinH PR is up to fix blog link on the old website now, whilst we wait for the new one. Will close this for now :)
