### ISSUE TITLE
Rudimentary Automatic Parallelism

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1352]
### Summary
Applying linear operations over lots of data is a common operation in data science. As these operations often are not interdependent they can fairly easily benefit from parallel execution. This task deals with creating a proof-of-concept implementation of automated parallelism for computations.

### Value
We prove that it is possible to do.

### Specification

- [ ] Determine an algorithm for automated parallelism of computations that:
  - [ ] Discover situations where there exist strictly separated dataflows. 
  - [ ] Execute these dataflows in parallel on available threads.
  - [ ] There should be a thread pinned to each available core.
- [ ] The implementation should explore techniques to reduce the overhead of spawning threads and (potentially) moving data to the threads to gain the best benefit from parallelism. 
- [ ] The implementation should provide a runtime option that determines whether or not this automated parallelism is enabled.
- [ ] The resultant algorithm should rely on technologies that are _currently_ available in the compiler and interpreter. It may, as a result, make some assumptions about the computations that it is parallelising (regarding observable side effects).
- [ ] It must show that processing of 4x 10MB dataframes in parallel results in a 3-4 times speedup. This analysis can assume the existence of a CPU with at _least_ four cores and need not run in the IDE.

### Acceptance Criteria & Test Cases

- [ ] The difference between parallel and serial should be 3-4 times speedup in favour of parallel execution, assuming an available at least 4-core processor and using single-threaded algorithms processing data in each of the flows.
- [ ] A repository with a script that runs the code with and without parallelism and compares the two.

**Comment by iamrecursion** [comment]
Consider the following program that should be amenable to parallelisation:

```
main =
    frame_1 = Table.read_csv "./data.csv"
    frame_1' = frame_1.filter (...)
    frame_2 = Table.read_csv "./data.csv"
    frame_2' = frame_2.filter (...)
    frame_3 = Table.read_csv "./data.csv"
    frame_3' = frame_3.filter (...)
    frame_4 = Table.read_csv "./data.csv"
    frame_4' = frame_4.filter (...)

    Table.merge [frame_1, frame_2, frame_3, frame_4]
```

This program consists of four strictly-separate streams of data processing that are merged in the final line. Each of these flows performs a filtering operation on the input table to create another table; each of these operations are entirely independent of each other.

While further development could discover _seperable_ data-flows in the program, this task deals only with the parallelisation of already separate data flows.

**Comment by iamrecursion** [comment]
The initial instinct is to annotate calls that are safe to have their inputs parallelised at the _definition_ site. However, for a call `x.f`, we do not know what the eventual call target for `f` will be (due to the fact that methods are dynamically dispatched). 

While we _could_ limit usage of this annotation to the statically-dispatched locals (functions, rather than methods), this case degenerates purely to annotating a _call_ to a particular function. Much like we have a `@Tail_Call` annotation that is placed at a _call site_, we could add an `@Auto_Parallel` annotation that is also used at a call site. An informal description of the semantics of this annotation are as follows:

1. For arguments `a_1, ..., a_n`, at a call-site annotated with `@Auto_Parallel`, determine the edges in the dataflow graph that end at these arguments.
2. Where some subset of these edges are _independent_, mark these computations as to be parallelised.
3. When executing the expression containing the annotated call, execute these computations in parallel to obtain their results. Join on the parallel threads and _then_ compute the result of the annotated call.

### Edge Separation
The first major question about this approach is _how_ and _to what extent_ do we determine whether edges are separate. As it turns out, we already have comprehensive dataflow information within top-level definitions in the compiler for caching purposes, making it relatively simple to perform this analysis and determine whether all incoming edges to the function arguments are made up of distinct regions in the graph.

Using the dataflow information for this task, however, imposes a number of caveats on the parallelism approach. As we do not yet have comprehensive purity information, the compiler has to take the presence of the `@Auto_Parallel` annotation as a promise from the programmer that there are no data races or side effects observable between the parallel data flows. With this guarantee, the compiler is then at liberty to run what it determines as separate data flows in parallel.

### Compiler and Runtime Changes
The second major question of this approach is how you actually architect such an approach at the runtime and compiler level. As far as I can see at this point, it requires the following moving parts.

- Discovery and attribution of the `@Auto_Parallel` annotation applied to applications.
- A pass to enumerate the arguments to the annotated call discover which of the associated data-flows are able to be parallelised. This pass will then handle transforming the program to insert IR nodes denoting parallel fork and join operations, re-parenting the separate data-flows to these nodes.
- The separate flows should be wrapped into nullary functions so they are represented as `CallTarget`s at runtime.
- The `Join` IR node will need to be inserted directly _before_ the annotated call, and will need to ensure that the resultant variable names are still in scope for the annotated call.
- These new nodes will require changes to alias, dataflow, and tail position analysis.
- To compliment these, new runtime nodes will need to be added: `ForkNode` and `JoinNode`.
  - `ForkNode` will be responsible for spawning threads to execute the individual data-flows, and registering those threads with the `ThreadManager`.
  - `JoinNode` will be responsible for waiting on joining the parallel data-flows, and then executing the expression that depends on them.
- Code generation will create these truffle nodes from the corresponding IR nodes.

It should be noted that doing this in this fashion will introduce an overall slowdown to the compiler. Much like any late-stage transformation of the compiler IR, this parallelism discovery pass will require both alias and dataflow analysis to be re-run after it. Alternatively, it must be responsible for updating the results of those analysis passes, but this is infeasible as a not-insignificant part of both passes logic would need to be replicated. Perhaps this is an opportunity to explore making those monolithic passes easier to run on more granular portions of the code than an entire module.

In interest of expediency, however, the simplest approach for now is to provide a global option to the runtime that enables or disables this behaviour, along with the additional analysis passes.

### Notes

- As this approach only deals with non-interdependent data-flows, there is no need to insert locking.
- If the threads have the chance of interacting with the `Context`, then we need to ensure that we call `Language::initializeThread` and `Language::disposeThread` at the start and end of thread execution.

### Open Questions

- Does Truffle/Graal have a special API for threads like it does for files? I can't find one, but that does not mean it does not exist.
- What are the scoping implications of this? Though certain variables may be seperable at the point of the annotated call, further on in the body they may still need to be in scope.
- How does threading interact with the language context? Are we going to end up with orphan nodes? I would imagine that the closure executed by the spawned thread would be a call target, which I _think_ avoids this issue.

**Comment by iamrecursion** [comment]
The result of the above design would produce code that looks similar to the following:

```
main =
    frame_1 = Table.read_csv "./data.csv"
    frame_1' = frame_1.expensive_operation (...)
    frame_2 = Table.read_csv "./data.csv"
    frame_2' = frame_2.expensive_operation (...)
    frame_3 = Table.read_csv "./data.csv"
    frame_3' = frame_3.expensive_operation (...)
    frame_4 = Table.read_csv "./data.csv"
    frame_4' = frame_4.expensive_operation (...)

    @Auto_Parallel Table.merge [frame_1, frame_2, frame_3, frame_4]
```

**Comment by iamrecursion** [comment]
Instead of a `ForkNode`, `JoinNode` duality we could instead have an async/await-style architecture. Where we have code similar to

```
x = table1.doThing
y = table2.doThing

print "Hello world"

z = x + y
```

We can perform a static translation to something equivalent to 

```
x_async = Async.spawn (table1.doThing)
y_async = Async.spawn (table2.doThing)

print "Hello World"

x = x_async.await
y = y_async.await

z = x + y
```

`Async.spawn` and `await` would require the creation of special `IR` nodes and special `ExpressionNode`s to represent these.

**Comment by iamrecursion** [comment]
An alternative approach is to annotate statically known methods as `@Pure`. Pure methods could then be parallelised with an async/await style process as above. `@Pure` methods would have to disallow lazy arguments such that we can always guarantee that the arguments are evaluated _before_ forking, and join points would have to join on the thread handles.

Threads should be handled through the [`TruffleLanguage.Env`](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleLanguage.Env.html) API. We do not know ahead of time whether you can execute a _node_ directly, but we can always execute a `CallTarget`. The `VirtualFrame` would need to be materialized.
