### ISSUE TITLE
Nightly Workflow

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1530]
### Summary
We want to be able to do fully-built nightly releases for users, and to enable better testing by the IDE. 

### Value
People will be able to test things better.

### Specification

- [x] Change our release and project management tooling to add support for nightly builds.
- [x] Add a workflow that runs the release process every night on cron. It should publish a nightly artefact named "Enso Nightly ISODATE" (e.g. `Enso Nightly 2021-03-01`) that should be a _pre-release_.
- [x] Alternatively it can be triggered by pushing a commit containing `[release: nightly]` in the commit message (`[release: stable]` will come later when we automate the main release flow).
- [x] It should also clean these up, keeping only the last _three_ of these prereleases.
- [x] Do not rebuild if no new commits since latest nightly.
- [x] Add a "Nightly" section at the top of the changelog (`RELEASES.md`).
- [x] Add a section to the PR checklist to update the new "Nightly" section at the top of the changelog (`RELEASES.md`). This section should accumulate all the changes from the last release.
  - [x] Check on PR CI if the changelog has been updated (unless skipped with `[no-changelog]` in commit msg).
  - [x] This check should be done in a separate workflow
- [x] These nightly workflows should copy the content from the "Nightly" section into the release notes.
- [x] Completion of the nightly workflow should send a webhook to trigger a nightly build in the IDE repo.
  - See https://github.com/enso-org/ide/issues/1495 
  - [ ] Prepared but can only be enabled when the above issue is finished.
- [x] Warn when creating a project tied to a nightly release.
- [x] If the version is a nightly and it does not exist, update the error message to explain this.
- [x] Document all of these features.

### Acceptance Criteria & Test Cases

- [ ] We build nightly releases on CI.
- [x] Our tooling has support for these nightly releases. 
- Test cases:
  - [x] Basic acceptance: the workflow runs on staging, creates working artifacts with correct version strings, the release is automatically published.
  - [x] Trigger on commit message; no trigger on other commits/PRs.
  - [x] The changelog check is correct: accepting changes, reporting lack of changes, but skipping the check if told to do so.
  - [x] Auto-trigger on cron.
  - [x] Not proceeding if no new changes on `main`.
  - [x] Removing older releases to keep only the 3 most recent ones.

**Comment by radeusgd** [comment]
The associated version will be based on the `version` from build.sbt: `<version>-SNAPSHOT-<ISODATE>`, for example `0.2.10-SNAPSHOT.2021-04-09`.

Todo:

Is this the moment where we also want to switch to `v?` tags? @iamrecursion This will add some additional work but maybe it is worth doing together with the workflow.

If not, the associated tag be `enso-<version>-SNAPSHOT.<ISODATE>`, for example. `enso-1.2.3-SNAPSHOT-2021-04-09`.

Otherwise the tag will be `v<version>-SNAPSHOT.<ISODATE>`.

**Comment by radeusgd** [comment]
Since we have two mechanisms for triggering nightlies: schedule and manual commit message, we may get more than 1 nightly release on a single day. But since the tag is created based on the version and date, if the version is not changed, the tag would be the same for all releases, so a conflict will arise.

Two solutions come up immediately:
- Each job should overwrite any previous runs from the same day.
  - One downside is that jobs started just after midnight will be overwritten by the scheduled nightly build.
- Subsequent builds should add some suffix to differentiate the tag.
  - Downside: the tag is computed when the release starts because the version string is baked into the built executables, but the release is published only after the builds (and we most likely want to keep it that way, to avoid creating an empty release in case the build fails). So this has a potential for race conditions - if another job starts before other one completes, they will get the same tag. Unless some other synchronization mechanism is used but I think the increased complexity is not justified here. Maybe we could just acknowledge that and be careful when triggering releases manually.

@iamrecursion what do you think?

Another related note is, should `[release: nightly]` infix trigger the build on push to any branch (thus allowing everyone with push access to create nightly releases) or should it only work on specific branches (`main`?)?

**Comment by iamrecursion** [comment]
> Is this the moment where we also want to switch to `v?` tags? @iamrecursion This will add some additional work but maybe it is worth doing together with the workflow.

Yep, let's make the swap.

> Since we have two mechanisms for triggering nightlies: schedule and manual commit message, we may get more than 1 nightly release on a single day. But since the tag is created based on the version and date, if the version is not changed, the tag would be the same for all releases, so a conflict will arise.

I would suggest we add a suffix to the tag.

> Downside: the tag is computed when the release starts because the version string is baked into the built executables, but the release is published only after the builds (and we most likely want to keep it that way, to avoid creating an empty release in case the build fails). So this has a potential for race conditions - if another job starts before other one completes, they will get the same tag. Unless some other synchronization mechanism is used but I think the increased complexity is not justified here. Maybe we could just acknowledge that and be careful when triggering releases manually.

GitHub has actually just come out with a solution for this. We want to use [concurrency groups](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency) in the workflow. This should be enabled across the nightly and true release workflows to prevent more than one release (of any kind) from running at once and potentially conflicting.

> Another related note is, should `[release: nightly]` infix trigger the build on push to any branch (thus allowing everyone with push access to create nightly releases) or should it only work on specific branches (`main`?)?

It should only work on specific branches (the filter should be configurable somewhere). For now, just `main`.

Can you please ensure that the exact process the automation performs is documented? It should be _possible_ to do manually in case something goes wrong.

As somewhat of an aside, with all this logic done how difficult would it be to add the automation for actual releases? It came up whilst I was away that people wanted to cut a release and didn't feel comfortable performing the process manually.
