### ISSUE TITLE
Can't install version 1.9 on Linux

### ISSUE THREAD

**Issue by commandodev** [enso-org/enso#1547]
### General Summary

I downloaded the latest installers from the website and github, but couldn't get it to work. Trying now with enso-bundle

### Steps to Reproduce

Download version 1.9 of the luna gui installer from the website, unzip and try to run it:

```
$ ./lunaInstaller 
Error during loading electron application: 
Luna installer finishes unsuccessfully

Error log:
 (
(electronLunaInstaller:1458673): Pango-ERROR **: 18:36:59.216: Harfbuzz version too old (1.4.2)

)
QFontDatabase: Cannot find font directory /home/ec2-user/dev/build-qt-static/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
```

I also tried `$ ./luna-manager install`, but:

```
$ ~/.luna/bin/luna-studio/current/luna-studio
bin/public/luna-studio/luna-studio: symbol lookup error: /tmp/.mount_luna-sjQkdDt/usr/lib/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
```

I also tried to download the ide, but:

```
ide-2.0.0-alpha.1$ ./run start --skip-version-validation



----------------------
--- Initialization ---
----------------------

Installing build script dependencies.
Calling 'npm install'
audited 47 packages in 1.061s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Calling 'node /home/ben/docs/1.Projects/Enso/ide-2.0.0-alpha.1/build/run start --skip-version-validation'
fatal: not a git repository (or any of the parent directories): .git
```

```
$ uname -a
Linux cdodev 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Expected Result

I would have expected that the installer would work, or that there would be instructions on required dependencies :-)

### Actual Result

See errors above

### Enso Version

1.9 (latest available from website)
2.0 beta of ide from github

I don't have anything that I can run `enso --version` on. What should I download to do this, and where from?

**Comment by commandodev** [comment]
I also tried

```
$ ../enso/bin/enso --version
Enso Launcher
Version:    0.2.6
Built with: scala-2.13.5 for GraalVM 21.0.0.2
Built from: enso-0.2.6 @ aec61292c467c3c52e2259ac9e8cd03670c77f15
Built on:   Linux (amd64)
Enso engine from project Playground: 
Enso Compiler and Runtime
Version:    0.2.6
Built with: scala-2.13.5 for GraalVM 21.0.0.2
Built from: enso-0.2.6 @ aec61292c467c3c52e2259ac9e8cd03670c77f15
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.10+8-jvmci-21.0-b06
            Linux 5.8.0-43-generic (amd64)
```

Created a project, but `enso run` didn't seem to work. All I got was this in the terminal:

```
$ ../enso/bin/enso run
[info] [2021-03-04T19:01:21.859Z] [akka.event.slf4j.Slf4jLogger] Slf4jLogger started
```

**Comment by commandodev** [comment]
Downloading the app image from here https://github.com/enso-org/ide/actions/runs/621925429 got me up and running, but all in all a pretty frustrating experience, which I would assume is losing you a lot of users :-)

<blockquote><img src="https://avatars.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/ide">enso-org/ide</a></strong></div><div>Enso – a visual and textual functional programming language. - enso-org/ide</div></blockquote>

**Comment by joenash** [comment]
Hey @commandodev, 

Sorry for the rough experience - I'm afraid that's because of our outdated website, which has sent you bouncing between a couple of different projects.

Luna <1.9 was deprecated over a year ago, as 2.0 necessitated a completely fresh code base. The app image you're now using that's working is the alpha for 2.0, on that new codebase. Our new website will be up soon, which should prevent folks from winding up on that old, very deprecated version. 

As for the problem you're running into [here](https://github.com/enso-org/enso/issues/1547#issuecomment-790852695) with blank output from the Enso run, that's actually a slightly different issue. Basically the default project template is optimised for the IDE, and so doesn't output anything to terminal (it doesn't contain print or anything like that). We'll look into a way to make the default project make sense from whichever environment (CLI or IDE) the user comes from.

Thanks again for persevering, and for the feedback!
