### ISSUE TITLE
Enso_Project is not a hint in the searcher

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1605]

**Comment by iamrecursion** [comment]
This is because it's a fake method that is added during codegen. To fix this we will:

- Add it in a compiler pass before codegen.
- Add a documentation block to it that contains the `DISPLAY name` tag, with `name` set to `Enso_Project`.
- Ensure that this method is collected by the suggestions collection.

As an aside, we should also add the `AKA` tag while we're here. It should take a space-separated list of alternate names.

**Comment by iamrecursion** [comment]
Due to limitations of the doc parser we can't do this as described above, at least in the near term. For now @farmaazon will handle this on the IDE side.
