### ISSUE TITLE
Access to project name 

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#1690]
### General Summary

1. Let the project/open method in the Project Manager API return project name in response (next to addresses and engine version).
2. Add additional endpoint to the Language Server returning engine version, project name, (it could be profitable to include project id as well). 

### Motivation

Currently, having the project id only I cannot determine a name of freshly opened project - therefore I need to keep paired information (id + name) wherever I want to keep the list of "projects possible to open".

Additionally, having only connection to the Language Server (which is the case in cloud environment) I cannot ask Language Server for the information I need and - I imagine - the LS has handy. (currently cloud provide us only a name)

**Comment by 4e6** [comment]
Implementation note.

The project manager starts the language server as an external process using the CLI runner interface. Currently, LS doesn't have CLI flags providing information about the engine version it runs, or the project name/id. 

Possible ways to get the required info:
- _engine version_ can be obtained from the build info. The `engine-runner` SBT project already depends on both, the `language-server` and the `version-output` project providing the build info. Language server can also depend on the `version-output`
- _project name_ can be obtained from the `package.yaml` project file. LS knows the project root, and can read the project definition
- _project id_ is a part of the project metadata which is stored differently in desktop and cloud environments, and only the project manager has access to the project id. We can pass it to the language server by using the CLI flag. Although, I'm not sure that we need to expose the project id this way because it is only used in the project manager API right now.

**Comment by iamrecursion** [comment]
After further discussion with @farmaazon we've settled on the following:

- The PM will return the project name in the response to a `project/open` request.
- The langauge server will discover both the engine version (via the build info), the runtime version, and the project name when asked via an endpoint.
- This second endpoint will be `workspace/projectInfo`.
