### ISSUE TITLE
Node Searcher 2.0

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#1753]
# Visual Design

## Base View

![image](https://user-images.githubusercontent.com/1623053/125221800-198e6b80-e2c9-11eb-9582-5439d97871a5.png)

The searcher consists of 3 panels:

- The favorite toolbar (top one), containing icons of the favorite tools.
- The browser toolbar (bottom left one), containing a hierarchical list of available tools.
- The documentation (bottom right), displaying documentation for the currently selected tool.

There are several basic assumptions in this view:

- There is almost always 1 tool selected (highlighted in blue). After opening the searcher, the first favorite tool is selected if any of the favorite tools is matched (they are filtered on the incoming data type). If the favorite toolbar is empty, the first item in the 3rd column is selected. There is only one situation possible when no tool is selected – after the user presses the up arrow key in the favorite toolbar – then the input field is selected, indicating that the "enter" key would insert the exact expression the user has typed (see the "Input Highlight" view).
- The columns have the same width, which is currently not configurable.

## Searching

![image](https://user-images.githubusercontent.com/1623053/125221818-201ce300-e2c9-11eb-86c9-84c8654437dd.png)

## Library Browsing

![image](https://user-images.githubusercontent.com/1623053/125221835-2612c400-e2c9-11eb-98df-9ba66b475f6b.png)

## Input Highlight

![image](https://user-images.githubusercontent.com/1623053/125223106-7be86b80-e2cb-11eb-87ab-a79dee654a89.png)

See task descriptions for detailed specifications of the required implementations.

**Comment by iamrecursion** [comment]
# Searcher Categories
The following is an outline of the searcher categories and what should be in them. For each function it names the qualified path so that the IDE can properly look up documentation. For the categories it names the module in which the category documentation will exist.

Please note that the order here is the order in which they should appear in the searcher. Some of these are extension methods, and so I have listed the _defining_ modules in addition to the fully qualified name.

## Data Science (`Standard.Searcher.Data_Science`)

### Input and Output (`Standard.Searcher.Data_Science.Input_And_Output`)

Note that for the first three, the names are only the location at which the _documentation_ will be found. They have no concrete implementation that should be used.

- Text Input (`Standard.Searcher.text_input`)
- Number Input (`Standard.Searcher.number_input`)
- Table Input (`Standard.Searcher.table_input`)
- Read Text File (`Standard.Base.Data.File.File.read`)
- Read Excel File (`Standard.Base.Data.File.File.read_xlsx`, accessible from `Standard.Table`)
- Read CSV (`Standard.Base.Data.File.File.read_csv`, accessible from `Standard.Table`)
- Write Text File (`Standard.Base.Data.File.File.write`)
- Write Excel File (`Standard.Table.Table.write_xlsx`)
- Write CSV (`Standard.Table.Table.write_csv`)
- To JSON (method `Standard.Builtins.Any.to_json`, accessible from `Standard.Base`)
- To Table (`Standard.Base.Data.Json.Object.to_table`, `Standard.Base.Data.Json.Array.to_table`, both accessible from `Standard.Base`)

#### Text Input Node

- Hard-coded in the IDE.
- Should insert a node with the expression `""`.

#### Number Input Node

- Hard-coded in the IDE.
- Should insert a node with the expression `0`.

#### Table Input Node

- Hard-coded in the IDE.
- Should insert nodes with the following expressions:

```
column_1 = ["name", "Enso"]
column_2 = ["stars", 5000]
table = Table.new [column_1, column_2]
```

This may require importing `Standard.Table`.

### Preparation (`Standard.Searcher.Data_Science.Preparation`)

- Select (`Standard.Table.Table.select`)
- Filter Rows (`Standard.Table.Table.where`)
- Clean Columns (`Standard.Table.Table.drop_missing_columns`)
- Clean Rows (`Standard.Table.Table.drop_missing_rows`)
- Drop Missing (`Standard.Table.Data.Column.Column.drop_missing`)
- Fill Missing (`Standard.Table.Data.Column.Column.fill_missing`)
- Add Column (`Standard.Table.Table.set`)
- First Row (`Standard.Table.Table.first`)
- Last Row (`Standard.Table.Table.last`)
- First N Rows (`Standard.Table.Table.take_start`)
- Last N Rows (`Standard.Table.Table.take_end`)

### Join (`Standard.Searcher.Data_Science.Join`)

- Join Tables (`Standard.Table.join`)
- Join Table (`Standard.Table.Table.join`)

### Transform (`Standard.Searcher.Data_Science.Transform`)

- Mask Columns (`Standard.Table.Table.where`)
- Get a Column (`Standard.Table.Table.at`)
- Transform Column (`Standard.Table.Data.Column.Column.map`)
- Transform Columns (`Standard.Table.Data.Column.Column.zip`)
- Sort Table (`Standard.Table.Table.sort`, `Standard.Table.Data.Column.Column.sort`)
- Rename Column (`Standard.Table.Data.Column.Column.rename`)
- Add Columns (`Standard.Table.Data.Column.Column.+`)
- Subtract Columns (`Standard.Table.Data.Column.Column.-`)
- Multiply Columns (`Standard.Table.Data.Column.Column.*`)
- Divide Columns (`Standard.Table.Data.Column.Column./`)
- AND Columns (`Standard.Table.Data.Column.Column.&&`)
- OR Columns (`Standard.Table.Data.Column.Column.||`)
- NOT Columns (`Standard.Table.Data.Column.Column.not`)

### Aggregate (`Standard.Searcher.Data_Science.Aggregate`)

- Group a Table (`Standard.Table.Table.group`)
- Sum Columns (`Standard.Table.Data.Column.Column.sum`,`Standard.Table.Data.Column.Aggregate_Column.sum`)
- Max Columns (`Standard.Table.Data.Column.Column.max`,`Standard.Table.Data.Column.Aggregate_Column.max`)
- Min Columns (`Standard.Table.Data.Column.Column.min`,`Standard.Table.Data.Column.Aggregate_Column.min`)
- Mean Columns (`Standard.Table.Data.Column.Column.mean`,`Standard.Table.Data.Column.Aggregate_Column.mean`)

### Compare (`Standard.Searcher.Data_Science.Compare`)

- Equality (`Standard.Builtins.Any.==`, available from `Standard.Base`)
- Inequality (`Standard.Builtins.Any.!=`, available from `Standard.Base`)
- Greater Than (`Standard.Builtins.Any.>`, available from `Standard.Base`)
- Greater Than or Equal (`Standard.Builtins.Any.>=`, available from `Standard.Base`)
- Less Than (`Standard.Builtins.Any.<`, available from `Standard.Base`)
- Less Than or Equal (`Standard.Builtins.Any.<=`, available from `Standard.Base`)

### Text (`Standard.Searcher.Data_Science.Text`)

- Length (`Standard.Builtins.Text.length`, available from `Standard.Base`)
- Check Emptiness (`Standard.Builtins.Text.is_empty`, available from `Standard.Base`)
- Check Non-Emptiness (`Standard.Builtins.Text.not_empty`, available from `Standard.Base`)
- Split Text (`Standard.Builtins.Text.split`, available from `Standard.Base`)
- Get Words (`Standard.Builtins.Text.words`, available from `Standard.Base`)
- Contains (`Standard.Builtins.Text.contains`, available from `Standard.Base`)
- Check Prefix (`Standard.Builtins.Text.starts_with`, available from `Standard.Base`)
- Check Suffix (`Standard.Builtins.Text.ends_with`, available from `Standard.Base`)
- Lower Case (`Standard.Builtins.Text.to_lower_case`, available from `Standard.Base`)
- Upper Case (`Standard.Builtins.Text.to_upper_case`, available from `Standard.Base`)
- Get Characters (`Standard.Builtins.Text.characters`, available from `Standard.Base`)
- Replace Text (`Standard.Builtins.Text.replace`, available from `Standard.Base`)

### Numbers (`Standard.Searcher.Data_Science.Numbers`)

- Range (`Standard.Builtins.Number.up_to`, available from `Standard.Base`)
- From Text (`Standard.Builtins.Decimal.parse`)
- Add (`Standard.Builtins.Number.+`)
- Subtract (`Standard.Builtins.Number.-`)
- Multiply (`Standard.Builtins.Number.*`)
- Divide (`Standard.Builtins.Number./`)
- Power (`Standard.Builtins.Number.^`)
- Maximum (`Standard.Base.Math.max`)
- Minimum (`Standard.Base.Math.min`)
- Exponential (`Standard.Builtins.Number.exp`, available from `Standard.Base`)
- Logarithm (`Standard.Builtins.Number.log`, available from `Standard.Base`)
- Natural Logarithm (`Standard.Builtins.Number.ln`, available from `Standard.Base`)
- Square Root (`Standard.Builtins.Number.sqrt`, available from `Standard.Base`)
- Sine (`Standard.Builtins.Number.sin`, available from `Standard.Base`)
- Cosine (`Standard.Builtins.Number.cos`, available from `Standard.Base`)
- Tangent (`Standard.Builtins.Number.tan`, available from `Standard.Base`)
- Inverse Sine (`Standard.Builtins.Number.asin`, available from `Standard.Base`)
- Inverse Cosine (`Standard.Builtins.Number.acos`, available from `Standard.Base`)
- Inverse Tangent (`Standard.Builtins.Number.atan`, available from `Standard.Base`)
- Pi (Constant) (`Standard.Base.Math.pi`)
- e (Constant) (`Standard.Base.Math.e`)

### Date and Time (`Standard.Searcher.Data_Science.Date_And_Time`)

- Current Time (`Standard.Base.Data.Time.now`)
- Current Date (`Standard.Base.Data.Time.Date.today`)
- Current Time Zone (`Standard.Base.Data.Time.Zone.local`)
- UTC Time Zone (`Standard.Base.Data.Time.Zone.utc`)
- Time from Text (`Standard.Base.Data.Time.parse`)
- Date from Text (`Standard.Base.Data.Time.Date.parse`)
- Time Zone from Text (`Standard.Base.Data.Time.Zone.parse`)
- Time to Date(`Standard.Base.Data.Time.Time.date`)
- Date to Time (`Standard.Base.Data.Time.Date.Date.to_time`)
- Change Time Zone (`Standard.Base.Data.Time.Time.at_zone`)

## Network (`Standard.Searcher.Network`)

### HTTP (`Standard.Searcher.Network.Http`)

- Fetch Data(`Standard.Base.Network.Http.fetch`)
- GET Request (`Standard.Base.Network.Http.get`)
- POST Request (`Standard.Base.Network.Http.post`)
- Get URI (`Standard.Base.Network.Uri.parse`)
- Build an Auth Header (`Standard.Base.Network.Http.Header.authorization`)
- Build a Header (`Standard.Base.Network.Http.Header.new`)

## System (`Standard.Searcher.System`)

### Filesystem (`Standard.Searcher.System.Filesystem`)

- New File (`Standard.Builtins.System.File.new`)
- Home Directory (`Standard.Builtins.System.File.home`)
- Current Directory (`Standard.Builtins.System.File.current_directory`)

### Process  (`Standard.Searcher.System.Process`)

- Run a Command (`Standard.Base.System.Process.run`)

### Environment  (`Standard.Searcher.System.Environment`)

- Read Environment (`Standard.Base.System.Environment.get`)

**Comment by iamrecursion** [comment]
One of the caveats with this system is that doing _proper_ filtering of these entries by `this` type is limited. While the IDE can filter based on the _concrete_ type of `this`, we have subtyping relationships between types. In order to do this, we possibly want to encode the known `supertypes` of a given type in the suggestions database. This would be done as a separate table.

I should note that this is not a tenable solution for the future as there are potentially infinite supertypes of any given type.

**Comment by iamrecursion** [comment]
An interesting example of [docs style](https://www.sidefx.com/docs/houdini/nodes/sop/subdivide.html).
