### ISSUE TITLE
Display Objects: on_hide and on_show of single instance are sometimes called in the same frame.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#2861]
### What did you do?
I've extended test "visibility_test4" with additional scenarios + add counters how many times the callbacks are called.

### What did you expect to see?
That the only on_show or on_hide is called at most once after each update.

### What did you see instead?
The assertion fails in one scenario (it's commented and marked with TODO).

### Enso Version
Commit with fullscreen visualizations.

**Comment by vitvakatu** [comment]
For reference: @MichaelMauderer spotted the issue while investigating https://github.com/enso-org/enso/issues/6501, the related test is currently disabled (because it is failing).

@MichaelMauderer please confirm that everything is correct :)

**Comment by wdanilo** [comment]
Despite the fact that these should not fire in a single frame, can this cause a bad display object state (is the last emitted event correct?)? I'm asking to know it this is an important or not so important issue.

**Comment by MichaelMauderer** [comment]
Needs to be investigated a bit. The underlying issue that I have observed is a bit different (and I will file a separate issue later today). It might be related, though, as it is caused by multiple successive show/hide events of grandparents and children and leads to shapes left in the scene. I'm not 100% sure if they fire in the same frame, though. It might be an issue of late firing FRP events.

**Comment by farmaazon** [comment]
Closing as not relevant to GUI2
