### ISSUE TITLE
Enable GitHub Discussions on the Enso Repo

### ISSUE THREAD

**Issue by zicklag** [enso-org/enso#3237]
### Summary

Currently the Enso website, and the GitHub issue template page links to GitHub discussions on this repo, but discussions are either not enabled, or not open to the public, and I am presented with a 404 page when following the links.

### Value

This is value for users who wish to discuss in a forum-like context, and also apparently supposed to be working according to the Enso website.

### Specification

GitHub discussions page can be visited by public GitHub users.

### Acceptance Criteria & Test Cases

Going to this link presents the GitHub discussions interface to a GitHub user not otherwise associated to the Enso project or team: https://github.com/enso-org/enso/discussions.

**Comment by wdanilo** [comment]
@zicklag the problem is that we had too many channels to monitor and we wanted to provide better support for a fewer amount of them. Our Discord is the well-supported channel to communicate with us: https://discord.gg/enso .

We will remove this link from our website. Do you feel that the forum-like experience would be much better for you rather than Discord?

<blockquote><img src="https://cdn.discordapp.com/icons/401396655599124480/09d62344b8e3e697ef853032422e9af8.jpg?size=256" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/invite/enso">Join the Enso Discord Server!</a></strong></div><div>Enso is an open source, visual language for data science. | 2,458 members</div></blockquote>

**Comment by zicklag** [comment]
> Do you feel that the forum-like experience would be much better for you rather than Discord?

I personally am almost never on chat platforms due to a rather unique network situation on the machine I'm often on. This might change in the future, but it's how it's been for me for now, so I can't usually access Discord.

For you guys, though, I definitely understand trying to keep things consolidated to avoid having a lot of channels to keep track of, so don't let my special case alone change your minds on that. :)

I think the forum-like workflow has a large benefit when you have a large or growing userbase and you want discussions to be searchable and persisted, but that might not yet be applicable to Enso yet, so you guys are probably doing the right thing by keeping GitHub discussions off for now.

**Comment by wdanilo** [comment]
@zicklag I will close that for now. We will revisit that when we will have bigger team and after we release the cloud version in a few months. Of course, please feel free to reopen it if you don't agree that it should be closed now.
