### ISSUE TITLE
Implement a Enso Vector Type

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#496]
### Summary
Enso needs a standard linear collection with O(1) access guarantees. This is `Vector`.

### Value
We have a linear collection in the Enso standard library.

### Specification

- [ ] Implement indexing syntax `[1, 2, 3] . 0`.
- [ ] Implement an immutable `Vector` type in Enso.
- [ ] Implement a mutable `Vector` type in Enso.
- [ ] The vectors should be boxed.
- [ ] Implement a set of useful operations for working with both kinds of vectors.

### Acceptance Criteria & Test Cases

- The above specification has been implemented.
- The above functionality has been rigorously tested.

**Comment by kustosz** [comment]
>  Implement indexing syntax `[1, 2, 3] . 0`.

I think we should think about it carefully and decide on the best approach.

1. We could implement it in a way of static desugaring, i.e. `[1,2,3].0` generates `[1,2,3].index 0`. I think this was the approach suggested before. The problem is obvious: it can only work if we're indexing by a literal. That's horrible, as it breaks referential transparence and is, frankly, useless (we have syntax that only works with literals, while we all know using literals is most of the time a code smell).
This problem can only be mitigated with the Type Checker, but only in the case when we can prove that the part after `.` is an integer. That's tricky, given that the integer can come from e.g. java. 

2. We could implement it as an extension of the dynamic semantics – "if the method being called is not a method but an integer, do the indexing thing". That works 100% of the time. The problem here is uniform call syntax. If
```
ix = 1
[1,2,3].ix
```
works, then 
```
ix = 1
ix [1, 2, 3]
```
should also work. But that leads to code like `1 [1,2,3]` being accepted, which is IMO very strange. Still, I find accepting `1 [1,2,3]` more acceptable than not accepting `[1, 2, 3].ix`.

3. We could use a different syntax for indexing. Even an operator like `!` would do the trick – we just go `[1, 2, 3] ! ix` and the intent is clear and there's no strangeness here. The downside is – accessing an element of a collection looks different than accessing an element of an atom. I think this downside is acceptable – accessing collection elements is inherently used differently than accessing objects. E.g. it is very rare to access atom elements by a programatically generated name, while it is very frequent with collections.

My personal take is: I believe 3. to be the best solution (up to choice of operator). If `3.` is not acceptable, then 2. Solution 1. is IMO the worst of them and is really useless.
Please voice your concerns @wdanilo @iamrecursion before end of day Tuesday, July 21

**Comment by wdanilo** [comment]
@kustosz Thanks for an amazing write-up and really good explanation of the problems. My thoughts are below:

1. You made a very good point that using literals is in most cases a "code smell", so the planned syntax sugar will be both not widely useful and also would encourage bad code practices. However,  always using explicit method names like `[1,2,3].index 0` is not a bad idea at all. Let's just agree that syntax `.0` doesn't make any sense and we should remove it, but lets keep explicit the `index` method call as the proposal of this point.

2. I really dislike this idea. If I understand correctly, given an expression `lst.foo` it would check if there exists a method `foo`, and if not, it will check whether `foo` is a number, and if so, it will use it for indexing? This sounds like a very complex system that would randomly fail. For example, after defining a new method which aliases with a local variable in some file, the file could stop compiling, as the method will be preferred over the local variable. This clearly shows me that this concept is deeply broken, as adding new methods in one file should never override local variable bindings in other files - I consider such a behavior a design mistake and thus a no-go.

3. This, of course, works, however, I'm not sure I see big (any?) advantages over the explicit `index` method. Sure, writing `lst ! 5` is shorter than `lst.index 5`, but the difference is so small that I would consider it negligible. Moreover, expressions like `[vars,ixs] . zip_with index` looks much more readable to me than `[vars,ixs] . zip_with (!)`. Anyway, this is just an operator, so it could be defined for any atom and just expand to the `index` method call if we want. If there will be strong preferences to have such an operator in std lib, I would go with just this solution (using it as sugar for explicit `index` call).

**Comment by kustosz** [comment]
Re 2.
It works the other way around and in fact already behaves this way in other circumstances.
Because of Uniform Syntax Call, we can't disambiguate `x.foo` and `foo x`. Therefore, if there's
a local variable called `foo` in scope, it will shadow any call to method `foo`. E.g. if there's a lambda
called `map` in local scope, `[1,2,3].map` will use the lambda, not the method.
The rationale is: `[1,2,3].map` must be the same as `map [1,2,3]`, which means you expect the local variable.
For a reference: this is exactly the way it works in Haskell – if you have a global function (incl a typeclass method)
and a local function with clashing names, you get the local.
That means – if there's a number `foo` in scope, `[1,2,3].foo` will currently always result in the error
"Sorry, `foo` is not a function". So, in essence, what you described does not occur. Please reconsider that
option again (I do not really like it, but the way you interpreted it is wrong, so you may have a different opinion
on the second try).

Re 3.
Indexing by literals is quite common in data science (e.g. get a column by name from a dataframe), so having 
a shorthand seems worthwhile to me. And indeed there's nothing stopping us from implementing both `index`
and `!` etc.

**Comment by kustosz** [comment]
> Indexing by literals is quite common in data science

I meant to say "indexing by constants", not "literals" :)

**Comment by wdanilo** [comment]
2. Oh, you are right, that's of course correct and much better behavior. Still, I don't like it. I like to understand what code does by looking at it. Seeing `lst.foo` should tell me - this is method call and the semantics should not base on the inferred type of `foo` - this idea feels so strange and so bad to me, that I'd not be happy to use it.

3. I think this is the best solution we have here.

**Comment by iamrecursion** [comment]
I think we should go with `index` as a method, with an operator shorthand. However, we can't use `!` as that's reserved for error ascription (e.g. `Handle in IO ! AccessError`). Whatever the choice, the rationale and description should be put in the design documentation.
