### ISSUE TITLE
File/Data read and read_text warnings

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5113]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184236852).
<hr />

Any file access issues (e.g. not existing or no permission) is an error.
If the file format is not supported should be an error.

Unlike text.from_bytes encoding errors should be treated as warnings by default. 

Likewise malformed CSV should also be treated as warnings (e.g. mismatched column count).

If the document is not parsable (e.g. invalid Excel, invalid JSON or unclosed " in CSV then an error should be raised.

**Comment by radeusgd** [comment]
TODO:
- [x] Tests for file access error ~~(use chmod on Linux, for now ignore elsewhere)~~
  - [x] Tests for all modes: Overwrite, Append, Backup; on all platforms since it is an important piece and possibly fragile (found a bug in backup mode)
  - [x] Fix Backup mode
- [x] Tests for failure if unsupported format
- [x] Add tests for File.read/read_text encoding issues being warnings by default
  - The tests are there, we just need to verify defaults are Warning.
- [x] There are tests for invalid column count, just add verification that they default to Warning.
- [x] Make unclosed " in CSV a hard error.
- [x] Add a test for reading a corrupted Excel file, expecting a `Corrupted File` error.
- [x] Add a basic test for reading a `.json` file.
- [x] Add a test for reading a malormed `.json` file, expecting a `Corrupted File` error.

Open Questions:
- Maybe the `Mismatched_Quote` error reported on unmatched " in CSV should be also merged to be the `Corrupted_File` error? cc: @jdunkerley
