### ISSUE TITLE
Simplify EPB PolyglotProxy with ReflectionLibrary

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5176]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183244827).
<hr />

[PolyglotProxy](https://github.com/enso-org/enso/blob/d87a32d0195b51a2526f95d32fbbbb0757b3d22b/engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/runtime/PolyglotProxy.java#L29) is responsible for _delegating interop messages_ from Enso to JavaScript, Python, R. It is a repetitive piece code fragile to copy&paste programming. It has to be updated with every GraalVM update (e.g. #182845176) as the set of interop messages changes.

[ReflectiveLibrary](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/library/ReflectionLibrary.html) has been recently discovered by us that could _simplify the whole proxying_ to a single `send` method.

Demonstrated on [WithWarnings](https://github.com/enso-org/enso/commit/f6340361a0d82047c56b59f8f2d20a209ba6c0b7#diff-d784205295fc228b108d6ca365bf8371e6fa2337bd8f2c38e7a3bdac721f3a30R14).

Can the same approach be applied to `PolyglotProxy`?

**Comment by JaroslavTulach** [comment]
- the code has already been simplified by #7882 
- The [PolyglotProxy & related classes](https://github.com/enso-org/enso/pull/7882/files#diff-ccad61bee766711b658faf056e1a3f9381d9a05a9537edb2ac85774d039f0f6d) were deleted
- Instead we rely on Truffle's own proxying between `TruffleContext` instances of Enso and JavaScript
- we reported https://github.com/oracle/graal/issues/8033 to be on par with Enso original implementation
- the fix was integrated on Sep 27, 2024: https://github.com/oracle/graal/pull/8266
- we are _not yet using it_ - we will once we upgrade to new Truffle

In any case, we can close this issue as fixed.
