### ISSUE TITLE
The message about losing connection with backend is delayed.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5196]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184390115).
<hr />

https://discord.com/channels/401396655599124480/1069912865261240371

According to JT:
> The message isn't shown immediately. When I kill the Java backend I see many attempts of the browser to reconnect:
eval    @    VM245:600074
handleError    @    VM245:598794
imports.wbg.__wbg_new_ac1b7ff8270166ee    @    VM245:600073
$web_sys::features::gen_WebSocket::WebSocket::new::hf12ae518514d6bc9    @    pkg-opt.wasm:0x1b12d68
$enso_gui::transport::web::Model::reconnect::hdaa39e9ccf437f47    @    pkg-opt.wasm:0x16e7f1e
$enso_gui::transport::web::WebSocket::reconnect_trigger::{{closure}}::h08c74648b973d196    @    pkg-opt.wasm:0x124a924
$<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h2429bc2d1e715588    @    pkg-opt.wasm:0x1b85c31
__wbg_adapter_40    @    VM245:598642
real    @    VM245:598629

> but the message isn't shown at that time. Only after 5-10s later.

It should be displayed as soon as we realize connection is lost.

### Notes

Important notes from @Frizi (https://github.com/enso-org/enso/issues/5196#issuecomment-1425626573):
> It appears that only engine-protocol ws connection Close event actually causes the error message to show up. Often this connection doesn't realise it's closed for a while, while other websockets are already trying to restart.

**Comment by Frizi** [comment]
Reproduced the issue. Websocket reconnection sequence starts happening before message is displayed.

It appears that only `engine-protocol` ws connection Close event actually causes the error message to show up. Often this connection doesn't realise it's closed for a while, while other websockets are already trying to restart.

![image](https://user-images.githubusercontent.com/919491/218074877-4f791a06-cb1d-4c00-8155-c4ff22f07b75.png)
The message is shown at the same time as the last log appears, and it can take a few seconds since json-rpc receives a close.

**Comment by jdunkerley** [comment]
Works fine on current version.
