### ISSUE TITLE
Update the shortcut documentation

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5206]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184369917).
<hr />

Check if the shortcut documentation is up-to-date and fix it if needed.

**Comment by somebody1234** [comment]
We have a global shortcut registry now, so it's potentially possible to auto-generate it from the bindings we define. @farmaazon thoughts?

(Of course, adding support for docs into the shortcut registry will be part of this task)

However, it may or may not be a good idea to either:
- wait until all the shortcuts are implemented in the new GUI
- add the rest of the shortcuts as part of this task

**Comment by farmaazon** [comment]
> We have a global shortcut registry now, so it's potentially possible to auto-generate it from the bindings we define. @farmaazon thoughts?

I don't have any. The only concern is the clash of the following good practices:
1. As a rule, the generated files should not be committed in repository (but I know exceptions)
2. The documentation should be available in GH repository.

Of course, we can keep a generated file in repo and just make CI check that generating again won't change it.
Or we may rely on a special site with documentation dev.enso.org, but I'm not sure how docs are uploaded there, and [there are rendering problems](https://enso.org/docs/developer/ide/product/shortcuts.html)

**Comment by somebody1234** [comment]
> As a rule, the generated files should not be committed in repository

FWIW I think this is a rule we can break. There are already (or there will be) a number of exceptions:
- The generated parser
- The Rust flatbuffers reader
  - This would be the case in TypeScript too, but... I guess there were issues with flatbuffers' TypeScript codegen?
- The demo PR will introduce a type containing all icon names generated from the SVG, and (more importantly) a JSON containing all icon names so that the storybook can display them all.

The idea is that, if there is a single source of truth it would be impossible for docs to get out of sync in the first place - however it's true that we'd want a CI check to make sure it's up to date

**Comment by somebody1234** [comment]
Of course, I don't think this is a particularly pressing issue either way. AFAICT, the current `shortcuts.md` *is* up-to-date, however it's possible that we want to keep this issue open for updating `shortcuts.md` with the (slightly different) GUI2 shortcuts

(or just keep this open forever because this is something that should more or less always be happening)
