### ISSUE TITLE
Display connections into lambdas expressions

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5304]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/183907328).
<hr />

Placeholder task for future reference
https://discord.com/channels/401396655599124480/1041669067188219914

Currently, the connections to variables used in lambda expressions are not displayed in the GUI. They should be.

**Comment by 4e6** [comment]
Displaying connections into lambda expressions requires support from the engine. Currently, lambdas are not instrumented, and the engine does not send updates about expressions inside the lambda body. I assume the engine should have the ability to "instrument once" expressions so that it does not affect the performance (i.e. the case when the lambda is applied to `map` function)

**Comment by wdanilo** [comment]
@4e6 thanks for the description. It's definitely not needed for release now, but it'd be nice to have it earlier than later.

**Comment by JaroslavTulach** [comment]
> ability to "instrument once" expressions

What does it mean: "instrument once"?

**Comment by jdunkerley** [comment]
Not currently in scope for the Beta release - might be brought back in as that is rescoped later.

**Comment by farmaazon** [comment]
Fixed in GUI2.
