### ISSUE TITLE
Fully qualified names aren't resolved

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5487]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182110423).
<hr />

### Steps to reproduce

This is a valid Enso program:

```
from Standard.Base import all

main = IO.println "Ahoj"
```

this is also a valid Enso program:

```
from Standard.Base import IO

main = IO.println "Ahoj"
```

why following one liner isn't valid?

```
main = Standard.Base.IO.println "Ahoj"
```

### Expected

With my Java `import` or _fully qualified names_ experience I'd expect the last program to be valid. In Java one can always spell the _FQN_ of a type that can be imported _per partes_. 

Wojciech believes _"it should be valid indeed!"_

Edward tried to convince me that importing _Standard_ is important and correct, as it sets the _namespace_.

I believe _namespace_ in Enso is given by [editions](https://github.com/enso-org/enso/blob/develop/docs/libraries/editions.md) and then even the _fully qualified name_ type shall be uniquely resolvable.

### Actual

```
$ cat >m.enso
main = Standard.Base.IO.println "Ahoj"
$ ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run m.enso 
In module m:
Compiler encountered errors:
m.enso[1:8-1:15]: The name Standard could not be found.
Exception in thread "main" Compilation aborted due to errors.
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:932)
        at org.enso.polyglot.Module.getAssociatedConstructor(Module.scala:19)
        at org.enso.runner.Main$.runMain(Main.scala:712)
        at org.enso.runner.Main$.runSingleFile(Main.scala:652)
        at org.enso.runner.Main$.run(Main.scala:539)
        at org.enso.runner.Main$.main(Main.scala:963)
        at org.enso.runner.Main.main(Main.scala)
```

**Comment by jdunkerley** [comment]
Believe this is very related to the work on #5037 - @hubertp please close if both covered.

**Comment by hubertp** [comment]
> Believe this is very related to the work on #5037 - @hubertp please close if both covered.

It is not. The support for FQNs was added in https://www.pivotaltracker.com/n/projects/2539304/stories/184213601 (https://github.com/enso-org/enso/pull/4056).
Except we limited the feature (on purpose!) so that one has to explicitly import the actual library not the specific namespace, always. To cut the long story short, one-linear won't work and we currently don't have plans to support. Adding it would need to consider the implications for dependency tracking mechanism.

I think we can close this though, because we now support FQNs minus the caveat I mentioned.

<blockquote><div><strong><a href="https://www.pivotaltracker.com/n/projects/2539304/stories/184213601">Impossible to call constructors with fully qualified names - Pivotal Tracker</a></strong></div></blockquote>

**Comment by jdunkerley** [comment]
Thanks @hubertp will close.
