### ISSUE TITLE
Panic occurs when node get Expression with invalid SpanTree

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5511]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/181342542).
<hr />

Note: This does not affect us greatly, because we don't provide invalid span-trees in the application. However, we should avoid panicking where possible. 

### Steps to reproduce
1. Use `expression_mock2` in "interface" debug scene. (replace one usage of expression_mock3)
2. Open the debug scene with console

### Expected
The displayed expression is wrong, but there is no panic

### Actual
Panic occurs.

**Comment by vitvakatu** [comment]
`expression_mock2` was removed from the codebase, you can find it here: https://github.com/enso-org/enso/blob/6b14ec5a630ee566d034895b5b57df01d942fbcd/app/gui/view/debug_scene/interface/src/lib.rs
The code should be updated for a new parser, I used the following:
```rust
pub fn expression_mock2() -> Expression {
    let pattern = Some("var2".to_string());
    let code = "make_maps size (distribution normal)".to_string();
    let output_span_tree = span_tree::SpanTree::default();
    let invalid_code = "Vector x y z".to_string();
    let parser = Parser::new();
    let invalid_ast = parser.parse_line_ast(&invalid_code).unwrap();
    let invocation_info = span_tree::generate::context::CalledMethodInfo { parameters: default() };
    let ctx =
        span_tree::generate::MockContext::new_single(invalid_ast.id.unwrap(), invocation_info);
    let input_span_tree = span_tree::SpanTree::new(&invalid_ast, &ctx).unwrap();
    let whole_expression_id = default();
    let code = code.into();
    Expression { pattern, code, whole_expression_id, input_span_tree, output_span_tree }
}
```

The issue is not reproducible – the displayed expression is invalid, and there is no panic. 

<blockquote><img src="https://opengraph.githubassets.com/0ea1ad01da910e0e483b5cdbce7f02c4a1e7d79b895a4a26d75826abfbb736d0/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso/lib.rs at 6b14ec5a630ee566d034895b5b57df01d942fbcd · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
