### ISSUE TITLE
Generate completion of `Table.join` join criteria using data from both joined tables

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#5629]
Currently the completion for`Table.join` `on` parameter only takes the left-side table columns into account.
<img width="353" alt="image" src="https://user-images.githubusercontent.com/919491/218154521-465ba2f2-e552-40f5-85a8-855aeeebed3b.png">
Ideally we want to compute the widget entries using column names from both tables. That requires new IDE and engine capabilities:
- Method metadata querying API needs to allow for providing more than one argument value.
- Visualization API needs to be extended to allow specifying multiple expressions for evaluation at once. Currently it is limited to one per visualization.
- Selection of requested method arguments to send for widget query needs to be specified, possibly as part of suggestion database, or as a widget metadata itself (that would require prior splitting of widget metadata and values query).

#### Acceptance criteria:
`Table.join` method `on` widget completion allows selecting join criteria using column names from both tables.

**Comment by jdunkerley** [comment]
As part of the JS Vue IDE work the ability to do this must be considered.

**Comment by Frizi** [comment]
So far, the limitation for this issue has been on the protocol level, not on UI. The discussion on it was started, but without any response yet https://github.com/orgs/enso-org/discussions/6832

<blockquote><img src="https://opengraph.githubassets.com/2525333f384229c3c4552a56725e43e6501cdd963f0cb901a4801b97e4037db2/orgs/enso-org/discussions/6832" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/6832">Widget Visualizations with multiple input expressions · enso-org · Discussion #6832</a></strong></div><div>Currently, the data for dynamic node widgets is requested using language server's Visualization API. That allows us to resolve method annotations using the data from evaluated method call's target....</div></blockquote>

**Comment by JaroslavTulach** [comment]
Trying to recollect my previous thoughts and work on this topic reminds me of
- #7833

Take a look at [* instead of + test](https://github.com/enso-org/enso/pull/7833/files#diff-66c31eb7d96aa14e9382f208b67e8b956f8369ee3c8358cfd910295266b5c04dR106) to see that there already is a way for an Enso code (**including visualization** code - _I hope_) to observe not only `self`, but also _other arguments_ when a call is made. E.g. once one:
- has the [UUID of a node](https://github.com/enso-org/enso/pull/7833/files#diff-66c31eb7d96aa14e9382f208b67e8b956f8369ee3c8358cfd910295266b5c04dR107)
- gets a pointer to [main function via `Meta.meta`](https://github.com/enso-org/enso/pull/7833/files#diff-66c31eb7d96aa14e9382f208b67e8b956f8369ee3c8358cfd910295266b5c04dR120)
- attaches [on_call instrument](https://github.com/enso-org/enso/pull/7833/files#diff-66c31eb7d96aa14e9382f208b67e8b956f8369ee3c8358cfd910295266b5c04dR120)
- and forces it to `activate`
- gets a [callback with arguments](https://github.com/enso-org/enso/pull/7833/files#diff-66c31eb7d96aa14e9382f208b67e8b956f8369ee3c8358cfd910295266b5c04dR110)

All that is needed (from _my point of view_) is to **design an experiment** to use this mechanism in the IDE. What one needs to do on the IDE side to [invoke the instrumenter](https://github.com/enso-org/enso/pull/7833/files#diff-66c31eb7d96aa14e9382f208b67e8b956f8369ee3c8358cfd910295266b5c04dR120), @Frizi? How are the _visualizations done_ in the GUI2?
