### ISSUE TITLE
sort handles Incomparable types by default

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#5742]
### Problem Definition

The following snippet should not fail with `Incomparable_Values` error:
```
[Nothing, Number.nan, 3, 2, 1].sort
```
The problem is, that `Nothing` and `Number.nan` are _incomparable_, i.e., they return `Nothing` from their `compare` method, whereas integers and decimals are comparable.

### User Wanted Behavior

- User can sort vectors with `Nothing`: Nothing ends up together at one end. No warning.
- User can sort vectors with `NaN`: `NaN` ends up next to floats above `Nothing`. Attach a warning .
- If incomparable types (with different `Comparator.from`) found: [Parcel into groups](https://github.com/enso-org/enso/issues/5742#issuecomment-1444995335), sort independently and attach a warning. Bigger parcel first, smaller then.

### Warn, Fail or Nothing 

Introduce [new parameter](https://github.com/enso-org/enso/issues/5742#issuecomment-1443859093) to `sort`: `(on_incomparable = Warn) : Fail | Warn | Accept`.

Re.  _"...ends up at one end..."_ - (optionally in @JaroslavTulach opinion)  introduce a new argument in `sort` method that specifies how these incomparable values should be handled - whether they should be sorted at the very beginning of the vector, or at the very end.

### Technical Specification

Comment below [describes the desired behavior](https://github.com/enso-org/enso/issues/5742#issuecomment-1444995335). Few notes:
- `Nothing` has a special treatment - and ends up at one end
- Proper [topological sort](https://github.com/enso-org/enso/issues/5742#issuecomment-1444995335) is a future work and will be tracked as #5834 issue.
- We'll have `compare: Any -> Any -> (Ordering | Nothing)`
- `NaN` compares to `Nothing` with everything - it'd be great to not treat it as a special case, but as a regular one - if possible
- Without [topological sort](https://github.com/enso-org/enso/issues/5742#issuecomment-1444995335) - as soon as there is something that compares to `Nothing` - leave that at its position sort only the other elements(!?).

### Related

Comparators were introduced in #4067, see `Ordering.enso` for docs.

Related: 
- #5739
- #5626
- #5834

**Comment by jdunkerley** [comment]
Wanted behavior:
- User can sort vectors with Nothing: Nothing ends up together at one end. No warning.
- User can sort vectors with NaN: NaN ends up next to floats above Nothing. No warning.
- Other Incomparable types should end up at one end with a warning attached.

**Comment by radeusgd** [comment]
Do we specify what happens for Vectors like `v = ["c", 2, "a", "b", 3, 1, Nothing]`?

Implicitly, I think the idea is to group by type? So `v.sort == ["a", "b", "c", 1, 2, 3, Nothing]`? I think it would be good to clarify if we do that or something else.

If that's the solution, how do we determine the relative order between types?

**Comment by JaroslavTulach** [comment]
I'd suggest a new parameter to `sort`:
```
(on_incomparable = Warn) : Fail | Warn | Accept
```
The behavior is clear when `Fail`. We may have a special treatment for fixed set of special types like `Nothing`  or even `Nan`, but in general we have following issue: There are two groups of objects which aren't comparable. _Which one shall be first and which one shall be second_?

The only idea I have is to put the bigger one as first and the smaller one second. The size of a group can either be *size of set* or it can be *size with duplicates*. Each may have some nice parameters.

> how do we determine the relative order between types

I don't think we can do it in general - Unless you want to do it by comparing their fully qualified names. We can treat few fixed types especially and hardcode their order.

**Comment by Akirathan** [comment]
> Other Incomparable types should end up at one end with a warning attached.

You mean the warning should be attached to the vector, not to the incomparable value, right? Attaching it to the incomparable value seems not useful, as it would be hard for the user to spot that there is some warning attached, whereas with the warning on the vector it would/should be visible straight away.

>> how do we determine the relative order between types

> I don't think we can do it in general - Unless you want to do it by comparing their fully qualified names. We can treat few fixed types especially and hardcode their order.

I think sorting of a vector with mixed types makes sense as long as the types are "primitive", i.e., numbers, text, nothing - and for them, we can determine that, e.g., numbers come before text or vice versa. If there is a mixture of other types, trying to sort it should IMHO fail anyway. Users should provide their own comparator functions for such a non-standard collection of values.

>I'd suggest a new parameter to sort:
`(on_incomparable = Warn) : Fail | Warn | Accept`
The behavior is clear when Fail. We may have a special treatment for fixed set of special types like Nothing or even Nan, but in general we have following issue: There are two groups of objects which aren't comparable. Which one shall be first and which one shall be second?
>The only idea I have is to put the bigger one as first and the smaller one second. The size of a group can either be size of set or it can be size with duplicates. Each may have some nice parameters.

According to my previous note, the only incomparable types that we would sort by default would be just `NaN` and `Nothing`. Mixing other incomparable types, including the ones from stdlib, should result in failure anyway. What do you think? In general: Do we want to sort as much stuff as possible, or rather be explicit about it?

**Comment by JaroslavTulach** [comment]
Another interesting topic from a discussion with @radeusgd: 

> what if I define a type Set where ordering is by inclusion
then I don't really have good answers for which items are to be deemed comparable which not
some pairs will compare and some not, every item is comparable to emptyset

Clearly such sets can only have _"partial order"_. If you have type Set with a comparator based on set's elements, then all objects of type Set will be grouped together (as they share the same comparator) and they shall end up in some topological order. Of course that would require `compare : T -> T -> Ordering | Nothing` as originally proposed in 
- #5008

**Comment by radeusgd** [comment]
With the above in mind, we also need to be aware that the user may define an ordering which may not necessarily be symmetric, reflexive or transitive.

In these cases, we cannot really do much - probably should keep the order of elements as-is, maybe report some warning. But ideally we shouldn't for example enter an infinite loop if we get an example where `a < b < c < a`. So I think we should have tests for such adversarial cases. Not needing to do miracles, but ensuring that they do not blow up in our face.

**Comment by JaroslavTulach** [comment]
> If there is a mixture of other types, trying to sort it should IMHO fail anyway. Users should provide their own comparator 

@Akirathan, such attitude leads towards the _"Rust approach"_:
- according to @Frizi one cannot sort array of double values without a custom comparator
- because doubles can also contain `NaN` and that means doubles aren't _"sortable"_
- that's proper [rationalistic approach](http://wiki.apidesign.org/wiki/Rationalism) - seeking _truth, beauty, correctness_ - I like it and it fits _Rust mindset_ of _computer science degree programmers_ well
- however Enso targets [completely different set](http://wiki.apidesign.org/wiki/Cluelessness) of people and as such a more [pragmatic approach](http://wiki.apidesign.org/wiki/Pragmatic) is necessary

The goal of Enso `sort` is to **always sort** and do it **well** without any users providing custom comparator to `sort` as an argument. Of course, we need to find a balance to do it right. However everytime we force an Enso user to loose [Cluelessness](http://wiki.apidesign.org/wiki/Cluelessness) by writing a comparator to overcome a *sort failing* to do anything - we did a suboptimal job!

> even more than [Cluelessness](http://wiki.apidesign.org/wiki/Cluelessness), I'd like to strive for **Correctness** - ensure we don't return a "sorted" value to the user which is not really sorted the way they intended because they mixed the types for example - in that case I think **warn is ideal, fail is OK**

You are right @radeusgd, a *warning must be attached* whenever the `sort` encounters partial ordering issues. However completely bailing out signals our own failure, so I wouldn't do it (unless user explicitly requests such a strict mode) - I am convinced a *meaningful sort order is always possible*.

> With the above in mind, we also need to be aware that the user may define an ordering which may not necessarily be symmetric, reflexive or transitive.

Right, we shall know what to do when the _ordering constraints decay_. Here is a classification of various cases and proposal how to handle such situation.

#### Linear Ordering

If all values are subject to [linear order](https://en.wikipedia.org/wiki/Total_order) we just sort them. They all must have the same `Comparator.from` obviously. All pairs return real value from `Ordering.compare`. We use the `Ordering` values and run classical sort. No warnings attached.

#### Default Comparator

Many of the builtin Enso types have the same _"default comparator"_. That is beneficial for the purposes of performance and allows the engine to perform various optimizations. However, from a logical perspective - different kinds of builtin are supposed to be treated as having _"different comparator"_.

It is up to the engine `sort` method to treat `Text` and `Number` as having (logically) _"different comparator"_ and treat them according to the **Differerent Comparators** section.

####  Different Comparators

Values that don't have the same `Comparator.from` aren't comparable by definition. Different types are usually not comparable (unless they share the same `Comparator.from` like `Integer` and `Decimal` types). We parcel the data into groups with the same comparator. Each group is sorted independently and then we somehow (discussed [here](https://github.com/enso-org/enso/issues/5742#issuecomment-1443859093) for example) place the sorted groups one after another.

#### Partial Order

The current design of comparators tries hard to avoid _"partial ordering"_ (inside of a single `Comparator.from`) - that's proper [rationalistic approach](http://wiki.apidesign.org/wiki/Rationalism) - however it has unwanted consequences:
- #5739

I don't like `Nan` type - it _feels so artificial_. I believe there are no real benefits of avoiding _partial ordering_ for the `sort` operation, so let me assume we have `compare : T -> T -> (Ordering | Nothing)` comparators and analyze the consequences.

##### Topological Sort

Objects with _partial ordering_ can still be sorted by [topological sort](https://en.wikipedia.org/wiki/Topological_sorting). We will optimistically _speculate on linear order_ of all values, but as soon as we find out it is not there, we resort into _topological sorting_ and attach warnings to notify the user.

_Topological sort_ may produce different results, but every result it produces respects all the specified `Ordering` conditions. As a result the [typical Enso user](http://wiki.apidesign.org/wiki/Cluelessness) shall be satisfied with the result. Any two values in the result will either be in the right order or the user will not care about their order.

##### Violated [Transitivity](https://en.wikipedia.org/wiki/Transitive_relation) or [Anti-Symmetry](https://en.wikipedia.org/wiki/Antisymmetric_relation)

Custom `Comparator.from` may violate various [partial ordering](https://en.wikipedia.org/wiki/Partially_ordered_set) constraints, so a regular _topological sort_ may not be possible. Usually that happens if there is a _cycle_ (e.g. `a < b < c < a` ) in the ordering.

Even such situation has a reasonable solution (and I [implemented it once](https://github.com/apache/netbeans/blob/14b7e4b530f5ea9f9222bcd10a9558c809ede331/platform/openide.util/src/org/openide/util/TopologicalSortException.java#L85) in the past) - just detect each cycle and _collapse the cycle_ into a _single element_. Perform a _topological sort_ on the simplified graph (succeeds as all cycles have been eliminated) and then expand the collapsed elements back.

The elements that violated anti-symmetry are in random order, but all the other elements are properly sorted. [Typical Enso users](http://wiki.apidesign.org/wiki/Cluelessness) shall welcome such result especially with a handful warning describing which elements couldn't be sorted because they formed a cycle.

##### Violating [Reflexivity](https://en.wikipedia.org/wiki/Reflexive_relation)

It is not possible in Enso for `x == x` not being `True`. If `Meta.is_same_object x x` then `Any.==` returns `True` immediately.

##### Violating Stability

What if two subsequent calls to `compare a b` yield different result? That shall never happen - especially not in a functional language like Enso - should that happen it is a bug in the `Comparator.from` implementation and needs to be fixed there.

#### Benefits of Trying to Sort Hard

There are reasonable data structures that cannot have total order, just partial one. @radeusgd mentioned:

> what if I define a type Set where ordering is by inclusion
> then I don't really have good answers for which items are to be deemed comparable which not
> some pairs will compare and some not, every item is comparable to emptyset

Having a flexible `sort` that can deal even with _partially ordered_ structures like a `Set` expands the number of use-cases users may **easily use Enso** for. Supporting decayed situations (like _topological sort with cycles_ use-case) while optimistically speculating on having [linear order](https://en.wikipedia.org/wiki/Total_order) leads to a _flexible sort support_ without any compromises of _fast sorting speed_ in the [most common case](https://en.wikipedia.org/wiki/Total_order).

**Comment by radeusgd** [comment]
> ...
> Right, we shall know what to do when the _ordering constraints decay_. Here is a classification of various cases and proposal how to handle such situation.
> ...

Thanks @JaroslavTulach for this amazing writeup! The new sorting design looks really really great IMO

**Comment by JaroslavTulach** [comment]
>  optimized sort node for the most common case when all the elements of a vector have the default comparator

After discussion with Pavel I've modified the [specification](https://github.com/enso-org/enso/issues/5742#issuecomment-1444995335) to include:


> #### Default Comparator
>
> Many of the builtin Enso types have the same _"default comparator"_. That is beneficial for the purposes of performance and allows the engine to perform various optimizations. However, from a logical perspective - different kinds of builtin are supposed to be treated as having _"different comparator"_.
>
> It is up to the engine `sort` method to treat `Text` and `Number` as having (logically) _"different comparator"_ and treat them according to the **Differerent Comparators** section.

**Comment by radeusgd** [comment]
> **Pavel Marek** reports a new **STANDUP** for today (2023-04-07):
> 
> **Progress:** Found out that the OutOfMemoryError is caused by too frequent reassignment of a single warning attached to the sorted vector. Every InvokeMethodNode creates a new Warning object with a new reassignment location. This is a potential bug in how we process warnings. Next week, I will try to reproduce this and create a separate issue for that. It should be finished by 2023-04-07.

What could be related to this issue is that our warnings get duplicated easily. I was advocating to do something about it a while ago, but I think after all no issue was created, maybe it is time.

Here is a related discussion: https://discord.com/channels/401396655599124480/951879392743796757

<blockquote><img src="undefined//discord.com/assets/652f40427e1f5186ad54836074898279.png" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/channels/401396655599124480/951879392743796757">Discord - A New Way to Chat with Friends & Communities</a></strong></div><div>Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.</div></blockquote>
