### ISSUE TITLE
Fully qualified names including same type and module names are not resolved properly

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#5902]
When attempting to use a fully qualified name inside an expression, some FQNs are triggering an unexpected error, failing to resolve. It hapens whenever the path contain a module, which itself contain a type of the same name (e.g. `Error`, `Problem_Behavior`).

<img width="665" alt="image" src="https://user-images.githubusercontent.com/919491/224719340-c3cf585d-294d-46cc-bfee-fdc706e52537.png">

The resolution is eagerly resolving a type when its name matches module name. For example, following node is resolved to a type, even though the path only resolves to a module (this is likely an expected behavior):
<img width="287" alt="image" src="https://user-images.githubusercontent.com/919491/224721092-3a7159ee-0ead-4b97-95d9-43b44be9391f.png">

When resolving longer paths with subpaths matching this scenario, the whole resolution fails.

Example code:
```
main =
  Standard.Base.Error.Problem_Behavior.Problem_Behavior.Ignore
```

Reported error:
```
Method `Problem_Behavior` of Error could not be found.
```

**Comment by hubertp** [comment]
I can confirm that this happens for modules which also have a builtin type named the same. In this case `Error` is causing problems because `Problem_Behavior` is not present in the right scope. Probably related to the whole eigentype and method registration but I will confirm once I find the root cause.

**Comment by hubertp** [comment]
Turns out this is actually an expected behaviour. `Standard.Base.Error` resolves to `Standard.Base.Error.Error` because `Standard.Base.Main` exports `Error.Error` and that takes a precedence over the FQN. Since `Error.Error` doesn't have a member  `Problem_Behavior` the compiler error is correctly reported.

I will see if I can somehow force it to neglect exports declared in `Main.enso` when we use FQN.

**Comment by wdanilo** [comment]
Should we allow for such exporting? I think this is confusing. If `Standard.Base.Main` exports something that collides with defined module, like here, this should probably not be allowed. What do you think @hubertp?

**Comment by hubertp** [comment]
> Should we allow for such exporting? I think this is confusing. If `Standard.Base.Main` exports something that collides with defined module, like here, this should probably not be allowed. What do you think @hubertp?

I think using a fully qualified name is as unambiguous as it gets, irrespective of any exports present in `Main`, so i'd rather fix the underlying problem.

**Comment by hubertp** [comment]
Thinking even more (and comparing to e.g. `Standard.Date.Text`) I start to lean towards your solution @wdanilo. 
The sole existence of type `Error` within the module of the same and then having submodules on the same namespace makes it rather difficult (if not impossible) to disambiguate. 
We don't have that problem with `Text` despite the fact that `Main` exports `Date.Text.Text` e.g. `Standard.Date.Text.Line_Ending_Style.Line_Ending_Style.Unix` works just fine. This is because there is no `Date` type.
