### ISSUE TITLE
Widgets on `take` are not inserting brackets correctly and cause weird behavior

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5925]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/224997616-464deb2a-c5d2-4859-a01f-9ccda89d67cb.mov

`operator2.take Index_Sub_Range.First count 2` where `count` is an argument which causes an error 
or `operator2.take Index_Sub_Range.First` which works with default value(1) and have a placeholder for count

### Expected behaviour

`operator2.take (Index_Sub_Range.First count)` So when user selects `Index_Sub_Range.First` it is placing the brackets correctly and user can add/edit an argument

### Enso Version

888307f03ff661d78bd1c5b652cca11428055333

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by sylwiabr** [comment]
Similar problems has `order by` on `Table` 

https://user-images.githubusercontent.com/12892578/225020823-dae27ce8-f3bf-4199-920e-a281367ae56c.mp4

**Comment by Frizi** [comment]
The expected behaviour from this bug is implemented in #5705. When `Index_Sub_Range.First` is selected from dropdown, it should be inserted with parentheses.

Unfortunately, this is not enough to completely fix this issue. When the node is edited manually to `operator2.take Index_Sub_Range.First`, the placeholder will show up, and connecting a node to it will not insert parentheses. Also, it is visually not clear that the arguemnt is connected to `Index_Sub_Range.First`, and not the `take` method. When the node is manually edited to insert the trailing `3` (as in attached video), the new argument is interpreted as an unexpected extra argument to `take`. The emitted error is not really helping to understand what happened.

In order to fix this, a decision is needed what we want to do about nested placeholders for non-parenthesized constructors:
1. We can drop them. The expression `operator2.take Index_Sub_Range.First` would not show the `count` placeholder. It would show up for `operator2.take (Index_Sub_Range.First)` inside parentheses.
2. We can keep them visually as is, but handle connection to that argument by wrapping the nested expression with parentheses. That would mean rewriting `operator2.take Index_Sub_Range.First` to `operator2.take (Index_Sub_Range.First number1)`
3. Additionaly to 2, we can visually wrap the expression with parentheses, even if those are not present in actual code.

![An edge about to be connected to `count` argument](https://user-images.githubusercontent.com/919491/225127565-f379ed41-f479-4e5d-83e3-50d47069f53a.png)

**Comment by farmaazon** [comment]
For me, the solution 1 looks most natural. @wdanilo what do you think?

**Comment by farmaazon** [comment]
@wdanilo bump.

**Comment by farmaazon** [comment]
@wdanilo bump

**Comment by wdanilo** [comment]
@farmaazon sorry for missing this somehow.

Regarding visual part, we should do it as in the new design - by placing vertical lines between arguments:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/1623053/235959299-bfe6f098-5edf-4da3-ad3e-bd663e4cdc67.png">

These vertical lines are needed for yet another issue (I don't remember now which one), but basically, if we have nested widgets now, we should progress towards the new design ASAP, otherwise we have a strange state of GUI where some things look nice, where some others look like a code for a programmer.

Under the hood, the solution 2 should be implemented. We don't know whether the code is generated by us or written by the user, so connecting argument to a function argument, should produce parentheses in the code.

**Comment by farmaazon** [comment]
Created https://github.com/enso-org/enso/issues/6776 which, along with the new design implemented, should cover the entire solution above.

Closing this as fixed by https://github.com/enso-org/enso/pull/5705
