### ISSUE TITLE
Text.to_display_text returns `Text`

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#5971]
Especially when handling exceptions it is important to have proper implementation of `to_display_text` (which is invoked from `PanicException.getMessage()`. However Text! has some wrong implementation. Try:

```
main = IO.println "Ahoj".to_display_text
```

and it prints `Text`. That's wrong. I should print `Ahoj`.

**Comment by JaroslavTulach** [comment]
Proposed fix:
```diff
diff --git engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java
index e0bed6343..589f9f49a 100644
--- engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java
+++ engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java
@@ -31,6 +31,11 @@ public abstract class AnyToDisplayTextNode extends Node {
       throw new IllegalStateException(e);
     }
   }
+  
+  @Specialization
+  Text identity(Text self) {
+    return self;
+  }
```

**Comment by radeusgd** [comment]
I think there was some story here.

I remember `to_display_text` was being added because `to_text` would sometimes return too big payloads and overwhelm the IDE. After all the default Text visualization is planned to be Lazy to handle big texts.

If we do _just_ identity here, stuff like error messages which want to display this text can get huge (for example if my Text is a contents of a whole book).

So I suggest that maybe we should truncate the returned Text at some character limit? (though if we do so we need to be careful to not cut the text between two codepoints belonging to a single grapheme cluster - so some slight care will need to be taken to correctly find a Break between proper Characters (`BreakIterator.getCharacterInstance` should be our friend)

**Comment by JaroslavTulach** [comment]
Related pull requests, issues and discussions:
- going with [to_display_text instead of to_pretty_text](https://discord.com/channels/401396655599124480/570967533985988629/813363607928438784)
- #1498
- [it's just a type name](https://discord.com/channels/401396655599124480/570967533985988629/813425308522905660) most of the time...
- #4009
- [shorten very much](https://discord.com/channels/401396655599124480/1044586488823808101/1044888887446753331) and **generate labels that would fit on a node**. 
- #4076 


CCing @4e6, @kustosz, @hubertp. Also related:
- #1538
- #5961

**Comment by jdunkerley** [comment]
Agree with Radek's comment on truncating the text - maybe first 80 grapheme clusters. 
Otherwise @JaroslavTulach's fix looks like the right one.
