### ISSUE TITLE
Visualizations are getting blank when uploading a file to the workflow

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5991]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When uploading a file the visualizations on already existing nodes are getting blank. Please, see the video.

### Expected behaviour

Existing open visualizations should not blink (update), and definitely should not go blank.

### Screenshots or screencasts

https://user-images.githubusercontent.com/12892578/225928835-acb6cda3-5ab2-44f4-abe6-fe1752b87122.mov

### Enso Version

126a4668720141e235aaa54c6dad41a10a82ac60

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

Standalone

### Operating System

MacOS

**Comment by vitvakatu** [comment]
Can reproduce, bisecting now.

**Comment by vitvakatu** [comment]
The issue seems to be caused by commit `7a40ccc3ea02321a6e699c0d4cd2bb187f5d9de2` (#5906)
Assigning to @MichaelMauderer
cc @farmaazon

**Comment by wdanilo** [comment]
> The issue seems to be caused by commit `7a40ccc3ea02321a6e699c0d4cd2bb187f5d9de2` (#5906)
> Assigning to @MichaelMauderer
> cc @farmaazon

I'm wondering how on earth that PR could influence it. Seems not connected at all to me and seems like a random ordering issue. I might be wrong though.

**Comment by MichaelMauderer** [comment]
Maybe some layout recalculation issue? This PR introduces a new use of `client_x/client_y`. That could then lead to some unspecified orderings to change.

**Comment by wdanilo** [comment]
Oh, so do you think this is related to HTML dom elements ordering? Might be! But this is wild. When you'd know what it is, please tell me, as I'm dying out of curiosity!

**Comment by MichaelMauderer** [comment]
We are putting this on hold for the moment to prioritize other tasks. Some notes from the current investigation: 

How to reliably reproduce:
* Create a new node with a table visualization.
* Make sure at least two table visualizations are open/visible in the window (at least one of them on the node that was created in this session).
* Drop a file into the scene to create a new node.
Result:
* The visualization(s) on the nodes that were created in this session will be blank. 
* The following error will be in the debug log (different IDs of course)


```
index.js:10 [ERROR] app/gui/src/model/execution_context/plain.rs:246 Failed to dispatch update to visualization c1a53e84-0329-499b-bac8-8d6f5b1d9864. Failed to found such visualization.
```

```
index.js:10 [ERROR] app/gui/src/model/project/synchronized.rs:417 Failed to handle the visualization update: Tried to use incorrect visualization Id: c1a53e84-0329-499b-bac8-8d6f5b1d9864.
```

This above reproduction can be stopped from happening by removing the calls to `client_x`/`client_y` in `lib/rust/ensogl/component/drop-manager/src/lib.rs:181`, but this is not the root cause. 

The error can also sometimes happen when removing a node, as opposed to dropping one.

When removing the calls to `client_x`/`client_y` in the above location, the bug can still be reproduced if a large number of visualizations is open. More than 10 on my machine reliable reproduce the issue. 

Next steps:
* Investigate the error message.
* Investigate the handling of visualization IDs.
* Investigate the message passed between engine<->controller<->visualizations.

**Comment by sylwiabr** [comment]
Can not reproduce after fixes from @farmaazon
