### ISSUE TITLE
109s vs. 13s when parsing a large column in IDE versus CLI

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6018]
In the demo with Werner, we had a significant performance issue. Having tuned it up the CLI is now much closer to expected speed. However, when running within the IDE it is much slower.

The process was just parsing a date. I have reproduced with a test workflow parsing 500k date strings.

The GUI takes 109s to execute versus 13s for CLI.

Test workflow:
[Parse_Performance.zip](https://github.com/enso-org/enso/files/11019996/Parse_Performance.zip)

**Comment by 4e6** [comment]
Profiling [language-server.npss.zip](https://github.com/enso-org/enso/files/11049720/language-server.npss.zip) showed that most of the time spent in `parseColumn` method, and more specifically in `fillInStackTrace` methods of exceptions.

![2023-03-23-132551_2143x645_scrot](https://user-images.githubusercontent.com/357683/227175631-292dd437-170d-4414-ae72-81f9771d0a38.png)

![2023-03-23-133409_2143x582_scrot](https://user-images.githubusercontent.com/357683/227177118-3fafb151-5c02-4354-82d7-9ad47fbcdb63.png)

**Comment by 4e6** [comment]
Profiling in text mode [language-server.npss.zip](https://github.com/enso-org/enso/files/11050007/language-server.npss.zip) showed that `parseColumn` method is twice as fast because the stack traces are not filled in.

![2023-03-23-140624_2144x624_scrot](https://user-images.githubusercontent.com/357683/227185567-e5efcbc2-a5c3-445a-a4dc-310e35213d3c.png)

**Comment by 4e6** [comment]
Thanks to @Akirathan for the help. He noticed that in both cases the stack traces are filled, but it takes less time in the text mode. I assume it can be because of the deeper stack in the interactive mode.

The fix would be to rewrite the `DateTimeParser` without using the `parseBest` method that causes the issue.
https://github.com/enso-org/enso/blob/0bdf44cba8aec366154a296e30e1730a0ef45a04/std-bits/table/src/main/java/org/enso/table/parsing/DateTimeParser.java#L20-L26

**Comment by jdunkerley** [comment]
OK thanks @4e6 

I will take this over then and redo that bit. We will need to bear in mind that any Java method which uses exceptions as control flow should be avoid in any function which might be mapped over.

**Comment by Akirathan** [comment]
> We will need to bear in mind that any Java method which uses exceptions as control flow should be avoid in any function which might be mapped over.

That is definitely a good idea. In this case, it is even more hidden, since `parseBest` method uses the exceptions internally.
![image](https://user-images.githubusercontent.com/14013887/227261327-d92b7646-2839-464b-96ef-70d26e2a003e.png)
Line 1999 is very hot, thus, a lot of exceptions are created internally.

**Comment by radeusgd** [comment]
Of course it is good to avoid exceptions for control flow and we should definitely do that.

We will still be getting exceptions from time to time, and cannot easily control how some internals of libraries are implemented.

Can we do something about this `fillInStacktrace` being so slow? Ofc, it is kind of inherently slow. But I understand that in the GUI it is significantly slower than in CLI, so in CLI it is not _that_ bad. Do you think there is anything that we could do to decrease this slowdown, to get the GUI performance to match CLI?

One idea I had, can we set `MaxJavaStackTraceDepth` in our release mode to some not-too-big value, to limit the stack trace size? Of course in debug mode we want full stack traces, but for production maybe keeping just last ~40-100 frames could be enough and maybe it could improve our performance in places that are still throwing?

I could not find any good docs for `MaxJavaStackTraceDepth`, but it seems that it is an option that is supported - there were even some [bugfixes related to it](https://bugs.openjdk.org/browse/JDK-7179701).

**Comment by radeusgd** [comment]
Looking at the [OpenJDK sources](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/classfile/javaClasses.cpp#L2476-L2525), it seems that setting `MaxJavaStackTraceDepth` _does limit_ the size of stack traces attached to exceptions (it is not merely a display setting).

Not sure if GraalVM does the same, would need to double check.

**Comment by Akirathan** [comment]
> Can we do something about this fillInStacktrace being so slow? 

Not really. It is a native JVM function, by limiting the size of the stack you don't solve the problem entirely - the JVM still needs to do some safe point bookkeeping in order to switch to a native function. Avoiding exceptions as much as possible is the best, and easiest fix.

I understand that we cannot reimplement JDK libs, but avoiding suspicious and expensive JDK lib methods should not be that difficult.

**Comment by radeusgd** [comment]
> > Can we do something about this fillInStacktrace being so slow?
> 
> Not really. It is a native JVM function, by limiting the size of the stack you don't solve the problem entirely - the JVM still needs to do some safe point bookkeeping in order to switch to a native function. Avoiding exceptions as much as possible is the best, and easiest fix.

That's why I'm not proposing this as the only fix - I agree that first and foremost we should avoid exceptions in control flow. We will still take a perf. hit in scenarios when an exception is thrown - and so I'm wondering if `MaxJavaStackTraceDepth` could help us alleviate that performance hit at least a bit.
