### ISSUE TITLE
Component Browser Icons are not on an external screen with different zoom level in Windows 11 Pro

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6125]
Icons are visible on the laptop main screen but on the external screen they are just squares.

![image](https://user-images.githubusercontent.com/4699705/228513309-61726c56-24de-4ac4-987b-2ce409c65a8a.png)

Main screen at 150%, external at 175%.

**Comment by wdanilo** [comment]
Does it happen when you drag the window there or it also happens when you open application from start on that screen?

**Comment by jdunkerley** [comment]
> Does it happen when you drag the window there or it also happens when you open application from start on that screen?

Happens when you drag to it and reappears when dragged back. 

Will try and configure so open on it (have lost access to specific monitor).

**Comment by kazcw** [comment]
I can reproduce this, on Windows and also Linux. I think I remember seeing that we are doing something unusual with the alpha channel for cached shapes... Looking in to it.

**Comment by farmaazon** [comment]
> I can reproduce this, on Windows and also Linux. I think I remember seeing that we are doing something unusual with the alpha channel for cached shapes... Looking in to it.

Yes, the alpha channel of cached shapes is ignored (we replace it with SDF).

However, the cause is a bit different: we scale up the size of cached shapes' texture, so when rendering shapes from the texture will match the device pixels, not the logical ones. But when the scaling changes, we don't update the texture, but  seemingly still use the new scaling for getting the shapes location, what makes us taking some random parts of the texture.

**Comment by wdanilo** [comment]
@farmaazon would it be hard to re-cache textures when DPI changes?

**Comment by farmaazon** [comment]
> @farmaazon would it be hard to re-cache textures when DPI changes?

I think it is not.
