### ISSUE TITLE
Shape order gets lost when moving a component to a different layer. 

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#6241]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When moving the `DropDownMenu` to the `panel` layer for use in the top menu, the order of its component shapes (`arrow` and `chooser_hover_area`) seems to become unspecified. On some systems, then they are ordered in the wrong way. 

### Expected behaviour

The shape order defined between the shapes via `above`/`below` attributes in the shape definition should be preserved. 

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
@MichaelMauderer could you create a repro demo scene, or that would not be possible?

**Comment by kazcw** [comment]
I'll look at this because I'm currently reorganizing how we use layers quite a bit, so I'm likely to be affected by the same problem

**Comment by MichaelMauderer** [comment]
> @MichaelMauderer could you create a repro demo scene, or that would not be possible?

I can try. But when this came up yesterday, I was unable to repro this, and it only appeared on @Procrat 's machine.

**Comment by vitvakatu** [comment]
I was reporting a similar issue a long time ago, it contains technical details: https://discord.com/channels/401396655599124480/1041664588334235741/1041664588334235741 
I don't know if it was fixed since then or not.

<blockquote><img src="undefined//discord.com/assets/652f40427e1f5186ad54836074898279.png" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/channels/401396655599124480/1041664588334235741/1041664588334235741">Discord - A New Way to Chat with Friends & Communities</a></strong></div><div>Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.</div></blockquote>
