### ISSUE TITLE
Allow users to give a project other than Upper_Snake_Case name.

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6356]
### How important is this feature to you?

2 – Somewhat important, but I can live without it

### Describe the idea you'd like to see implemented.

Right now user can name the project just using upper snake case (`My_Project_1`). Other ways should be also supported by the engine as well - `My Project 1` or `my project 1` or `MyProject1`

### Would you be willing to help us implement this feature?

No

**Comment by mwu-tow** [comment]
IIRC this was because the project name was required to be a valid Enso identifier, as we wanted to be able to refer to the project in the code. So this might involve some language design input.

**Comment by sylwiabr** [comment]
That is true. From the user perspective however, it's very annoying if you are limited to upper snake case unfortunately and very surprising.

**Comment by somebody1234** [comment]
i definitely think this it's a good idea to allow e.g. spaces, *somehow* - i feel like requiring `Title_Snake_Case` (?) makes it feel less approachable. i believe there's code somewhere to automatically convert project names to `Title_Snake_Case`, so *maybe* it could just be converted to the allowed name on the fly.

(just my two cents - this should definitely be discussed by whoever does language design)

i guess an analogy may be cloud asset names - because it's meant be more like a filesystem, all assets allow most names (if not any name) - projects included, so *maybe* there could be different limitations for the *file name* and the *variable name*?

**Comment by farmaazon** [comment]
@sylwiabr Does it have to be for Beta Release? It requires some discussion and work on both Project Manager and IDE, the former may be very non-trivial. We have several other big tasks planned for beta release

**Comment by wdanilo** [comment]
I was chatting about it with Sylwia. If we want to do it (I don't feel it is really a breaking deal, but Sylwia and @jdunkerley feel otherwise, probably correctly, as users would like to name the projects as they want), then we should basically then allow for arbitrary name and generate proper Enso module name from that name by mangling it. This way we can still use the names of the projects in Enso modules while allowing arbitrary user-displayed project names. What do you think of this solution?

**Comment by farmaazon** [comment]
> I was chatting about it with Sylwia. If we want to do it (I don't feel it is really a breaking deal, but Sylwia and @jdunkerley feel otherwise, probably correctly, as users would like to name the projects as they want), then we should basically then allow for arbitrary name and generate proper Enso module name from that name by mangling it. This way we can still use the names of the projects in Enso modules while allowing arbitrary user-displayed project names. What do you think of this solution?

Yes, I also thought something about that, but I wasn't sure what if we have one project named `A_Project`, and then the user want to rename another to `A Project` - I guess we should display message about duplicated name, however it may be unintuitive, as the names are actually different, only they identifier is different.

**Comment by wdanilo** [comment]
But we allow multiple projects to have the same module names, right? Until they are imported as libraries ... but then you'd need to register your library and then you can get an error that library with that name is already registered. Until then, I think ti should work, right? Please correct me if I don't see something here!

**Comment by farmaazon** [comment]
> Until they are imported as libraries ... but then you'd need to register your library and then you can get an error that library with that name is already registered. Until then, I think ti should work, right? Please correct me if I don't see something here!

Well, I didn't know I need to register library somewhere to use it in my projects. I expected that having my project locally, I can just use it in another project (like in cargo).

**Comment by wdanilo** [comment]
> > Until they are imported as libraries ... but then you'd need to register your library and then you can get an error that library with that name is already registered. Until then, I think ti should work, right? Please correct me if I don't see something here!
> 
> Well, I didn't know I need to register library somewhere to use it in my projects. I expected that having my project locally, I can just use it in another project (like in cargo).

Ok, this is interesting approach indeed. TBH I was not thinking about using it this way, but it makes sense and it would be cool to allow to use other projects without registering them. We need to think how to marry this idea with projects kept in the cloud (as this is our main product). There the situation is way more complex, as projects are stored in arbitrary folders, somewhere in S3 and not all users have access to all projects.

**Comment by hubertp** [comment]
Related https://github.com/enso-org/enso/issues/5065

**Comment by hubertp** [comment]
Also, remember that users can have weird project name like ":smile: My Project :smiley_cat: ".

**Comment by JaroslavTulach** [comment]
I've noticed last week that the new dashboard prevents other than `Snake_Case` project names:

![Non_Snake_Case_Warning](https://github.com/enso-org/enso/assets/26887752/ad24edb1-79f2-4cbf-9cce-9d5cca7df990)

Are we consistent about the _near term_ solution and _long term_ plans? Right now we have:
- `project-manager` - disallows non-`Snake_Case` project names
- _dashboard_ - disallows non-`Snake_Case` project names
- _IDE_ - allows any name, but fails when calling to `project-manager`

Probably we need to fix all these parts and make them consistent. +CCing @PabloBuchu.

**Comment by somebody1234** [comment]
@JaroslavTulach currently this is intentional. note that this validation only happens when using the local backend (i.e. the project manager backend) - so the plans are 100% to remove the validation when this restriction is lifted from the PM.

validation has mostly been added:
- to save on calls to the backend(s)
  - for the remote (cloud) backend, this also means there's no latency especially if you're very far away from the cloud VMs
- for (ideally) better error messages. not sure how good/bad the PM's error messages are, but the ones the cloud backend gives on invalid input aren't that great
