### ISSUE TITLE
Some operators are not recognized as operators.

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6367]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Operators like `<=`, `>=` are not behaving correctly in IDE as you ca see on the screencast. Thea are added to the nodes as methods. After editing the node to have expression like `a <= b` they don't have input ports working.

https://user-images.githubusercontent.com/12892578/233360249-cd192ebe-25fb-4e8a-aed3-7d87c39a88ec.mov

### Expected behaviour

`<=` should behave like `<` in IDE

### Enso Version

Nightly 20.04.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
It's not about operators with more than one character, because `|>` works perfectly.

It's something about some operators being actually lambdas in some context, so they are not parsed as operators:
https://discord.com/channels/401396655599124480/1087383311363604500/1088842646144950373

It should be fixed somehow in the parser.

<blockquote><img src="undefined//discord.com/assets/652f40427e1f5186ad54836074898279.png" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/channels/401396655599124480/1087383311363604500/1088842646144950373">Discord - A New Way to Chat with Friends & Communities</a></strong></div><div>Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.</div></blockquote>

**Comment by kazcw** [comment]
> It's not about operators with more than one character, because `|>` works perfectly.
> 
> It's something about some operators being actually lambdas in some context, so they are not parsed as operators: https://discord.com/channels/401396655599124480/1087383311363604500/1088842646144950373
> 
> It should be fixed somehow in the parser.
> 
> > <img alt="" width="48" src="undefined//discord.com/assets/652f40427e1f5186ad54836074898279.png"><img alt="" height="14" src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico"> Discord**[Discord - A New Way to Chat with Friends & Communities](https://discord.com/channels/401396655599124480/1087383311363604500/1088842646144950373)**Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.

I don't see how `<=number1` being a lambda is wrong, or related to this. Any ordinary operator would create a lambda in that position.

<blockquote><img src="undefined//discord.com/assets/652f40427e1f5186ad54836074898279.png" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/channels/401396655599124480/1087383311363604500/1088842646144950373">Discord - A New Way to Chat with Friends & Communities</a></strong></div><div>Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.</div></blockquote>

**Comment by wdanilo** [comment]
Kaz is right. Both `a <` and `a <=` are curried functions, so they are lambdas. However, somehow `a <` works in GUI while `a <=` does not. 

Another issue here is that when we create `a <` in GUI, the res arg is not displayed while it should be. Is this connected issue? Nevertheless if its connected or not, can we fix it?

**Comment by kazcw** [comment]
`<=` is being interpreted as a modifier at the `Ast` level, fixing that now.

**Comment by kazcw** [comment]
> Another issue here is that when we create `a <` in GUI, the res arg is not displayed while it should be. Is this connected issue? Nevertheless if its connected or not, can we fix it?

Hm. An expected-argument placeholder would make sense for a `a <` node, because that node is likely to be incomplete; but the syntax is also a valid operator section. Should all operator sections show placeholders for their implicit arguments? If not, maybe we could use a heuristic to show placeholders for some incomplete-binops and not others?

**Comment by kazcw** [comment]
> > Another issue here is that when we create `a <` in GUI, the res arg is not displayed while it should be. Is this connected issue? Nevertheless if its connected or not, can we fix it?
> 
> Hm. An expected-argument placeholder would make sense for a `a <` node, because that node is likely to be incomplete; but the syntax is also a valid operator section. Should all operator sections show placeholders for their implicit arguments? If not, maybe we could use a heuristic to show placeholders for some incomplete-binops and not others?

Conclusion from call: We should show expected arguments for partially-applied operators in the same conditions that we would do so for partially-applied methods, i.e. when not inside a lambda
