### ISSUE TITLE
Node arguments are not getting formatting (color and font) after editing a node

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6519]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I press Ctrl+click on a node and then cancel the edit, the node is not getting back the arguments formatting it previously had.

https://user-images.githubusercontent.com/108271897/235872996-c23ecba5-281c-4183-ba8c-daedba891c5f.mp4

### Expected behaviour

node gets back to the formatting it had prior the edit

### How we can reproduce it?

ctrl click the node
cancel the node edit
observe it's colorless ugly existence

### Enso Version

2023.5.2 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by vitvakatu** [comment]
Estimated as 1 point for initial investigation (can be an engine issue)

**Comment by MichaelMauderer** [comment]
I did have a look at this while investigating #6561, since they are adjacent issues. The problem here is on the IDE side. This is what happens:
* we evaluate the node for preview while editing
* during editing, we do not apply colouring 
* we end editing and do not re-evaluate the node (as it is already evaluated)
And it seems there is currently no process to update the colouring outside of type updates which we get from the engine, no colouring is applied.

The solution will be to either re-evaluate the node to trigger a full update, or try to get the colouring information that should already be present from the preview evaluation and apply it after editing has ended.

**Comment by farmaazon** [comment]
> The solution will be to either re-evaluate the node to trigger a full update, or try to get the colouring information that should already be present from the preview evaluation and apply it after editing has ended.

The latter is a proper fix.

**Comment by MichaelMauderer** [comment]
> > The solution will be to either re-evaluate the node to trigger a full update, or try to get the colouring information that should already be present from the preview evaluation and apply it after editing has ended.
> 
> The latter is a proper fix.

I agree.

**Comment by farmaazon** [comment]
Closing, as nodes are no longer colored according to type information.
