### ISSUE TITLE
Source Map Loading Timeout Warnings in Console When Creating a New Project

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#6559]
Open IDE, and create a new project. The following warning appears in the DevTools console:
```
DevTools failed to load source map: Could not load content for http://localhost:8080/preload.cjs.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for http://localhost:8080/pkg.js.map: Load canceled due to load timeout
```

There should be no warning.

**Comment by wdanilo** [comment]
@somebody1234 we are not shipping source maps with the app. We probably should. Could you take a look how to do it, please?

**Comment by somebody1234** [comment]
`asar l /tmp/.mount_enso-random-string-here/resources/app.asar` indicates that these files exist:
```sh
/assets/* # elided because they are not relevant
/tasks/computeHashes.cjs
/ensogl-app/index.js
/ensogl-app/index.js.map
/assets/dynamic-assets.js
/assets/dynamic-assets.js.map
/assets/fonts.js
/assets/fonts.js.map
/assets/index.js
/assets/index.js.map
/assets/pkg.js
/assets/run.js
/assets/run.js.map
/index.cjs
/index.cjs.map
/preload.cjs
/preload.cjs.map
```
initial observations:
- `pkg.js` doesn't have a source map?! i might have forgotten to copy it across? will look into it later, just posting this as a status update
- not sure how it's even loading `preload.cjs`. afaict, the builtin server *only* serves from `assets`, which `preload.cjs` doesn't seem to appear in... but i guess Electron loads that itself.
  - not sure why electron is trying to load `preload.cjs.map` then, so i'll just switch sourcemaps to inline
- as for `pkg.js`, i specialcased it. it doesn't seem like it's possible to get sourcemap generation to work, *and* keep `pkg.js` as CJS...
  - actually we do generate it because we pass `--sourcemap`. so maybe the issue is that it's excluded from `ENSO_BUILD_GUI_WASM_ARTIFACTS`
  
 and indeed we see that `index.js.map` is explicitly added but not `pkg.js.map`.

**Comment by somebody1234** [comment]
ok so this comment is mostly outdated but i'd figure i'd keep it here for posterity
