### ISSUE TITLE
Clearly report type errors on API boundary

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6682]
Currently Enso is using _"duck typing"_ - e.g. one can invoke a function with any argument and if such argument has the right methods, fields, etc. as expected, the execution goes on. Such a behavior is causing issues in the IDE - when a wrong node is connected as an argument (a `Text` instead of `Number` for example), the execution isn't rejected immediately, but proceeds until the _"duck typing"_ fails. However that is often late, deeply in the standard libraries internals and produces _hard to understand errors_. It'd be way better if the _typing error_ was caught right on the **API boundary**.

```
type Num
    All a
    Value (x : Num)
```

Let's use the _ascribed types_ for real type checks. With the above type definition, the following would execute OK: `Num.All "ok"`, but invoking `Num.Value "error"` would rise a `Type_Error`. Similarly with a

```
check (n : Num) = n
```

Invoking `check "error"` shall yield an error while `check (Num.All "ok")` shall be fine. There is a [proof of concept branch](https://github.com/enso-org/enso/compare/wip/jtulach/AscribedTypes_6682) demonstrating it can all work.

**Comment by radeusgd** [comment]
How do we plan to check conditions like
```
foo (v : Vector Integer) = v.take 5

...

foo [1,2,3]
foo [1,2,"X"]
foo []
```

**Comment by radeusgd** [comment]
I guess one way to do it would be to just ignore the 'type argument' and check `is_a Vector` as this is what we can do - I'm however afraid the halfway typecheck may give the users a bit of false sense of security - but if it's the best we can do quickly I guess it's good, we just need to make sure users know about our 'erasure'.

Probably in library code we'd need to then ensure that we verify the type once read from the vector, like:
```
foo (vec : Vector Integer) =
    x : Integer = vec.first
    y : Integer = vec.second
    x + y
```

Still, it is a bit harder now to track the error, because the true error happens when calling `foo` with a wrong vector, but it may be caught much later (in the example above its just a line below, but in practice it may be much further apart).

However, again - I think this solution will still improve most use cases so greatly that it is of course worth doing even if it will not (yet) be perfect in the more complex errors.

**Comment by JaroslavTulach** [comment]
> I think this solution will still improve most use cases so greatly that it is of course worth doing even if it will not (yet) be perfect in the more complex errors.

Implementing the "erasure" style is a matter of a week. Then the Enso type system can be _on par with Java 1.4_ (_before_ the introduction of _generics_).

Implementing `Vector Integer` (or rather `MyType Integer`) is a more complex change. Making `foo append(x: List a) (y : a) : List` is even slightly more work.

**Comment by JaroslavTulach** [comment]
However recording type at the creation may give us _"incomplete type"_:
```
type Either a b
    Left l : a
    Right r : b
```
probably `foo (e : Either Text Integer)` and `boo (e : Either Boolean Integer)` could both be invoked with `Either.Right 5`!

Thinking about it more, I think this leads to [Julia-like type system](https://docs.julialang.org/en/v1/manual/types/):
- Only values ... have types
- Type parameters may be omitted when they do not need to be referenced or restricted
- attach type annotations to expressions and variables... as an assertion
- `Point` itself is also a valid type object, containing all instances `Point{Float64}`, `Point{AbstractString}`, etc. as subtypes
- Concrete `Point` types with different values of `T` are never subtypes of each other
- `Point{Float64}` is not a subtype of `Point{Real}`
