### ISSUE TITLE
IDE died when editing the node such that no more evaluation was happening

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6727]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/ba3ec145-24ce-4682-aecb-f32b1845b7da

### Expected behaviour

IDE should keep working and getting the values from the engine

### Enso Version

Nightly 17.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by Akirathan** [comment]
The `[warn] Visualisation evaluation failed: ...` message from the Engine is not unusual - it happens, for example, when you are creating a new node, the visualization preview is opened, and you start typing some non-existing value. Engine/LS should not die because of failed visualization evaluation, at least that is not happening in my case. 

This issue seems like an instance of the "IDE and LS getting out of sync" family of issues. Related to #6701. Without the full verbose logs from the LS, there is not much we can see from this. At least we have another visual clue.

**Comment by Akirathan** [comment]
We still don't know the root cause of these *desynchronizations* between IDE and Engine, as noted in https://github.com/enso-org/enso/issues/6701#issuecomment-1554781071

**Comment by Frizi** [comment]
The issues caused by desynchronization are likely to be somewhat improved on IDE side by https://github.com/enso-org/enso/pull/6752, but the root cause of it still need to be understood and adressed.

**Comment by JaroslavTulach** [comment]
- #6752 has just been integrated.
- #6775 is a way to improve understanding of what happens _"in the field"_ when people use Enso on their computers

Not much more can be done to resolve this issue, I am afraid.
