### ISSUE TITLE
Node with randomly added by CB `Column.from_vector` to `select_nodes` renders weirdly and behaves like a part of a vector editor

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6760]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When CB added `Column.from_vector` to `select_columns ["id"]` node it started behave weirdly (like it was a part of a vector) and had problems with rendering.

### Expected behaviour

`Column.from_vector` should not be part of a widget.

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/8b996367-261e-43f6-a8e0-39a1d0a4c64b

### Enso Version

nightly 18.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by Frizi** [comment]
Part of this issue is related to the list editor being used on a syntax tree that it didn't expect, and part is about the component browser doing a weird thing.

## Unintuitive component browser behavior.

When I have a node with expression:
```
operator3.select_columns ["id"]
```

Then I enter its edit mode, the cursor is placed at its end and the component browser shows some suggestions. I select one with `Column.from_vector`, which modifies the node code to the following:
```
operator3.select_columns ["id"]Column.from_vector
```

Note a lack of space. I guess the component browser doesn't want to assume any specific context that the user wants to enter the suggestion into. But in this case it leads to a weird situation, where that whole expression `["id"]Column.from_vector` is treated as a first argument to `select_columns`.

I don't know what we would expect to be there, but I would like to treat this as a separate issue anyway, and focus on widgets here.

## List editor being chosen incorrectly.

The method `select_columns` expects its first argument to be a list of column names, which is of type `Vector Text`. Now because the expected array syntax doesn't match exactly (e.g. the expression doesn't end with `]`), that widget would not be used by default. But in this case, it is explicitly overriden in the library to be of type `ListWidget`, therefore it is applied anyway. The list editor then treats all loose parts of `["id"]Column.from_vector` as elements of a list, allowing them to be reordered by mouse drag.

I'm going to modify the widget choice logic such that the overriden widgets are only applied when the current expression syntax tree is suitable for them. That would mean that annotations are more of a widget suggestions used when everything lines up as expected, but can be ignored in other cases.
