### ISSUE TITLE
Icon for enabling/disabling output context, when toggled on, should stay visible even if not hovered.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#6791]
It should, according to the design.

**Comment by MichaelMauderer** [comment]
Do you have a link to the design of the described behaviour? Just to make sure, I can double-check requirements and affected items.

**Comment by farmaazon** [comment]
Now, I haven't found the exact description. The screenshots I've seen are from the new design of nodes, where icons are in a different place.

Currently, we could make this icon just not fade-out (and maybe move it closer to the node) @wdanilo is that ok?

**Comment by MichaelMauderer** [comment]
Currently, the behaviour of the output context toggle icon (the one to the right of the node, placed right of the visualization visibility toggle), is linked to the visualization visibility toggle icon, too. That is, they are animated and placed as an icon group. 

So, I assume this means also that the output context toggle icon should be moved to the left of the visualization visibility toggle icon. Otherwise, there is a gap between the icon and node.

**Comment by wdanilo** [comment]
So, how the icon will be handled now does not make much difference, as we need to nevertheless layout and manage icons differently soon. Actually, we might implement the new design right away in this task if you are changing how icons are managed, how about that? The new design is here:

<img width="506" alt="image" src="https://github.com/enso-org/enso/assets/1623053/bcf05f4a-b809-42cd-b774-4a1b0bf85923">


And yes, the icon does not disappear when toggled on.

**Comment by AdRiley** [comment]
This is now covered by issue https://github.com/enso-org/enso/issues/9164 which is more up to date with the lastest gui2 design
