### ISSUE TITLE
Handle some edge cases in rounding (inexact representations and overflows)

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#6811]
Handle the following edge caess:

* `1.225 . round 2 use_bankers=True`
Fails because the intermediate value is 122.5000000001, not 122.5, so it rounds to 3
Solution: Instead of add-0.5-and-floor, we compare with the midpoint value, which will *also* be off by the same amount
Notes
I accidentally found this, but it’s a well-known problem
https://realpython.com/python-rounding/
https://stackoverflow.com/questions/15762768/javascript-math-round-to-two-decimal-places
https://stackoverflow.com/questions/6930786/how-does-excel-successfully-round-floating-point-numbers-even-though-they-are-im

* Long values > 15 digits
Longs have 19 digits of precision, while doubles have 15; converting to double loses precision
Solution: don’t convert to double, do everything in integer space

* Doubles rounded outside their range
Solution: throw exception

**Comment by wdanilo** [comment]
@GregoryTravis all GitHub issues should be understandable by the reader after reading the text on GitHub. Here, after reading the title and its description I do not understand it. The title alone should also be more explanatory - after reading the title, the reader should more or less understand what the issue is about. The reader could also be someone from outside our organization, not having access to the Google Docs that you attach (not to mention that even I don't have access to them right now).

**Comment by GregoryTravis** [comment]
Done.

**Comment by wdanilo** [comment]
Thanks a lot ❤️
