### ISSUE TITLE
Simpler fuzzy matching

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7046]
The matching algorithm in searcher should be modified, so it will accept less entries than now. See https://github.com/enso-org/enso/issues/7046#issuecomment-1610173369 for details.

**Comment by wdanilo** [comment]
Hmm, why `bar_foo` should not be matched? `foo` is a valid beginning of a word there. If I have a function `to_string`, I want it to be found when writing `string` I think.

**Comment by farmaazon** [comment]
> Hmm, why `bar_foo` should not be matched? `foo` is a valid beginning of a word there. If I have a function `to_string`, I want it to be found when writing `string` I think.

In some meeting's notes I have an info we want to show greyed-out remainder of the text when selected suggestion. How could it work with patterns starting in the middle of the code?

**Comment by wdanilo** [comment]
Regarding your question, @farmaazon, I think we will not show this greyed out thing at all. No fuzzy searcher does it, probably exactly because of this reason.

## Fuzzy matching rules

So, to sum up the design:

1. All hints to the fuzzy matching should be provided in the Enso syntax form, e.g. `data.read_file` (I'm using lowercase here as we are changing the casing in Enso to lowercase, but upper-case might appear for now in this list, but fuzzy matching should be case-insensitive). These things will be displayed in the component browser in a nicer way, e.g. `data read file`. 
2. When user types `.` or `_` it should match the dot or underscore as is. However, any non-zero repetition of space should match both dot and underscore.
3. User input should be interpreted as any sequence of word prefixes, where by "word" we understand entries split by `.` and `_` and the first number in a number sequence. For example, to match `data.read_file21`, the words are "data", "read", "file", and "21", and thus user can type `darefi21`, but not `daredfi21`, as "red" is not a prefix of any of the words. However, user can also type `data.re`. 
4. A pretty important thing here though is that when typing dot explicitly, fuzzy matching should not work. So typing `da.re` should not match `data.read`. Explicit dots should be interpreted literally, always. 
5. Explicit underscores, on the other hand, should always be interpreted as word beginning. 


## Scoring

We need to work on scoring here as well. This will probably be adjusted on the go, but there are a few rules we know already:

1. Matching an earlier word should give better scoring than later word. For example, for input `dre` should give bigger score for `data read` then for `foo_dre` (like in IntelliJ).
2. However, the point 1 makes it a little bit tricky. The thing is that the part after the last dot is most important. So for example, typing `read` should match `data.read_file` better than `retention.advertising` (The hints will have dots only in case of static methods).
3. No matter what is matched, typing exact next letters of the match should never change a match. This should be somehow "guaranteed" by the algorithm design. For example if the user typed `foo_b` and the best match is `foo_bar`, typing "a" and "r" should never switch to another best match, because "a" and "r" are the exact next letters of the best match. This is important for the UX of the searcher and it is one of the most broken things in MacOS spotlight (typing exact next letters can there change the hint to something else).
4. There should be an easy way to adjust weights by some criteria. For example, we know already that hints in virtual groups should have higher weight (and should be sorted by the group order when user did not type anything yet), or that local variables should have lower weight than static methods and methods, but higher than modules.

**Comment by farmaazon** [comment]
@kazcw James recently created a new, better version of matching algorithm (different from one described in the comment). It can be tested here https://jdunkerley.github.io/enso-react/ We should be implemented this one in IDE. Sorry for confusion.

@jdunkerley please post the code here, so Kaz will easily port it into Enso GUI.



<blockquote><div><strong><a href="https://jdunkerley.github.io/enso-react/">React App</a></strong></div><div>Web site created using create-react-app</div></blockquote>

**Comment by jdunkerley** [comment]
The code is at https://github.com/jdunkerley/enso-react/
Specifically at: https://github.com/jdunkerley/enso-react/blob/main/src/data/Function.ts

I'll summarise the logic and post shortly.

<blockquote><img src="https://opengraph.githubassets.com/57c10b3adc60a7d37703a0d5fd6b787d3794a5134da92e9cecc23fafc6a86177/jdunkerley/enso-react" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/jdunkerley/enso-react">GitHub - jdunkerley/enso-react</a></strong></div><div>Contribute to jdunkerley/enso-react development by creating an account on GitHub.</div></blockquote>

**Comment by jdunkerley** [comment]
Here is the summary of the search:

- Case-insensitive search
- Search either for "word starts with" or "initials starts with". **Does not match contains within words.**
- If not connected to anything, search within static functions and constructors.
- If incoming, then just search within instance methods or extension methods of the type (or parent types).
- Does not include PRIVATE, optionally includes ADVANCED/UNSTABLE.
- Match within either names or aliases. For static methods or constructors, prefix with either the type name or module name if not in a type.
- If search string contains a `.`, then the first part is used to search within the type (or module name). Only relevant for static methods or constructors.
- If the search string contains a `_`, then each part represents a starts with word and must be matched in the same order they occur.

## Examples within Table:

- `col` will match `columns`, `column_count`, `select_columns`.
- `col_` will match `columns`, `column_count`, but not `select_columns` (because no following word after `col`).
- `col_c` will match `column_count`, but not `columns` or `select_columns` (because `col` must be followed by another word starting with `c`).
- `sc` will match `select_columns`, but not `columns` or `column_count` (because `sc` must be at the beginning of a word or initials of word).
- `drop` will match `drop`, `drop_duplicates`, `dropna`.

## Examples within Static:

- `read` will match `Data.read`, `Image.read`, `Data.read_text`, `Environment.get`.
- `rt` will match `Data.read_text`.
- `drt` will match `Data.read_text`.
- `dp` will match `Date.parse`, `Decimal.parse`.
- `dtp` will match `Date_Time.parse`.
- `d.` will match all methods within types starting with `d` (e.g. `Data`, `Date`, `Date_Time`).
- `dt.` will match all methods within types starting with `dt` or with initials `dt` (e.g. `Date_Time`).

**Comment by jdunkerley** [comment]
For ordering the search, the following scoring was used:

- First, based on the type of match:
  - Name starts with
  - Type starts with
  - Alias starts with
  - Name words match but not the first word
  - Alias words match but not the first word
  - Name initials
  - Alias initials
- Then, based on the percentage of the word matched not used (i.e. if looking for `col` the word `column` scores higher than `columns`)
- Then, based on the group ranking
- Final alphabetically on (`Module` or `Type` name and `Method` name)

The typescript implementation of this isn't quite right but is close to what it should be.
