### ISSUE TITLE
Getting the vector editor to start dragging an item is tricky

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7063]
Was trying to use the ability to drag an item out of a Vector. 
Was very hard to get it to pick up the item, once moving worked as expected.
Video attached.

https://github.com/enso-org/enso/assets/4699705/9adceabc-a4f0-4c80-a524-37c548b0ca73

(Newest develop IDE build as of 19th June)

**Comment by wdanilo** [comment]
2 issues:
1. The "drag area" should cover whole node vertically, so there is no space between the edge of the node and the widget which would not allow it for the drag (@Frizi knows about it already and it might already been fixed, to be confirmed).
2. @jdunkerley you were not dragging them vertically, but a little bit horizontally. We have a threshold there choosing which direction the drag was. This is because some widgets allow for horizontal drag, like sliders. We need to distinguish if you wanted to drag the component or change the component. Knowing that, could you please try dragging them more vertically and telling if the issue is still there? We can increase these thresholds, but then it will be harder to change values on sliders.

**Comment by farmaazon** [comment]
> The "drag area" should cover whole node vertically, so there is no space between the edge of the node and the widget which would not allow it for the drag (@Frizi knows about it already and it might already been fixed, to be confirmed).

@Frizi There is an issue #6823, perhaps the first point should be implemented when fixing it. Shall I merge this issue to that one?

**Comment by farmaazon** [comment]
@Frizi bump ^

**Comment by farmaazon** [comment]
No longer relevant in new GUI, where we have handles to drag.
