### ISSUE TITLE
Enso should create projects' directory in correct OS-specific locations 

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7094]
Currently Enso are located in some OS-specific directories. Unfortunately, sometimes those are not the usual locations where one would search for applications data. Need to verify/adjust those for

- Windows - ???
- MacOS - ???
- Linux - Currently: `$HOME/enso/projects`, Desired: Dunny, probably can stay the same

**Comment by mwu-tow** [comment]
The `~/enso/projects` is a OS-dependent location, as `~` is an OS-defined home directory.

> This is hardly a default location where applications should store its data

The location for application data is usually hidden from plain user's view; the rationale for this location was to make projects easily discoverable and accessible through file explorers.

**Comment by hubertp** [comment]
I updated the description a bit. Linux is a free world so not really a problem. This mostly concerns Windows and Mac, as apparently the locations can be surprising (as reported by other users, not me).

**Comment by farmaazon** [comment]
> > Linux is a free world so not really a problem.
>
> Depending on the point of view. Personally, I really don't like apps creating directories in my home directory, or even in any subdirectory.

Neither do I.

> For me, the ideal solution is to allow the user _to choose_ their workspace location.

Yes, ideally, but that's not what we currently have available. 

>> This mostly concerns Windows and Mac, as apparently the locations can be surprising
>
> As @mwu-tow mentioned, we want to have a place easily accessible by the user, so app data directory is not the place.

I think there is a mismatch here between something being "easily accessible" (as in, say as few clicks as possible) and expectations where application's/user's data should reside so as not to appear random. Also consider that some users automatically upload certain directories to the cloud and they would expect certain directories to be synced automatically.

> What could be better? Perhaps "Documents", but I'm not sure, as I'm not the everyday Windows user.

Alternatives so far proposed are:
- `%USERPROFILE%\Documents`
- `%USERPROFILE%\OneDrive\Documents`
- Read the custom location via `[Environment]::GetFolderPath("mydocuments")` call
- `CSIDL_LOCAL_APPDATA` or `CSIDL_APPDATA`
- Read some registry entries

I have no stake in this ticket (not a Windows or Mac user). I created it since the topic has been raised multiple times on various meetings.

**Comment by mwu-tow** [comment]
Any location that the user did not explicitly select will be unexpected. It would not occur to me to look in any specific place for anything I haven't saved on the disk.

We have no such capability now, so I'd just leave things as-is. At least `~/enso/projects` is easy to document and uniform. It is better than having to provide 3 different path variants every time we tell the user to go looking for a project files.

If we are really concerned about discoverability, I'd rather display the physical project path in some in IDE, perhaps even with some "open in explorer" action.

**Comment by jdunkerley** [comment]
@wdanilo / @sylwiabr do we want to agree on this for Windows and Mac.

The current location is unlikely to be backed up to users profiles (or cloud synced) in Windows.

**Comment by jdunkerley** [comment]
We are consistent with JetBrains products with where we put it in Windows. So closing this for now.
We should allow the user to read from any location and chose where to save but this is another ticket.
