### ISSUE TITLE
Cannot type special characters into an Enso node

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7139]
The Enso IDE does not allow you to use `Alt+NumPad` to enter special characters on Windows (nor does it support the emoji input via `Windows+FullStop`.

 Try entering ¥ (Alt-0165) and it will ignore the Alt being held down.
Using the emoji input is just ignored by Enso's IDE.

**Comment by wdanilo** [comment]
What this website shows when you click this shortcut? https://www.toptal.com/developers/keycode

<blockquote><img src="https://www.toptal.com/developers/keycodeog-image.png" width="48" align="right"><div><strong><a href="https://www.toptal.com/developers/keycode">JavaScript Key Code Event Tool | Toptal®</a></strong></div><div>KeyCode.Info allows users to press any key and instantly get the JavaScript Key or Key Code KeyboardEvent. Check out the Tool and Event List.</div></blockquote>

**Comment by jdunkerley** [comment]
https://github.com/enso-org/enso/assets/4699705/591e4da7-a3e2-4178-8b33-374380344646

Video attached of what site captures when typing Alt-0167 (§)

**Comment by wdanilo** [comment]
Interesting. If Im correct, we are using `event.key`, which for accents, gives good characters, like `ą`. We need to investigate if this is even possible to get the right glyph there, as I don't see it displayed on the website when you click the button combination.

**Comment by Akirathan** [comment]
I have just tried to copy and paste some random Unicode emoji 😂 into a literal node, and it is not displayed - 
![image](https://github.com/enso-org/enso/assets/14013887/f457a28c-fbe3-4139-8cc5-712f9ebcd2df)
. Is is related? (It works for other text fields in the browser)

**Comment by somebody1234** [comment]
the font rendering might just not support that glyph - especially if the font rendering doesn't try to use fallback fonts

**Comment by somebody1234** [comment]
re: the emoji/altcode stuff, events related to IMEs may be relevant: https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event

but i'd assume the OS needs to think that a text input is currently being focused, in order to open the IME in the first place. not sure how difficult that may be... it may be that having a dummy text input in the HTML that isn't visible (but is always focused) may work

<blockquote><img src="https://developer.mozilla.org/mdn-social-share.cd6c4a5a.png" width="48" align="right"><div><strong><a href="https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event">Element: compositionstart event - Web APIs | MDN</a></strong></div><div>The compositionstart event is fired when a text composition system such as an input method editor starts a new composition session.</div></blockquote>

**Comment by wdanilo** [comment]
> I have just tried to copy and paste some random Unicode emoji 😂 into a literal node, and it is not displayed -
> ![image](https://user-images.githubusercontent.com/14013887/249223765-f457a28c-fbe3-4139-8cc5-712f9ebcd2df.png)
> . Is is related? (It works for other text fields in the browser)

I'ts not related. We don't support displaying emojis right now and what you see is an expected behavior (although not the most beautiful one). But you were able to paste the emoji, move cursor around it and work with it, so what you see is another issue.

**Comment by farmaazon** [comment]
Both special characters and emojis seem to work in GUI2
