### ISSUE TITLE
Nodes names doesn't appear

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7259]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

<img width="1355" alt="image" src="https://github.com/enso-org/enso/assets/12892578/324f78fe-f8cf-4ad3-944f-bb96f0abbfec">

### Expected behaviour

Nodes names should be visible and should appear when editing a node or on hover

### Enso Version

nightly 11.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by vitvakatu** [comment]
Bisecting pointed at commit https://github.com/enso-org/enso/commit/fcaa7510c50

**Comment by Frizi** [comment]
I have found the root cause. I'm going to submit a fix soon.

This is caused by my partial, but incomplete removal of view mode logic (profiling related) from the nodes. In this case, the node output port turned out to depend on its `set_view_mode` FRP input receiving any initial value, otherwise the FRP network is never properly initialized. My fix is to complete the removal of display mode logic in the output port, which makes the name label behavior correct.
