### ISSUE TITLE
Hot-Reload not working under Linux

### ISSUE THREAD

**Issue by JanBeelte** [enso-org/enso#7403]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I modify the source file on disk it is not reloaded until I use the special hotkey (cmd alt y).

### Expected behaviour

Hot-Reload should work as expected.

### Logs

[20230726_watch_not_updating.log](https://github.com/enso-org/enso/files/12173037/20230726_watch_not_updating.log)
[sample.zip](https://github.com/enso-org/enso/files/12173126/sample.zip)

### Enso Version

b62c3d78675b4dc1eb7f5a3c8482b519012aa0ce

### Browser or standalone distribution

Firefox (not supported officialy, but should work)

### Browser Version or standalone distribution

Mozilla Firefox 115.0.2

### Operating System

Linux

### Operating System Version

Linux jan-desktop 5.15.120-1-MANJARO #1 SMP PREEMPT Wed Jul 5 21:45:37 UTC 2023 x86_64 GNU/Linux

**Comment by 4e6** [comment]
@JanBeelte can you also attach the contents of `package.yaml` (the file in the root of the project)

**Comment by JanBeelte** [comment]
Added it to the issue above.

**Comment by 4e6** [comment]
Thanks! One more question. I can see that you're using some kind of a dev build. How do you run the project? I.e what command do you use?

**Comment by 4e6** [comment]
Also, can you please check that the issue is reproducible in the latest [nightly release](https://github.com/enso-org/enso/releases), for example the one that was released today https://github.com/enso-org/enso/releases/download/untagged-e437b2014fb449dfec88/enso-linux-2023.2.1-nightly.2023.7.26.AppImage

**Comment by JanBeelte** [comment]
I pulled develop today and I am running via:
`./run ide watch --backend-source release --backend-release latest --skip-wasm-opt --ide-option -debug.dev-tools=true --ide-option -debug --ide-option --window=false`

**Comment by JanBeelte** [comment]
> https://github.com/enso-org/enso/releases/download/untagged-e437b2014fb449dfec88/enso-linux-2023.2.1-nightly.2023.7.26.AppImage

Within the AppImage it works as expected! How can I change my ./run command to also make it work there?
(It is important for me to have it running in the browser, that is why I also use --window=false)

**Comment by 4e6** [comment]
> I pulled develop today and I am running via:
./run ide watch --backend-source release --backend-release latest --skip-wasm-opt --ide-option -debug.dev-tools=true --ide-option -debug --ide-option --window=false

You can check the list of tags here https://github.com/enso-org/enso/tags and then use one of them as a `--backend-release` parameter, for example
```
./run ide watch --backend-source release --backend-release 2023.2.1-nightly.2023.7.20 --skip-wasm-opt --ide-option -debug.dev-tools=true --ide-option -debug --ide-option --window=false
```

Unfortunately the latest nightly built on July 24 is not usable due to an error during the build. I believe there is an issue and I am going to open a ticket regarding that

<blockquote><img src="https://opengraph.githubassets.com/6ac31ba1d75a880f0732862bdc26955d60054d8a6bf538c237d98dce96af3327/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Tags · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by 4e6** [comment]
For the reference #7408
