### ISSUE TITLE
When opening the project for a second time, suggestion database is not sent.

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#7413]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [x] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening a project multiple times in the same engine session, the suggestion database is sent only on the first visit. After that, the `search/getSuggestionsDatabase` endpoint seems to have no effect.

### Expected behaviour

The full suggestion database should be sent to IDE every time it uses `search/getSuggestionsDatabase` endpoint.

### How we can reproduce it?

1. Open a project in IDE. Take note that component browser offers many suggestions.
2. Refresh IDE.
3. Open the same project again.
4. Open component browser, notice missing suggestions.

### Screenshots or screencasts

Notice only small responses containing suggestion updates.
![image](https://github.com/enso-org/enso/assets/919491/b044fffc-9571-4c93-8969-1e1079b6ff1b)

### Enso Version

2023.2.1-nightly.2023.7.24.1

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

electron

### Operating System

Windows

### Operating System Version

11

**Comment by Akirathan** [comment]
I can reproduce this on `enso-linux-2023.2.1-nightly.2023.7.28.AppImage`, moreover, I have filtered logs only from the language server, and it seems that on the second project open, the number of suggestions database updates is roughly 64 KB, while after the first project open, the amount is larger than 1 MB. In the attachment, `00-ls.log` is the filtered LS-only log and `appenso.log` is the entire log from the project-manager.

[00-ls.log](https://github.com/enso-org/enso/files/12195992/00-ls.log)
[appenso.log](https://github.com/enso-org/enso/files/12195996/appenso.log)

**Comment by 4e6** [comment]
Well, that's because the suggestions mechanism has changed. The `search/getSuggestionsDatabase` now always returns an empty response. And the suggestions are automatically sent to IDE when a library is loaded by the compiler.

https://github.com/enso-org/enso/blob/7441a9a62cdec26ed0bd152ed556ec9025c38054/docs/language-server/protocol-language-server.md#searchgetsuggestionsdatabase

> Deprecated
> The request always returns empty entries field with the correct currentVersion. The suggestions are sent during the initial project compilation as a part of [search/suggestionsDatabaseUpdate](https://github.com/enso-org/enso/blob/7441a9a62cdec26ed0bd152ed556ec9025c38054/docs/language-server/protocol-language-server.md#searchsuggestionsdatabaseupdate) notification.

**Comment by 4e6** [comment]
The reason is that when the initial `search/getSuggestionsDatabase` request is sent during the project initialization. The suggestions database is empty anyway. Because no libraries are loaded. And since the request was not doing anything it was abandoned which allowed us to make the suggestions database more performant.

If we want to support the described scenario, I can try to revive the request.
