### ISSUE TITLE
When closing a project it takes a period of time for the server to exit, there is no indication on the dashboard

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7470]
When you close a project the shutdown of the language server takes time. There is no visual indicator on the dashboard that it is still closing.

User cannot delete or rename during this time. Some indication is needed that it is shutting down.

**Comment by hubertp** [comment]
The shutdown delay was introduced to allow for gentle re-connections. But explicit closing of the project could probably just proceed with shutdown immediately with no harm. We should detect this scenario and enforce it.

**Comment by hubertp** [comment]
Re the original problem (rather than discussing shutdown/reconnection ones): 
it seems to be a [deliberate decision](https://github.com/enso-org/enso/blob/develop/lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala#L151) to fail the deletion of the project when project is still running.

Rather than a simple yes/no running, we could add pending shutdown state. Alternatively, we could just try to force shutdown at this point.
