### ISSUE TITLE
Searching for static methods does not seem to consider written qualified name.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7486]
Follow up of https://github.com/enso-org/enso/pull/7484#issuecomment-1663493720

When I open CB and type `Table.new`, I get `Table.new` only at 3rd place.

![image](https://github.com/enso-org/enso/assets/3919101/870001a4-638b-4cb8-979e-cc94b0927a02)

I guess this is because the filtering pattern is only "new", and "Table." is a context, and for some reason we no longer filter out entries whose qualified names did not match the "context" part - this was a workaround meant to be removed once #5354 is implemented.

**Comment by sylwiabr** [comment]
Also the private entries should not be visible in default search.

**Comment by farmaazon** [comment]
> Also the private entries should not be visible in default search.

This is another issue: #7464

**Comment by kazcw** [comment]
> I guess this is because the filtering pattern is only "new", and "Table." is a context, and for some reason we no longer filter out entries whose qualified names did not match the "context" part - this was a workaround meant to be removed once https://github.com/enso-org/enso/issues/5354 is implemented.

The workaround is working the way it has since whenever it was introduced. The displayed entries all have `Table` in their qualified names, which is the condition tested; it looks like they are all `PRIVATE` functions defined in types within the `Table` module. All the unexpected entries in this case will be fixed by #7464.

We might improve the workaround by requiring the context to match at the end of the namespace (so that `Table.new` doesn't match `Table.Foo.new`), but I think once #5354 is implemented the current recursive-search behavior might make more sense.

**Comment by farmaazon** [comment]
Oh, I haven't noticed that each type has "Table" inside. So I guess it would behave the same in the old commits if they would display "PRIVATE" methods?

Ok, so I will put higher priority on task with "PRIVATE" tag, and then we consider if close this one.

**Comment by farmaazon** [comment]
No longer reproducible in GUI2
