### ISSUE TITLE
No column width modifications work after first one in full screen visualization

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7524]
In full screen vis, when I hover over a column delimiter, the cursor changes to a double-sided arrow, illustrating that I can click and drag to change the column width. This works only for the first width modification. After the first modification, I cannot even see the cursor change to double-sided arrow, and the click-and-drag does not work.

In normal visualization, I don't experience this problem.

To reproduce:
- Open a full screen visualization of a table
- Modify arbitrary width of a column
- No more widths can be modified unless you exit the full screen vis.

[Screencast_20230808_183251.webm](https://github.com/enso-org/enso/assets/14013887/f44558c5-57cb-4e0d-820f-60d9e2faaf08)

Tried on `enso-linux-2023.2.1-nightly.2023.8.8.AppImage`

**Comment by vitvakatu** [comment]
Might be related to #7518, will check today as well.

**Comment by radeusgd** [comment]
> Might be related to #7518, will check today as well.

In my issue I tried to describe exactly the same scenario, maybe not clearly enough. But that's definitely the same issue (at least to the part 2 of #7518 about 'visualization does not interact with Enso cursor').

**Comment by vitvakatu** [comment]
That's actually handy that we have two separate issues, as problems described in #7518 look similar, but are not actually connected. 

This issue is introduced by https://github.com/enso-org/enso/commit/6534d0a925b72a231e21a6824b37d94536d2bd55

It seems we defocus fullscreen vis when clicking anywhere, and there is no (easy) way to focus it again.
