### ISSUE TITLE
``union`` of two tables reports an "unexpected storage implementations" error when ``add_row_number`` precedes the ``union``

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7565]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Can't union on two tables:
![image](https://github.com/enso-org/enso/assets/108271897/3a17e801-0064-489b-bfda-81a4369cbbe9)

![image](https://github.com/enso-org/enso/assets/108271897/fe226b37-8027-45f9-b513-ffabed4afcad)

### Expected behaviour

``union`` working

### Enso Version

2023.8.11 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Win11pro 22H2 22621.1848

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by xvcgreg** [comment]
Skipping ``add_row_number`` makes ``union`` work again:
![image](https://github.com/enso-org/enso/assets/108271897/05447496-8800-46b4-89f7-df42c02a9730)

**Comment by radeusgd** [comment]
Indeed this is kind of a regression introduced by #6890 - I added `AbstractLongStorage` there but I still sometimes assume that `LongStorage` is the only storage for Integer type (which is no longer the case after that PR). It is only partially a regression because the 'non-standard' storage _only_ appears in `add_row_number` which was itself added in #6890 - so there was never a time when this worked correctly, it just used to be not available before.

Anyway - I've already noticed a few instances of this issues and fixed them in my upcoming PR #7557. However, I have still missed some cases - so thank you a lot for the report - it made me check this more carefully and now I should push a commit to #7557 that should eliminate all instances of this problem.
