### ISSUE TITLE
Support OS native mouse cursor

### ISSUE THREAD

**Issue by FeldrinH** [enso-org/enso#7667]
### How important is this feature to you?

4 – Lack of it makes using Enso a lot harder

### Describe the idea you'd like to see implemented.

Currently the Enso IDE seems to use a custom cursor that is rendered by Enso itself. It would be nice to have an option to use the native OS cursor instead.

PS: This is essentially a repost of https://github.com/enso-org/enso/issues/2897, because that issue was closed more than a year ago with no explanation and I have verified that the latest recommended release (2023.2.1-nightly.2023.8.2) still has the same sluggish custom cursor.

### Is your feature request related to a problem?

The custom cursor used by Enso is noticeably more laggy than the native cursor. Also, whenever the UI is loading something there are noticeable lag spikes during which the cursor is completely frozen. This makes working with the UI extremely frustrating. The problem is especially noticeable on my laptop, but even on my fairly powerful desktop computer the responsiveness of the Enso custom cursor is not as good as the OS built-in cursor.

All my computers run Windows, it is possible that this issue is worse on Windows compared to other operating systems. I currently don't have computers with other operating systems to test this.

EDIT: The sluggishness is less noticeable on a 144 Hz display compared to a 60 Hz display. After some more fiddling I think on my laptop most of the perceived lag comes from Enso itself running at less than 60 FPS and on my desktop most of it comes from the fact that the OS cursor has special status in the OS and is drawn as late as possible, which reduces perceived input latency.

### Would you be willing to help us implement this feature?

No

**Comment by vitvakatu** [comment]
Hi! Thank you for creating the issue. When changing our internal processes, we closed old points on GitHub some time ago, so your issue was closed accidentally.

As you have performance issues on your laptop, please provide us with more info.
1. Your hardware spec: CPU, OS, RAM, GPU.
2. Record a few seconds of the video working in IDE with the performance monitor opened. You can open it by pressing <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>`</kbd>.
3. Record a few seconds of the performance profile using Chrome dev tools:
   1. Open DevTools using the `-debug.dev-tools` flag when launching IDE or <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>i</kbd> shortcut. (I might be wrong about the shortcut; I'm not using Windows. It should be the same as in Chrome browser)
   2. Switch to Performance tab
   3. Press record
   4. After a few seconds, press stop, and then save the profile using the "Download" button at the top of the performance tab
   5. Send the profile file to us.

It will help us to debug and eventually fix the performance issue you're facing.

**Comment by FeldrinH** [comment]
Hardware specs:
HP EliteBook 840 G8 + Windows 10
CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
GPU: Intel Iris Xe Graphics
RAM: 16 GB DDR4-3200 SDRAM (1 x 16 GB)

https://github.com/enso-org/enso/assets/5256211/9c61af0e-4f6e-4cfe-a062-7c811a532bd9

Unfortunately I could get the Chrome Dev Tools recording saving to work. When I pressed the download button in Chrome Dev Tools it would prompt for the file location and then log the error `Failed to save timeline: The request is not allowed by the user agent or the platform in the current context. (NotAllowedError)` to the console. The saved file was empty.

**Comment by farmaazon** [comment]
We use system cursor in new GUI.
