### ISSUE TITLE
Can't stop the project on the newest nightly

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7706]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Trying to click the "stop" button in the dashboard results in the exception:

<img width="509" alt="image" src="https://github.com/enso-org/enso/assets/6566674/ea2d2b91-4f67-4525-a3f9-bd7f521865d2">

I use engine `2023.2.1-nightly.2023.8.30`.

### Expected behaviour

I'm able to stop the project.

### Enso Version

b49cc25d3879ca5fbc4810a3dd83809680f5f086

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by somebody1234** [comment]
@vitvakatu this is probably (?) because the format for saved project info changed, youll want to manually run `localStorage.deleteItem('enso')` in the console to fix it. i guess it'd be good to have systems in place to prevent crashes when there's invalid data saved in localstorage though? because I'm sure this wont be the last time the format of saved data will change

**Comment by somebody1234** [comment]
A potential fix has been added to #7710, might want to make sure the fix does indeed solve your issue

**Comment by somebody1234** [comment]
closing, i'm assuming this was fixed by the PR linked above
