### ISSUE TITLE
Visualization Container with chooser, resizing etc.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7733]
As in the [new design](https://github.com/enso-org/design/blob/main/epics/component-browser/design2.md) 

![Image](https://github.com/enso-org/enso/assets/3919101/7c2f9ee4-25a6-4ec6-95db-99b1ae1fe28d)

The visualizations are Vue components.

The two first icons (eye and "compass") are managed by the node view (this is "show/hide visualization" and "visualization chooser" respectively), others are parts of the visualization.

The visualization themselves needs to use "VisualizationLayout" component provided by us, which will allow using multiple predefined slots for putting different UI elements (for example a button bar) in the right place.

**Comment by somebody1234** [comment]
**E-Hern Lee** reports a new **STANDUP** for the provided date (2023-09-04):

**Progress:** - begin integrating visualizations into `GraphNode` to ensure they actually work
- refactor visualizations into their own module
  - this is mainly to dogfood (and help develop) the infrastructure to dynamically load modules
    - (note that this does not currently work. we probably need to import `vue/compiler-sfc`, and potentially also a VFS to combine the builtin visualizations with the project-local visualizations into the same file tree for compilation purposes)
- change visualization component's API to use slots (default slot for main content, and `toolbar` slot for the (single) component-specific toolbar)
- minor changes to CSS. :warning: the circular menu and toolbars now use a `background-filter: blur(64px)`, according to the figma design. it has been brought up that this is potentially computationally expensive, so we should consider adding an option to disable all blurs (and potentially all transparency too) across the entire app

other issues -
- fix merge conflicts, tidy up code, add dummy actions, and open PR (7726) for top bar (7730)
- fix merge conflicts, tidy up code, and open PR (7728) for widgets (7731)

(:information_source: note: posting standup manually because the bot errored - the standup appears as expected on airtable.)
