### ISSUE TITLE
[GUI2] Undoing a node deletion breaks AST ID assignment.

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#8134]
After deleting a node and hitting undo, the node is no longer being evaluated. Reloading the project reveals, that the node metadata was also not properly saved. This is caused by the ID map is not being properly undone. The behavior observed so far:
- Multiple AST IDs ends up being assigned to the same range, and ranges generally are a little bit incorrect for the undone text ranges
- The affected node's expression AST ID (used for node ID) is not assigned properly, but somehow the local client still recognizes the node metadata unitl page refresh.

It appears that the Yjs Relative Positions don't behave as expected after an undo operation, since their representation in the undone transaction is not accurately representing the state after that undo is applied. Understanding that behavior needs more testing.

**Comment by kazcw** [comment]
The conflict resolution of `Y.Text` can break syntax trees.
- This can't easily be detected and repaired.
- To ensure conflict behavior is reasonable, we should **change the representation we synchronize**.
- Although sync is not a priority now, the canonical representation is a fundamental design choice,
  easier to change sooner than later.

An important design choice is the mapping between AST and text.
- The parser's current `Span`s cannot efficiently support edits.
- `Y.Text` has been providing a mutation-aware mapping in the form of `RelativeOffset`s.
  - They aren't perfect; they don't interact well with undo/redo.
  - But they are why we hadn't needed mutation-friendly source-code references yet.
- We should **add edit-friendly references to `Span`s**.

The new representation needs to support read/write via AST changes, the text editor, and external file changes; as well
as correct conflict resolution, and undo/redo.
- We can achieve this by **using block structure as the Rosetta stone**.
  - `codemirror` supports `line:column` text locations natively.
  - The parser can include `line:column` information in its source code references.
  - We can synchronize a module as a *sea of lines*.

Sea of lines:
- A `Y.Array` of lines, but we don't care about the array's order.
- Each line has an ID, a parent, siblings, and `Y.Text` data.
- The only conflicts that aren't automatically resolved well are ordering, but we can recover:
  - If we end up with a dead reference within a block, we still know its position because we have before+after, so we can repair the links.
  - If two nodes are placed with the same before/after, we know they don't reference each other, so we just need to choose any relative order and repair the links.

**Comment by farmaazon** [comment]
There is no longer a problem with deleted node being not evaluated... but metadata are still gone. But that is now tracked by #9314
