### ISSUE TITLE
`file/event` response lacks FileAttributes

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#8200]
See #8199 

We’re forced to make a separate `file/info` request to ensure the file was created, not a directory. Passing additional information about updated filesystem objects in `FileEventNotification` would be helpful.

**Comment by 4e6** [comment]
Looking at the client logic

https://github.com/enso-org/enso/blob/1b3c9638ea348c20d27879a8151d317a8b4549f9/app/gui2/ydoc-server/languageServerSession.ts#L106-L115

I believe you should not make the `file/info` request at all because you already check `isSourceFile(event.path)`.

If the path is a directory, the `text/openFile` should return a [NotFile](https://github.com/enso-org/enso/blob/1b3c9638ea348c20d27879a8151d317a8b4549f9/docs/language-server/protocol-language-server.md#notfile) error, and it should be handled appropriately.

I would implement the `NotFile` error for the `text/openFile` request instead of querying the FS for every file event.

**Comment by 4e6** [comment]
Today @JaroslavTulach pointed out that if the FS emits a file event then the file should be in the FS cache, and querying its attributes is a cheap operation. I will implement getting the attributes instead

**Comment by vitvakatu** [comment]
> I believe you should not make the file/info request at all because you already check isSourceFile(event.path).

Given that a failure to open a file results in a server crash, the stakes are too high to consider anything with the `.enso` extension to be a file, not a directory. Yes, we have some redundancy here, but only to make it as durable as possible.

@somebody1234 also mentioned that this fix could benefit our visualizations loader.
