### ISSUE TITLE
List Editor widget

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8261]
List editor widget should allow adding, removing and moving elements by drag'n'drop.

If the mouse cursor is in the area between elements, it should change shape and color to indicate that adding is possible. Pressing in this area adds default element. Also, the + icon should appear at least in an empty vector, which adds elements at the end.

![Image](https://github.com/enso-org/enso/assets/3919101/83bd5f03-1491-42c2-bd11-023e104ab542)

```[tasklist]
### Tasks
- [x] List Editor which allows adding entries and reading configuration
- [x] Dragging and removing in List Editor
```

**Comment by farmaazon** [comment]
Refinement notes:
* If something is hard to do, let's make it in a simpler way, because the list editor will be revised soon anyway.
* Regarding dragging: the tricky part is to share mouse events between list editor and the nested widgets.

**Comment by farmaazon** [comment]
Inserting things between existing elements should be skipped in this implementation.

**Comment by somebody1234** [comment]
Yeah, that's fair. For now, it should be easy enough to add an element to the end and then drag it into place anyway

**Comment by somebody1234** [comment]
regarding dragging: for now i've decided to register both click and cmd+click.
nested widgets should still work when using click, as the events bubble up (and can be handled in an inner widget)

shift+click is not an option due to a bug in chrome: <https://bugs.chromium.org/p/chromium/issues/detail?id=982219>

<blockquote><div><strong><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=982219">982219 - 
 
 
 chromium -
 
 
 An open-source project to help move the web forward. - 
 
 Monorail</a></strong></div></blockquote>
