### ISSUE TITLE
Ability to write a Table in XML format

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#8413]
We should be able to do `table.write "foo.xml"`.

The format of the XML output is up for discussion.

One of the proposed approaches is:
```
<Table><Row><ColName>value</ColName>.... 
```

- [ ] Add `XML_Format.write_table` extension method in the Table library (probably in `Table_Conversions`, similar to `JSON_Format`)
- [ ] Add tests verifying the write behaviour - the tests should ideally check the dry-run and backup behaviour as well (similarly to e.g. our Excel tests)

**Comment by radeusgd** [comment]
> One of the proposed approaches is:
> 
> ```
> <Table><Row><ColName>value</ColName>.... 
> ```

Regarding the format we'd like to use, I think it would be good to try to ensure that it 'round-trips'.

e.g. that if we save a table to XML and read it back again, IMHO it would be good if the XML-parsed table had the same structure as the one we started with.
```
table = ...
f = File.new "test.xml"
table.write f
f.read f . to Table . should_equal table
```

Ofc I imagine we may have exceptions to that - e.g. if column names contain some atypical characters or if the cells contain objects that cannot be deserialized (obviously). But for a simple table containing primitive data, IMO it would be good to be able to read it back again. Although that is probably not the biggest factor in deciding the format - since we already do have that property if saving as CSV or Excel - so XML does not necessarily need to be a format for storing tables (it definitely isn't the preferred one anyway).

**Comment by somebody1234** [comment]
I think the more important issue is, I'd assume the output should be useful in some way - meaning, are there tools that can consume XML files? In which case, we should probably prefer to use an identical format to one of those.

(Things that come to mind are [OpenDocument](https://en.wikipedia.org/wiki/OpenDocument) and [`.xlsx`](https://en.wikipedia.org/wiki/Office_Open_XML))

Alternatively, we could have a specified XML format for all values in general, so that in case we decide to be able to serialize individual columns, or vectors, etc in the future?

**Comment by radeusgd** [comment]
> I think the more important issue is, I'd assume the output should be useful in some way - meaning, are there tools that can consume XML files? In which case, we should probably prefer to use an identical format to one of those.

Thanks @somebody1234, I think you are raising a very good point!

There isn't that much value in 'being able to write Table in some random XML format', if it's not a format that can be read by other stuff. I think indeed we should have some justification.

e.g.
- writing to CSV is the simplest way to save the table for later and it's a very portable format
- writing to XLSX allows us to export the table to Excel
- writing to JSON allows to relatively easily create JSON data from a table

But XML is more structured than JSON so a 'generic' XML generated from a table indeed does not seem that useful. If I want to _"just"_ write the table to a file, I'll most likely choose CSV over it.

If I want to write XML, it is usually because I then want to load it by something else - so the format has to fit that - e.g. JUnit test reports and things like that. 

So indeed, I think that maybe instead of a generic 'write table to XML format', we should focus on 'generate XML file' functionality? i.e. something that gives the user the control they need over what kind of XML is generated - what are the names of the `<nodes>`, is data stored as sub-nodes or as attributes? All this then can source its data from a `Table`, but it feels like the user needs control over the structure of the generated XML for all of this to make sense. Without it, it seems like we would be doing it 'just to do it', but without much of a purpose - unless we want to treat it as a prototype and extend with more structural control later - I guess that could be one path forward for this.

@jdunkerley what do you think about that?

**Comment by somebody1234** [comment]
:information_source: i may be overthinking, but... here are some further thoughts:

> something that gives the user the control they need over what kind of XML is generated

yeah, that does certainly sound promising - but I do still think we'd ideally want to gather use-cases first, if possible. otherwise we might spend a bunch of time implementing it, and potentially fighting bugs... only to find out that what people wanted wasn't (say) automatic sanitization of tag names, but rather being able to have certain columns as attributes and others as children, or being able to omit (or always include) columns with `Nothing` as a value, being able to omit `xmlns` and the xml header, etc.

(or alternatively, maybe all the functionality *does* end up existing, but it becomes a convoluted process trying to get the parsing correct in the GUI)

basic research suggests things like these as examples:
<https://omicstutorials.com/xml-in-bioinformatics-a-comprehensive-guide-for-biologists/>

<https://stackoverflow.com/questions/17198658/how-to-parse-an-xml-file-to-an-r-data-frame>
-> <http://forecast.weather.gov/MapClick.php?lat=29.803&lon=-82.411&FcstType=digitalDWML>

and i guess some XML files that are more related to programmers, rather than data analysts
<https://learn.microsoft.com/en-us/aspnet/web-forms/overview/deployment/web-deployment-in-the-enterprise/understanding-the-project-file>
<https://maven.apache.org/pom.html>
<https://stackoverflow.com/feeds>

(ideally they'd be prioritized depending on which ones are users most likely to need to work with too)

**Comment by jdunkerley** [comment]
The idea is to have a very simple general writer here. We will have specific format writers (such as xlsx and openoffice).

Conceptually this is to write a simple table to a generic format along the lines of the JSON write for a table.

```xml
<!-- @Author | Title //-->
<!-- XML_Format.XML_File docelement="Library" rowelement="Book" -->

<Library>
    <Book Author="Jim McWriter">
        <Title>My Little Book of Python</Title> 
    </Book>
</Library>
```

The first part of this ticket is to design the API more fully.

**Comment by jdunkerley** [comment]
Can we amend the `to_xml` so that it produces an `XML_Document` that we can then call `to_text` to serialize to text and has a `write` function.
