### ISSUE TITLE
Add benchmarks to `runtime-compiler`

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#8419]
There are no benchmarks for parsing or compiling. Let's add benchmarks to `runtime-compiler` or/and `runtime-parser` projects. Ideally, make sure that these benchmarks are visible in https://enso-org.github.io/engine-benchmark-results/engine-benchs.html

Will be good for #7054

**Comment by JaroslavTulach** [comment]
Let's create directory `compiler` next to existing [semantic](https://github.com/enso-org/enso/tree/b8f4dc32c9e2fb410522b9eefd3ccc9da7b54839/engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks) and put the benchmark there. It will then automatically appear at https://enso-org.github.io/engine-benchmark-results/engine-benchs.html

<blockquote><div><strong><a href="https://enso-org.github.io/engine-benchmark-results/engine-benchs.html">engine benchmark results</a></strong></div></blockquote>

**Comment by JaroslavTulach** [comment]
Let the benchmark generate _traditional end user code_:
```
from Standard.Base import all

main =
    operator1 = File.read "blabla"
    operator2 = operator1.xyz 2 where=Location.Start
    operator3 = operator1.abc "Hi3"
```
If we can generate such code, then we can have a benchmark for 100, thousand and ten thousand line file and compare the scalability of our implementations.

**Comment by JaroslavTulach** [comment]
What shall we measure? We want to _measure creation of the IR and applying compiler `Passes` to it_ - probably  how long it takes to invoke [Compiler.run](https://github.com/enso-org/enso/blob/b8f4dc32c9e2fb410522b9eefd3ccc9da7b54839/engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala#L124) method. However that method requires an implementation of `CompilerContext.Module` which isn't easy to get. One way is to mock it, but probably easier to just `org.graalvm.polyglot.Context.eval("enso", ....)` and get a reference to `main` method (without invoking it). That shall be simpler (as the API already exists) and good enough to begin with.

**Comment by radeusgd** [comment]
> Let the benchmark generate _traditional end user code_:
> 
> ```
> from Standard.Base import all
> 
> main =
>     operator1 = File.read "blabla"
>     operator2 = operator1.xyz 2 where=Location.Start
>     operator3 = operator1.abc "Hi3"
> ```
> 
> If we can generate such code, then we can have a benchmark for 100, thousand and ten thousand line file and compare the scalability of our implementations.

Won't this hide the issue of various levels of complexity? I.e. a 10 line function with lots of variables and dependencies may be more complex to analyze (especially if something in it were O(N^2)) than 10 independent 1-2 line functions that are very trivial.

Maybe we could try using our `Standard.Base` library as the _'corpus'_ for the benchmarks? It should contain methods of varying levels of complexity and is probably the best 'example' we can currently get of a big codebase in Enso that uses various kinds of patterns.

What do you think?

**Comment by Akirathan** [comment]
@radeusgd I think that the proposal from @JaroslavTulach makes more sense for now, as it resembles more closely what is actually parsed and compiled in the IDE.

Besides, when you import `from Standard.Base import all`, all the modules that are transitively reachable are compiled. So I am not sure I follow your reasoning here.

**Comment by radeusgd** [comment]
> Besides, when you import `from Standard.Base import all`, all the modules that are transitively reachable are compiled. So I am not sure I follow your reasoning here.

🤦 oh I have somehow completely missed that. Then indeed my suggestion is moot, you are 100% right.

**Comment by radeusgd** [comment]
Well I guess what still stands is - I don't think we should be generating sources by multiplying the 3 line example multiple (10s, 100s, 1000s) times.

Because then the timing will get saturated by the time to parse these simple 3 lines, instead of the time needed to compile `Standard.Base` - which I imagine is much more complicated to compile and provides a better benchmark of practical usage.

Maybe both are worth measuring though.

**Comment by JaroslavTulach** [comment]
> Maybe we could try using our `Standard.Base` library as the _'corpus'_ for the benchmarks?

- `Standard.Base` is a **moving target** not really suitable for a _"unit benchmark"_ of the compiler
- When there is a regression: is it because of a problem in `runtime/compiler` or because of changes in `Standard.Base`?
-  Btw. such an _"integration benchmark"_ has already been proposed by #8820

> complex to analyze (especially if something in it were O(N^2))

The point of having files of various sizes is exactly to identify **complexity of our algorithms**! We don't want `O(N^2)` algorithms at places where speed matters.

> 10 independent 1-2 line functions that are very trivial.

There can be a benchmark that generates 10, 100, 1000 simple functions as well. That checks scalability from another angle.

> I don't think we should be generating sources by multiplying

The important goal is to have the benchmarking in place, run some benchmarks, collect the results. And, most importantly, make it **easy to add new benchmarks** to the system when a new performance problem is found.
