### ISSUE TITLE
Merge dashboard and GUI2 to single project

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8484]
Currently, the dashboard code and gui2 code are in completely different places (the former being a part of `ide-desktop`). They should be in a single IDE workspace. The current GUI2 should be rather named "project view".

**Comment by farmaazon** [comment]
Refinement notes:
* We should not have a separate esbuild for dashboard. But ask @somebody1234 how they integrate with dashboard in "borwser" version, and how to not break it.
* Also, revive the topic of using vue in dashboard as well.
* The shared part (shortcuts) should be in a single directory owned by both teams. But without changing dashboard now (just say them, that they could replace their shortcuts with ours).
* E2E tests may be moved to single place but still separated.

**Comment by somebody1234** [comment]
initial notes from my side:
- re: separate build script for dashboard:
  - dashboard now uses Vite as well, but it has a different entrypoint in its own `entrypoint.ts`. not sure whether they can be more or less merged.
- re: vue in dashboard - personally i'm not against it, *but* i figured it's better to avoid it for now at least because we now have another cloud frontend developer (sergei) - and we were looking for react developers specifically.
- shortcuts: i've refactored GUI2's shortcuts module for use in the dashboard. one issue would be that the module should handle *both* native *and* React events - which is not a problem for the code, but is a problem in terms of pulling in unnecessary dependencies into Vue.
  - the dashboard version has some extra features compared to the GUI2 one - mainly, metadata containing icons and names (iirc?) for display in the dashboard settings page.
- idk about E2E tests. i think it makes sense to have them in the separate directories if the codebases are still separate modules (i don't really think it makes sense to fully merge the codebases into a single module, tbh)

**Comment by farmaazon** [comment]
Putting on hold, as we must discuss the whole affair with cloud team first - there were different visions in both teams.

Also, it would be good to have build scripts moved to Bazel first.
