### ISSUE TITLE
Compiler Internal Error: Could not deserialize idmap.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8500]
### Discord username

farmaazon

### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Sometimes when I open project, I get no updates from the engine (the nodes are gray and visualizations are stuck in "loading" state). In the PM log, there is an error `Compiler Internal Error: Could not deserialize idmap.`

Strangely, it seems to not depend on the file I use, because opening same project second time works just as fine.

### Expected behaviour

IDE opens and nodes are evaluated. No Compiler Internal Errors.

### How we can reproduce it?

I see it rarely, but it happens more than once. 

I saw it for this project once, for example: 
[New_Project_33.zip](https://github.com/enso-org/enso/files/13613365/New_Project_33.zip)

### Logs

PM logs after I opened project once and it failed as described. Then I opened the same project second time and it worked.

[enso-project-manager-2023-12-08.0.log](https://github.com/enso-org/enso/files/13613357/enso-project-manager-2023-12-08.0.log)

### Enso Version

IDE built on commit e4b2b56a405ef5036a9351319112c53ade3aed47 with nightly PM (2023-12-08

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

 120.0.6099.71

### Operating System

Linux

**Comment by farmaazon** [comment]
@4e6 or @hubertp could you look at PM logs and see if it's something there?

**Comment by hubertp** [comment]
There are no updates from the engine because it fails to parse the metadata section and eventually even run a first compile, yes. Can't really say how is that even possible or verify because `Main.enso` in the attached projects looks alright. Also not sure how a second run would "fix it". Quite possible there is some race involved.

I can see that a request is being made early on `Adding pending file edits: List((Range(Position(14,293),Position(14,377)),0))` which means that some text in metadata section is being replaced with an empty string. Do you happen to have the message that sent that message from IDE, cause it seems suspicious to send it at the beginning?
Is this a new or old GUI?

**Comment by farmaazon** [comment]
> I can see that a request is being made early on `Adding pending file edits: List((Range(Position(14,293),Position(14,377)),0))` which means that some text in metadata section is being replaced with an empty string. Do you happen to have the message that sent that message from IDE, cause it seems suspicious to send it at the beginning? Is this a new or old GUI?

It's a new GUI. I don't have the network log handy now, perhaps new GUI does some mischief on the beginning.

But even then, any invalid metadata should not break the compiler. The module could be edited externally to just any shape.

(BTW it would be nice to have the full communication between GUI2 and engine stored somewhere as a debug log)

**Comment by hubertp** [comment]
> (BTW it would be nice to have the full communication between GUI2 and engine stored somewhere as a debug log)

https://github.com/enso-org/enso/pull/8452
