### ISSUE TITLE
Local Project Manager should be able to work against any folder

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#8650]
The goal is for the local and cloud project managers to have mostly the same functionality.

One step is for the local Project Manager to be based off another folder.
Will need an API for the IDE to be able to change folders.

Goal is for the local IDE to have folder structure visible so you can organize stuff.

**Comment by somebody1234** [comment]
I think ideally we would want a way to watch specific folders for status changes (project added, project removed, project state change). Cloud doesn't have this functionality either so it's low priority + probably needs time spent designing it, but I think it's still something we should potentially take into consideration when designing this API.

Apart from that, note that the dashboard shows projects in a tree, meaning it can have multiple folders open at once. It's not a big deal since it just uses the underlying `listDirectory` API in the cloud to do that, but again might be worth taking into consideration.

Also note that there are a number of operations on projects (cut, copy, duplicate, plus dragging assets to move them around) that should *eventually* be supported. (Again though, likely out of scope for this initial issue.)

**Comment by 4e6** [comment]
I imagine it this way. If the user wants to open a project from a different location, Electron should allow opening a native system dialog to choose a directory. After a new directory is selected, you can pass it to the [`project/list`](https://github.com/enso-org/enso/blob/1b3c9638ea348c20d27879a8151d317a8b4549f9/docs/language-server/protocol-project-manager.md#projectlist) to list the projects in the new directory.

For this to work, we need to update the project manager API to support a new optional `baseDirectory` parameter.

```ts
interface ProjectListRequest {
  numberOfProjects?: Int;
  baseDirectory?: string;
}
```

**Comment by somebody1234** [comment]
@4e6 I think though, that the main usecase would be to be able to browse (and/or watch) an entire directory tree (which should initially be ~/enso?). But it's worth noting that we probably don't want to watch the entire tree right away, because the directory structure might be *really* deep and/or really big

**Comment by 4e6** [comment]
@JaroslavTulach pointed out that having a running process that can tell you the contents of a directory is a security vulnerability because the project manager doesn't have authentication and any user of the system can list directories of the user that started the project manager.

To mitigate this, instead of using `project/list` command on a running process, we can run the project manager as a CLI tool, e.g `project-manager --list /path/to/directory` and read the stdout. And only start the long-running project manager when we open the project.

**Comment by somebody1234** [comment]
@4e6 just a heads up, cloud does allow opening subdirectories of the root directory. is there a security issue in allowing those without restrictions?

**Comment by 4e6** [comment]
It is not an issue in the Cloud because we can guarantee that only one user has access to the machine.

**Comment by somebody1234** [comment]
wait, i mean letting the local backend (not the cloud backend) list descendant folders of the initial root directory
