### ISSUE TITLE
Add File Browse Widget

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#8681]
- Create a new file browse widget, working in electron for local projects only, using the system file browser.
- Make Data.read use the file browse widget. 
- Note: Needs to be able to be an option within a dropdown list.

**Comment by farmaazon** [comment]
First version: in local project, just use the system File browser.

**Comment by farmaazon** [comment]
I guess clicking `path` argument in Data.read should start editing path and show the dropdown with single "pick in file browser" option? Or we should open FB on every click at widget? @AdRiley @jdunkerley

**Comment by farmaazon** [comment]
Refinement notes:
* Use electron API for system file browser. The widget wouldn't work properly in browser anyway (no access to full paths there).
* File browser is opened only when picked an option from drop down.
* Display widget on types containing `File` type. If the type accepts also Text, the widget should prefer inserting Text instead of `File.new` if it's first in the list.
