### ISSUE TITLE
Restrict slider to min/max values

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8752]
In Numeric Input Widget, the slider should be displayed only when the engine's configuration specifies a range (in dynamic config). The slider range should be (obviously) restricted to that range.

**Comment by somebody1234** [comment]
possible follow up (?):
there are other types of sliders, which use the whole range of the screen as the drag area, allowing much finer control.
note that this *may* require capturing the mouse so it doesn't disappear off the window (although the drag will still work)

also note that this is something that may want to be implemented even with a limited range, as the slider widget *is* very small, so with a range > the slider's size in pixels, many numbers *will* be unreachable.

(the slider was implemented this way mainly (a) for convenience (it's a *bit* easier to implement) and (b) because no other widget really tracked mouse deltas directly)

**Comment by vitvakatu** [comment]
I believe we have a design where vertical movements of the mouse control the accuracy (the delta) of slider’s movements.

**Comment by somebody1234** [comment]
ah, indeed.
