### ISSUE TITLE
Auto layout doesn't take the connections into account when placing nodes

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8963]
For example, when creating "Geospatial analysis" example and removing metadata, all nodes seem to be laid out backwards (so all connections are going up)

![Image](https://github.com/enso-org/enso/assets/3919101/99f498bc-5cf2-44ab-8ae7-bad9885a4281)

**Comment by farmaazon** [comment]
Note: Just put them from top to bottom as in file. This ensures topological order.

**Comment by MichaelMauderer** [comment]
This seems to be fixed by c811a5ae8ba4a512eb74ece2f9f6cb332c3bcdd4. 

Before this commit, I observed that removing the metadata of a program results in the graph being updated with a reversed layout, as in the screenshot above. After this commit, this behaviour is gone and the layout is correct.

New projects without metadata seem to be laid out correctly before and after this commit.

**Comment by farmaazon** [comment]
Let's yet investigate if the nodes are actually sorted, or we get the proper order by chance.
