### ISSUE TITLE
Removing last node from main graph makes execution error

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9172]
As in description: the error appears:

![image](https://github.com/enso-org/enso/assets/3919101/447f674e-1a5b-4284-9e43-82310a700e41)

And then nothing can be done in the graph.

**Comment by farmaazon** [comment]
Not reproducible on `c2842df8d83139702f9ba712452f0ea84f98524e`

**Comment by AdRiley** [comment]
Still getting the error message in enso-win-x64-2024.1.1-nightly.2024.4.30.exe

![image](https://github.com/enso-org/enso/assets/1720119/546ff213-98ad-4dd7-96a7-4672b131736c)

**Comment by Akirathan** [comment]
Removing last node from the graph leaves behind code `main =`, which is invalid:
![image](https://github.com/enso-org/enso/assets/14013887/c5fd1aa0-533a-4c2b-8ebd-7d323e352985)

The engine sends in on of `executionContext/executionStatus` messages that this is an invalid syntax. Which is expected.

Later, when I try to create a new node in an empty graph, the GUI sends `executionContext/executeExpression` for something in the component browser, and engine responds with an `executionContext/executionFailed` as expected.
![image](https://github.com/enso-org/enso/assets/14013887/53ecc2af-24e5-4321-a379-62fb7571fa90)

I believe that the problem is on the side of the GUI, that should ensure that once a graph is empty, it should not leave an empty block behind resulting in invalid syntax.

**Comment by Akirathan** [comment]
After a discussion on [Discord](https://discord.com/channels/401396655599124480/1201853256691888169/1236982044786167900), we came to a conclusion that the following snippet:
```
main =
```
Should be semantically equivalent to:
```
main =
    Nothing
```

Also note that for parser, the assignment operator without rhs is not an error. For example, the following code:
```
main =
    operator1 =
    operator2 =
```
is parsed as
```
(BodyBlock #(() (Function (Ident main) #() () "=" (BodyBlock #((Function (Ident operator1) #() () "=" ()) (Function (Ident operator2) #() () "=" ())))) () ()))
```

After all, the problem can be solved **on the Engine side** somewhere in https://github.com/enso-org/enso/blob/develop/engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java#L248-L251


<blockquote><img src="https://opengraph.githubassets.com/9195829d870304d6ae157e8ff91e96730595232e9a6524b965e61d812fbd25ca/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/blob/develop/engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java">enso/engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java at develop · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by farmaazon** [comment]
Unassigning, because once engine will support empty function blocks, the GUI should work just fine. If it won't just reassign `-gui` and me.

**Comment by 4e6** [comment]
Because we don't implicitly import builtins, the following code
```py
main =
```
will fail with `error: The name Nothing could not be found.`

**Comment by farmaazon** [comment]
> Because we don't implicitly import builtins, the following code
> 
> ```python
> main =
> ```
> 
> will fail with `error: The name Nothing could not be found.`

But this code
```
main =
    operator2 = 13
```
Does not fail with any error, while still returning Nothing.

**Comment by 4e6** [comment]
Ok, that makes sense, so the
```py
main =
```
should result in
```py
main = ()
```
where `()` is an empty block that when evaluated, result to `Nothing`
