### ISSUE TITLE
Make hashing consistent for values near `Double.MAX/MIN_VALUE`

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#9296]
Values around `Long.MAX/MIN_VALUE` hash differently as `Integer` and `Float`, even when they are considered equal.

Specifically, these values:
9223372036854776000
-9223372036854776000

However, the problem also occurs for values near these, such as

9223372036854775999, -9223372036854775999

When these values are converted to Float, they are rounded to +/-9223372036854776000, and so comparing such a value with

i == i.to_float

will return True, while the hash values are different.

The problem is that `BigIntegerOps.fitsInLong(double)` converts `MIN/MAX_VALUE` to double before comparison.

This is a separate task to ensure that fixing this doesn't make it inconsistent with behavior in other code.

**Comment by GregoryTravis** [comment]
This issue actually occurs for many values, not just values near `Double.MAX/MIN_VALUE`, which means that we are consistently inconsistent: int/float pairs that are `==` do not necessarily have the same hash, which is an acceptable exception.

**Comment by GregoryTravis** [comment]
Closing as working-as-intended.

**Comment by radeusgd** [comment]
> This issue actually occurs for many values, not just values near `Double.MAX/MIN_VALUE`, which means that we are consistently inconsistent: int/float pairs that are `==` do not necessarily have the same hash, which is an acceptable exception.

Should we consider to give the user a warning if int and float values are mixed in a `Map`? I guess normally the user will expect that to work OK - less advanced users may not really care much about distinguishing Integer and Float values, possibly treating them interchangeably in many places (which Enso facilitates). So if they do use these interchangeably and then run into a hashmap - they may be surprised. And such bugs are often really really nasty to track down.

So I suggest to have some form of warning, in one of the following ways:
1. (easy but maybe too annoying) the moment a Map contains both int and float entries, tell the user it is risky,
2. (harder but then will very rarely occur) detect when a hashmap contains both int and float entries **and** some entries it contains are in the ranges where this problem occurrs - so we can have potential or real collisions - and warn in that case.

I'm not sure how much harder (2) would be to implement, if it is viable at all. Ideally it would be better, because for situations like a hashmap with `2` and `2.0` it is probably fine and no warning is needed, it only is needed if these problematic numbers appear. Maybe we can detect them with some heuristic?

(1) is a bit broader but we would just discourage users from mixing types in a hashmap, which is probably good anyway.

> I imagine if we implement either warning (1) or (2), it should not only occur if a map contains such a mix of int and float values but also in cases like 'a map containing ints, queried (`get`, `contains_key`, etc.) with a float key and vice-versa.

This is getting a bit more complicated, so alternatively:
3. maybe if our Map implementation does not work correctly with mixing floats and ints, we should discourage it altogether and stop trying making it work with these simple cases (that allow us to interchange `2` and `2.0` in a hashmap) and simply decide (like Java does) that equal Float and Integer values have a different hash and _should not be mixed in hashmaps at all_ (then we'd probably want the (1) warning variant anyway).

-----

Overall my point is - the current solution is a bad compromise, because we try to make the hash equality work for simple cases (e.g. `2` and `2.0`) but it does not work for some other cases. This is really bad because it first teaches the user that they can rely on the equality and they do not need to really care if they are working with Integers or Floats, but then as they start using the feature and work with bigger numbers, they can run into unexpected inconsistencies. 

I'd rather not pretend we support a feature that works only halfway, and instead be open that mixing Floats and Integers in a hash map in Enso is a bad idea.

------

I know I may come as very nitpicking, and I do appreciate that this (only???) happens for rather large that our users are not going to run into very often. And that's right - so I don't think that any of the solutions proposed above (or some other solution) should be implemented right away. But I think we should keep track of this issue and try to address it at some point in the future.

I think we really need to ensure that users can trust the results that they get in Enso. If users start getting running into weird bugs that can cause their results to become corrupted due to wrong handling of hashing, they may lose trust in the product and it may be hard to regain it.

On the other hand of course I'm keeping in mind this hashing problem (if I understand correctly??) is a relatively rare occurrence, so with all much more pressing things to create, it may not be the most pressing issue ot resolve. But I don't think we can abandon it altogether, without any warnings whatsoever.

**Comment by GregoryTravis** [comment]
@radeusgd I agree with you that we should be more consistent. I think the best would be to change the hashing so that `2` and `2.0` have different hash values, so that (as you said) users wouldn't get the idea that they can count on that.

Beyond that, I think warning (1) is probably enough -- using floating-point values (or numbers in general) as hash keys is unusual, so I don't think warning in this case would be too much.

I know @jdunkerley has said that using floating-point keys is just a bad idea in general -- perhaps we could attach a warning for any such use (`get` or `put`), which would then cover the case where a user was using both floating-point and integer?

**Comment by radeusgd** [comment]
> I know @jdunkerley has said that using floating-point keys is just a bad idea in general -- perhaps we could attach a warning for any such use (`get` or `put`), which would then cover the case where a user was using both floating-point and integer?

I think that sounds reasonable.

**Comment by GregoryTravis** [comment]
#9607, #9608
