### ISSUE TITLE
GUI2 times out  connecting to Language Server on large projects

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#9347]
### Repro steps
1. Create a new project from "Colorado COVID" template on the Cloud backend
2. Wait for the project to open

### Expected result
No errors

### Actual result
Connecting to Language Server times out

### Details
Console logs:
[localhost-1709807376658.log](https://github.com/enso-org/enso/files/14556006/localhost-1709807376658.log)

WebSocket messages:
Note that the first reply from the backend arrives 17 (!) seconds after the request. This is higher than the 15 second limit, which is demonstrated by the second request being sent after roughly 16 seconds.
![image](https://github.com/enso-org/enso/assets/4046547/2aa3496a-cb7c-4ab1-b61f-cc051188b61f)

Console logs (screenshots):
![image](https://github.com/enso-org/enso/assets/4046547/f6bed40c-67a0-4659-8173-0e9ee2832213)

![image](https://github.com/enso-org/enso/assets/4046547/b52feab7-6849-4696-a295-3a51ec947139)

**Comment by farmaazon** [comment]
I think the timeout itself is not much a problem; but the retry should properly interpret the 6002 error, and assume that the protocol is initialized.

There is however a problem here, namely that we need to know the response of initProtocol, because this is the only source of content roots. We could make sure we handle _every_ response of initProtocol, even if it's for timed out request, but I'm not sure if libraries we use allows that.

I think the proper solution is to add an endpoint to language server `file/roots` allowing us to ask for them if needed. @4e6 are you able to add one?

**Comment by farmaazon** [comment]
Refinement notes: 
* For now, let's increase the timeout. We can check if it's possible to retrieve proper response on 6002 error.
* Estimate includes possible unit tests for handling the error code, what may require slight refactoring.

**Comment by 4e6** [comment]
@farmaazon errors can have a `payload` field with arbitrary JSON. We can even send the context roots with the `6002` Session already initialised error. Adding the `file/roots` endpoint is also possible
