### ISSUE TITLE
Make autoscoping work in components like filter

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9417]
When we add a filter component and choose a filter condition it should be added with the .. autoscoping

![image](https://github.com/enso-org/enso/assets/1720119/902f31ae-b941-48b6-badf-c81cf60c86dd)

becomes (without the lhs)

![image](https://github.com/enso-org/enso/assets/1720119/bf0442e2-77c0-42f6-84f7-554880e7cf0a)

**Comment by somebody1234** [comment]
nit: I think the `..` autoscoping operator should be white, to make it clear that it's autoscoped and not just the variable `Equal`

**Comment by AdRiley** [comment]
If it was a variable wouldn't it have an incoming connection?

I prefer the .. in the lighter colour as I think it makes it more readable. But subjective opinion I know.

**Comment by farmaazon** [comment]
I guess #9277 must be implemented first. 

It's a bit strange we display `lhs` for `..` as `..` should be considered a unary operator.

Also it's still not clear to me, how is the state of sending us arguments for autoscoped constructor.

**Comment by Frizi** [comment]
Question from refinement:
- When is it safe to use .. operator instead of import?

For now we will assume that if all tag values are a constructor for the same type, we can transform them to `..`, or use suggestion database information if provided.

Since the `filter` method uses dynamic dropdowns, we can use `Text.trim` method as a test case to unblock this task.

**Comment by kazcw** [comment]
Cf. https://github.com/orgs/enso-org/discussions/8646#discussioncomment-8630661

<blockquote><img src="https://opengraph.githubassets.com/7c9caa737cbe238b36faba88451b8f7d5539e7bb7c6bf365f755e58496924d4b/orgs/enso-org/discussions/8646" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/8646">Autoscoping of constructors · enso-org · Discussion #8646</a></strong></div><div>Do you remember how ugly it is to always prefix a constructor of a type with its type name? Always write something like: table.aggregate Aggregate_Column.Count Enso should do better! Let's discuss ...</div></blockquote>

**Comment by farmaazon** [comment]
> **Adam Obuchowicz** reports a new **STANDUP** for yesterday (2024-05-20):

Ups, wrong ticket. It was supposed for #9878

**Comment by farmaazon** [comment]
Right now filter's widgets cannot use autoscope, because the engine does not seem to support them:

![Image](https://github.com/enso-org/enso/assets/3919101/9040269e-e472-4a1b-98a8-8b8d279e65c6)

I _guess_ that's because filter does not simply take `Filter_Condition` as argument, but 
```enso
    filter : (Column | Expression | Text | Integer) -> (Filter_Condition | (Any -> Boolean)) -> Problem_Behavior -> Table ! No_Such_Column | Index_Out_Of_Bounds | Invalid_Value_Type
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I don't know if current design allows autoscoping in such cases, but - if not - then it should be redesigned to close this issue.

**Comment by jdunkerley** [comment]
Tested and working in GUI.
