### ISSUE TITLE
Automate the Rust Code Generation

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#942]
### Summary
Now that the flexer can generate rust code for the DFA, it is important that we find a way to automate this generation from the lexer definitions to ensure that things stay in sync with the definition.

### Value
We won't get out of sync as might have otherwise happened if it was done by hand. 

### Specification

- [ ] Work out how to automate the generation of the lexer code at build time. You can assume that a lexer definition will construct rust code in an appropriate format (a string, for example). 
- [ ] Document this in the flexer design docs.
- [ ] Implement this automation step for use by the Enso lexer.
- [ ] This may involve `build.rs` work or procedural macros.
- [ ] It must recompile the lexer if the lexer definition changes _or_ if the definition of flexer changes, but should not do it spuriously (i.e. unconditionally recompiling is _not_ an option).

### Acceptance Criteria & Test Cases

- The lexer code is automatically generated at build time by cargo.

**Comment by Kesanov** [comment]
### Design
 
If we were to generate the source code manually from lexer `definition`, we would have to execute `cargo run --generate; cargo build`. In order to automate this, the code generation must happen in separate crate `engine` (since it isn't possible to run any cargo command on a crate that is being built by cargo).

While the `definition` should contain the source code enso lexer that implements flexer interface, the`engine` should only include the generated enso lexer, tests, benchmarks and a build script (or macro) that executes `definition::lexer().specialize()` during compilation.

Disadvantage of this design is that call to `specialize` is executed on each rebuild of `engine`, even when it doesn't have any effect on the lexer definition. Since cargo doesn't have any support for detection of what event triggered the rebuild, there seems to be no easy way to correct this behavior. Hopefully this shouldn't be a big problem, since 99% of code should be located in `definition`.

The current design generates the specialized code within `engine/build.rs`. Compared to procedural macros, this method is simpler and does not break any IDE features (like auto-completion). But as the parser gets more mature, the build script should be most likely replaced by a procedural macro.

**Comment by wdanilo** [comment]
I don't understand few things in the design:
1. What is the proposed layout of crates?
2. What does `cargo run --generate` do?
3. `In order to automate this, the code generation must happen in separate crate engine` - why? What is the desired layout of crates and their cargo dependencies? For the first time I hear the name `crate engine` - what is it?
4. I know what it is, but it should be explained to people who don't know it - what is `definition::lexer().specialize()`, what is its output and that the output should be able to use that and that fro other crates. This needs to be part of design doc.
5. `Disadvantage of this design is that call to specialize is executed on each rebuild of engine` - I do not understand this still. Could you show what are the crates, their dependencies, where is the build script etc? Just show that as a tree structure and describe what each crate does. What do you do in build.rs ? Are you using pre or post build scripts? All these information needs to be there to really help with that.

**Comment by Kesanov** [comment]
1. This was already part of the PR.
```
- root/
  - lexer-definition/
    - src/
      - lexer.rs <-- lexer definition
    - cargo.toml
  - lexer-engine/
    - src/
      - main.rs  <-- imports generated lexer from `lexer.rs` and uses it
      - lexer.rs <-- contains `include!("lexer-engine.rs")`
    - build.rs   <-- calls `lexer_definition::lexer().specialize()`
                  -- and saves its output to `src/lexer-engine.rs`
    - cargo.toml <-- lexer-definition is in dependencies and build-dependencies
```
2. Identical to `build.rs`: `cargo run --generate` executes `lexer_definition::lexer().specialize()` and saves its result to disk.
3. Because "it isn't possible to run any cargo command on a crate that is being built by cargo".
4. @iamrecursion already documented the API of specialized code generation in `docs/parser/flexer.md`.
5. Cargo has no post build script.
