### ISSUE TITLE
Writing space in the Code Editor opens some random project.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9450]
To reproduce: open some project and start editing code editor: type some letters and a space
Expected: space is written
Actual: space is not written, and then some random project opens. When going back to dashboard, you see two projects running at once. Entering the old one displays nothing.

Some focus issue between GUI and dashboard.

**Comment by somebody1234** [comment]
yeah, this is probably due to the new(ish) keyboard navigation handling in the dashboard...

but to be fair, i'm pretty sure usually the dashboard attaches handlers on `document`, so as long as codemirror's keyboard handler isn't on `document` itself maybe it should be fine?

perhaps it will help if GUI2 does `@keydown.stop` (or similar) on the code editor. maybe exceptions might need to be made for e.g. `Escape` if that is supposed to unfocus the Code Editor

**Comment by farmaazon** [comment]
> perhaps it will help if GUI2 does @keydown.stop (or similar) on the code editor. maybe exceptions might need to be made for e.g. Escape if that is supposed to unfocus the Code Editor

So far, we rather stopped certain events (Enter, Backspace etc.) to keep all shortcuts working in code editor. So we should add stop for space, or... think about different way of stopping events: perhaps we should stop all events without modifiers (except Esc perhaps)?

**Comment by farmaazon** [comment]
Refinement note: a dashboard issue - the dashboard should know what shortcuts should work when in project view.

**Comment by somebody1234** [comment]
can't repro, can anyone repro on develop? (if so, could you post repro steps?)

**Comment by farmaazon** [comment]
Indeed, I don't reproduce it too. Closing then.
