### ISSUE TITLE
File browse defaults to folder browse

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9503]
https://github.com/enso-org/enso/assets/1720119/d621e7a3-4f43-4a55-a164-c3e4b8931ebb

Should be a file browse.

Also should the file browse be modal?

**Comment by farmaazon** [comment]
The same problem is on Linux:

![image](https://github.com/enso-org/enso/assets/3919101/d94609db-bc8e-4246-86c1-c6f1f6001564)

I can click only folders here.

**Comment by vitvakatu** [comment]
The issue is probably caused by weird Electron behavior. See the relevant code here: https://github.com/enso-org/enso/blob/c983d081d98c803d38bc5a32b0c17bc29fd27b9a/app/ide-desktop/lib/client/src/index.ts#L381

The documentation: https://www.electronjs.org/docs/latest/api/dialog#dialogshowopendialogbrowserwindow-options

Apparently we shouldn’t pass `openDirectory` property on Linux and Windows. I didn’t find any open issue in the Electron repo about it.

<blockquote><div><strong><a href="https://electronjs.org/docs/latest/api/dialog">dialog | Electron</a></strong></div><div>Display native system dialogs for opening and saving files, alerting, etc.</div></blockquote>
