### ISSUE TITLE
Improve operator12345 names

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9829]
When auto-generating the variable names we would like to use the return type of the component and an incrementing number per type

e.g.

![image](https://github.com/enso-org/enso/assets/1720119/bb5d349d-cd45-4e08-a542-d912ade9fedd)

![image](https://github.com/enso-org/enso/assets/1720119/2ab54f74-c191-4c8e-a495-563d19ac837f)

**Comment by farmaazon** [comment]
Refinement notes:
* The name-picking algorithm should be simple and not too complex: let's use the return type of the first suggestion explicitly picked by user in component browser.
* The numbers should be incremental. Handling conflicts caused by multiple users' edits is _not_ in the scope of this task.
* Also literals should have their names (name, text, list...) matching their types shown to the user.
