### ISSUE TITLE
Make Output Port appear under visualisation when visualisation pane open

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9830]
- The below diagram just shows the general concept and should not be relied on for colors/spacing/shape
- Refer to figma or existing spacing/shape/color for actual implementation

![image](https://github.com/enso-org/enso/assets/1720119/2ae29274-70d7-469e-9292-2d845a70d83f)

**Comment by farmaazon** [comment]
Refinement note:
* The issue includes moving edges ends to actual output port position (updating the port rects properly). They should be updated when visualization opens.
* For first PR, do not spent too much time on making nice E2E tests, because we must confirm the design is good first.
* Make sure the interactions with "selection highlight" are good (intuitive for the user).

**Comment by kazcw** [comment]
When this is implemented, we should reapply the changes in #9848 to close #9783. Currently, when the visualization is open we are layering the output ports in between the visualization background and its toolbars. Once the ports are moved, the visualization can have its own stacking context because nothing needs to be sandwiched between its elements.
