### ISSUE TITLE
`System.exit` makes GUI unable to initialize the project - don't exit the sandbox!

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#9872]
This is partially expected, but I'm wondering if we should explicitly disallow usage of `System.exit` inside of GUI.

![image](https://github.com/enso-org/enso/assets/1436948/75e1f206-67cc-4f9f-82cb-afab008bad9f)

Because it shuts down the process, it kills the Language Server before it gets a chance to initialize.

The biggest problem is - the user _can_ insert the `System.exit` node into a workflow, but afterwards it becomes _impossible to remove it_. Because to remove it the Language Server needs to initialize, but it shuts down before it has the chance to do so - breaking such a workflow completely, until it is manually edited in an external editor.

**Comment by radeusgd** [comment]
We definitely do not want to allow `System.exit` from breaking the Language Server.

Perhaps it should Panic if ran in interactive mode instead?

**Comment by farmaazon** [comment]
Shouldn't `System.exit` exit _the current execution_ instead of the entire process in this case?

I imagine GUI just receiving "Execution failed" message with "exited with code X" or something along.

**Comment by JaroslavTulach** [comment]
Truffle offers a _sandboxed way_ of doing exit. Instead of [calling System.exit directly](https://github.com/enso-org/enso/blob/43c80da8a313f48bc7b492f37cc9c651cf7dea71/engine/runtime/src/main/java/org/enso/interpreter/runtime/system/System.java#L56) one should throw an exception with [exit status](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/interop/InteropLibrary.html#getExceptionExitStatus(java.lang.Object)). The exception shall be caught by language server and exit  status shall be reported to the GUI, but the JVM **shall not exit** itself. Or:

> As of 22.0 Truffle has support for polyglot context hard explicit exit triggered by guest languages using [TruffleContext.closeExited(Node,int)](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleContext.html#closeExited-com.oracle.truffle.api.nodes.Node-int-). It provides a unified way for languages to trigger the exit of the underlying polyglot context.

More on [Truffle exit](https://github.com/oracle/graal/blob/master/truffle/docs/Exit.md).
