### ISSUE TITLE
Allow copying of text from errors and warnings

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9878]
When you get an error:
There isn't an easy way to get the text for copy/paste for reporting  the isssue.

![image](https://github.com/enso-org/enso/assets/1720119/4f14ef51-ea71-4e86-86a5-e6957eba828e)

Can we allow the selection and copying of the text?
Right click -> copy menu?

**Comment by farmaazon** [comment]
* Enable text selecting and context menu in the error message.
* We can check what options are in context menu and configure electron to adjust it (remove entries like "Print" or "Inspect").

**Comment by vitvakatu** [comment]
We significantly underestimated this task.

- Enabling selection for text is easy, but it conflicts with the node output port. Selecting text without using the triple-click can be difficult.
- Electron does not provide us with a ready-to-use context menu! We don’t have it because it is not offered, not because we disable it.
- There is a library for Electron called [electron-context-menu](https://github.com/sindresorhus/electron-context-menu) that provides basic customizable context menu. But it requires Electron 30 or above. We’re on version 25 right now.
I was able to write code that opens a native context menu on right-click in the app, but I still need to implement actual text copying. I’m not sure I understand how exactly it should work.
- Besides, the context menu conflicts with the navigator now – the right click is used there for zooming.

WIP code is available in #9988

**Comment by farmaazon** [comment]
Because the previous approach would require some designing, we decided to, for now, create a button for copying entire message.
