### ISSUE TITLE
Add drag handle mouse cursor

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9906]
When my mouse is hovered over an area that I can use to drag a component round (component icon/drag halo) it should change to a drag cursor so that I know.

**Comment by farmaazon** [comment]
Refinement:
* Node background should set "grab". Every widget which has different interaction should change cursor by itself (clicking is more important than drag).
* When moving node, the cursor should be `grabbing`
* Vector Editor handle should use the same cursor.
* To consider: maybe change cursor to grabbing only when actually dragging node? Because clicking on a node can do other actions than just dragging.
